package ai.h2o.hive.udf.models;
/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2016-03-16T13:29:03.931-07:00
  3.8.1.3
  
  Standalone prediction code with sample test data for GBMModel named gbm2

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/gbm2 > gbm2.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m gbm2.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="gbm2", algorithm="gbm")
public class gbm2 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 3; }
  public int nclasses() { return 1; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_gbm2.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* C2 */ null,
    /* C3 */ null,
    /* C4 */ null,
    /* C9 */ null
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {1.0};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {1.0};

  public gbm2() { super(NAMES,DOMAINS); }
  public String getUUID() { return Long.toString(-2483140663945695954L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    double[] fdata = hex.genmodel.GenModel.SharedTree_clean(data);
    gbm2_Forest_0.score0(fdata,preds);
    gbm2_Forest_1.score0(fdata,preds);
    gbm2_Forest_2.score0(fdata,preds);
    gbm2_Forest_3.score0(fdata,preds);
    gbm2_Forest_4.score0(fdata,preds);
    gbm2_Forest_5.score0(fdata,preds);
    gbm2_Forest_6.score0(fdata,preds);
    gbm2_Forest_7.score0(fdata,preds);
    gbm2_Forest_8.score0(fdata,preds);
    gbm2_Forest_9.score0(fdata,preds);
    gbm2_Forest_10.score0(fdata,preds);
    gbm2_Forest_11.score0(fdata,preds);
    gbm2_Forest_12.score0(fdata,preds);
    gbm2_Forest_13.score0(fdata,preds);
    gbm2_Forest_14.score0(fdata,preds);
    gbm2_Forest_15.score0(fdata,preds);
    gbm2_Forest_16.score0(fdata,preds);
    gbm2_Forest_17.score0(fdata,preds);
    gbm2_Forest_18.score0(fdata,preds);
    gbm2_Forest_19.score0(fdata,preds);
    gbm2_Forest_20.score0(fdata,preds);
    gbm2_Forest_21.score0(fdata,preds);
    gbm2_Forest_22.score0(fdata,preds);
    gbm2_Forest_23.score0(fdata,preds);
    gbm2_Forest_24.score0(fdata,preds);
    gbm2_Forest_25.score0(fdata,preds);
    gbm2_Forest_26.score0(fdata,preds);
    gbm2_Forest_27.score0(fdata,preds);
    gbm2_Forest_28.score0(fdata,preds);
    gbm2_Forest_29.score0(fdata,preds);
    gbm2_Forest_30.score0(fdata,preds);
    gbm2_Forest_31.score0(fdata,preds);
    gbm2_Forest_32.score0(fdata,preds);
    gbm2_Forest_33.score0(fdata,preds);
    gbm2_Forest_34.score0(fdata,preds);
    gbm2_Forest_35.score0(fdata,preds);
    gbm2_Forest_36.score0(fdata,preds);
    gbm2_Forest_37.score0(fdata,preds);
    gbm2_Forest_38.score0(fdata,preds);
    gbm2_Forest_39.score0(fdata,preds);
    gbm2_Forest_40.score0(fdata,preds);
    gbm2_Forest_41.score0(fdata,preds);
    gbm2_Forest_42.score0(fdata,preds);
    gbm2_Forest_43.score0(fdata,preds);
    gbm2_Forest_44.score0(fdata,preds);
    gbm2_Forest_45.score0(fdata,preds);
    gbm2_Forest_46.score0(fdata,preds);
    gbm2_Forest_47.score0(fdata,preds);
    gbm2_Forest_48.score0(fdata,preds);
    gbm2_Forest_49.score0(fdata,preds);
    preds[0] += 9.933684462532918;
    preds[0] = preds[0];
    return preds;
  }
}
// The class representing training column names
class NamesHolder_gbm2 implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    NamesHolder_gbm2_0.fill(VALUES);
  }
  static final class NamesHolder_gbm2_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "C2";
      sa[1] = "C3";
      sa[2] = "C4";
    }
  }
}

class gbm2_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_0_class_0.score0(fdata);
  }
}
class gbm2_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.122490235f
      ? (data[1 /* C3 */] <0.24268067f
        ? (data[0 /* C2 */] <0.25266603f
          ? (data[1 /* C3 */] <0.1128125f
            ? -0.67029154f
            : (data[1 /* C3 */] <0.16754882f ? -0.5617895f : -0.50479704f))
          : (data[1 /* C3 */] <0.22265625f
            ? (data[1 /* C3 */] <0.19218017f ? -0.4800351f : -0.41559067f)
            : (data[0 /* C2 */] <0.29796875f ? -0.22973208f : -0.34875306f)))
        : (data[1 /* C3 */] <0.38256344f
          ? (data[2 /* C4 */] <0.1021875f
            ? (data[1 /* C3 */] <0.32726562f ? -0.2651446f : -0.17670177f)
            : (data[1 /* C3 */] <0.3473047f ? -0.17095464f : -0.1365057f))
          : (data[1 /* C3 */] <0.42291522f
            ? (data[0 /* C2 */] <0.52308595f ? -0.020234115f : -0.0972146f)
            : (data[2 /* C4 */] <0.11179688f ? -0.011550262f : 0.23821051f))))
      : (data[2 /* C4 */] <0.16282998f
        ? (data[2 /* C4 */] <0.13748685f
          ? (data[1 /* C3 */] <0.40875f
            ? (data[0 /* C2 */] <0.498125f ? -0.0047545806f : -0.0858342f)
            : (data[1 /* C3 */] <0.4225879f ? 0.0721488f : 0.004034153f))
          : (data[1 /* C3 */] <0.51125f
            ? (data[1 /* C3 */] <0.42634767f ? 0.10491236f : 0.03731173f)
            : (data[2 /* C4 */] <0.15734375f ? 0.1399649f : 0.26853633f)))
        : (data[2 /* C4 */] <0.19305405f
          ? (data[0 /* C2 */] <0.5674414f
            ? (data[1 /* C3 */] <0.4517969f ? 0.2785942f : 0.50663155f)
            : (data[1 /* C3 */] <0.571875f ? 0.1566971f : 0.38440934f))
          : (data[2 /* C4 */] <0.22233361f
            ? (data[0 /* C2 */] <0.7025f ? 0.32184896f : 0.2002213f)
            : (data[1 /* C3 */] <0.49789062f ? 0.29754066f : 0.5177427f)))));
    return pred;
  }
}


class gbm2_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_1_class_0.score0(fdata);
  }
}
class gbm2_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.122490235f
      ? (data[1 /* C3 */] <0.23745117f
        ? (data[0 /* C2 */] <0.25266603f
          ? (data[0 /* C2 */] <0.16730306f
            ? -0.58067936f
            : (data[1 /* C3 */] <0.1675f ? -0.5009725f : -0.4543173f))
          : (data[1 /* C3 */] <0.22234374f
            ? (data[2 /* C4 */] <0.0625f ? -0.4227791f : -0.37183115f)
            : (data[0 /* C2 */] <0.29796875f ? -0.20675892f : -0.32588446f)))
        : (data[1 /* C3 */] <0.38273063f
          ? (data[2 /* C4 */] <0.1021875f
            ? (data[1 /* C3 */] <0.3275f ? -0.24039598f : -0.15903161f)
            : (data[0 /* C2 */] <0.359375f ? -0.24483947f : -0.13739552f))
          : (data[1 /* C3 */] <0.42251477f
            ? (data[0 /* C2 */] <0.52308595f ? -0.018210696f : -0.08749312f)
            : (data[2 /* C4 */] <0.11179688f ? -0.010395259f : 0.21438944f))))
      : (data[2 /* C4 */] <0.16282998f
        ? (data[2 /* C4 */] <0.15255973f
          ? (data[1 /* C3 */] <0.30125f
            ? -0.25852334f
            : (data[2 /* C4 */] <0.13242188f ? -0.021884302f : 0.032921456f))
          : (data[1 /* C3 */] <0.37625f
            ? -0.13113244f
            : (data[1 /* C3 */] <0.40723634f ? 0.2921403f : 0.08829614f)))
        : (data[2 /* C4 */] <0.21194409f
          ? (data[0 /* C2 */] <0.5733008f
            ? (data[1 /* C3 */] <0.46234375f ? 0.25294834f : 0.57550925f)
            : (data[2 /* C4 */] <0.1875f ? 0.13343072f : 0.22718339f))
          : (data[1 /* C3 */] <0.54222655f
            ? (data[1 /* C3 */] <0.48810637f ? 0.33460313f : 0.60612625f)
            : (data[2 /* C4 */] <0.22929688f ? 0.22983445f : 0.3477144f)))));
    return pred;
  }
}


class gbm2_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_2_class_0.score0(fdata);
  }
}
class gbm2_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.122490235f
      ? (data[1 /* C3 */] <0.24268067f
        ? (data[1 /* C3 */] <0.1876961f
          ? (data[1 /* C3 */] <0.1125362f
            ? -0.54580754f
            : (data[1 /* C3 */] <0.16745017f ? -0.45532194f : -0.40447837f))
          : (data[1 /* C3 */] <0.22263347f
            ? (data[2 /* C4 */] <0.06234375f ? -0.3891997f : -0.33004737f)
            : (data[0 /* C2 */] <0.29773438f ? -0.18608306f : -0.28378135f)))
        : (data[1 /* C3 */] <0.38256344f
          ? (data[2 /* C4 */] <0.1021875f
            ? (data[1 /* C3 */] <0.34308594f ? -0.21176113f : -0.106223665f)
            : (data[1 /* C3 */] <0.3473047f ? -0.1397491f : -0.109062925f))
          : (data[1 /* C3 */] <0.42291522f
            ? (data[2 /* C4 */] <0.11179688f ? -0.07886629f : -0.015394798f)
            : (data[2 /* C4 */] <0.11179688f ? -0.009355754f : 0.19295047f))))
      : (data[2 /* C4 */] <0.1579105f
        ? (data[2 /* C4 */] <0.13746999f
          ? (data[1 /* C3 */] <0.30835938f
            ? -0.18962337f
            : (data[0 /* C2 */] <0.434375f ? 0.15851243f : -0.013749628f))
          : (data[0 /* C2 */] <0.5076563f
            ? (data[1 /* C3 */] <0.37921876f ? 0.040007956f : 0.19447735f)
            : (data[2 /* C4 */] <0.15242188f ? 0.015934266f : 0.068961665f)))
        : (data[2 /* C4 */] <0.18259245f
          ? (data[0 /* C2 */] <0.57183594f
            ? (data[1 /* C3 */] <0.370625f ? -0.03994929f : 0.21673647f)
            : (data[1 /* C3 */] <0.53234375f ? 0.093460485f : 0.212258f))
          : (data[2 /* C4 */] <0.21219894f
            ? (data[0 /* C2 */] <0.573125f ? 0.32372957f : 0.1939043f)
            : (data[1 /* C3 */] <0.54398435f ? 0.4640567f : 0.23655674f)))));
    return pred;
  }
}


class gbm2_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_3_class_0.score0(fdata);
  }
}
class gbm2_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.122490235f
      ? (data[1 /* C3 */] <0.24268067f
        ? (data[0 /* C2 */] <0.25266603f
          ? (data[1 /* C3 */] <0.1128125f
            ? -0.49122676f
            : (data[1 /* C3 */] <0.16754882f ? -0.40886235f : -0.36882508f))
          : (data[1 /* C3 */] <0.22265625f
            ? (data[1 /* C3 */] <0.19218017f ? -0.35431424f : -0.3020644f)
            : (data[0 /* C2 */] <0.29796875f ? -0.16747478f : -0.25540325f)))
        : (data[1 /* C3 */] <0.38256344f
          ? (data[2 /* C4 */] <0.1021875f
            ? (data[0 /* C2 */] <0.438125f ? -0.19240937f : -0.11591314f)
            : (data[1 /* C3 */] <0.3473047f ? -0.12577415f : -0.09815661f))
          : (data[1 /* C3 */] <0.42291522f
            ? (data[0 /* C2 */] <0.52308595f ? -0.012860754f : -0.0757396f)
            : (data[2 /* C4 */] <0.11179688f ? -0.008420199f : 0.17365544f))))
      : (data[2 /* C4 */] <0.16282998f
        ? (data[2 /* C4 */] <0.13748685f
          ? (data[1 /* C3 */] <0.40875f
            ? (data[0 /* C2 */] <0.5034375f ? -0.005808094f : -0.08259173f)
            : (data[1 /* C3 */] <0.4225879f ? 0.066512935f : 0.0046674036f))
          : (data[1 /* C3 */] <0.51125f
            ? (data[1 /* C3 */] <0.42634767f ? 0.08178237f : 0.022764318f)
            : (data[0 /* C2 */] <0.6325f ? 0.25652376f : 0.13092323f)))
        : (data[2 /* C4 */] <0.19305405f
          ? (data[0 /* C2 */] <0.5674414f
            ? (data[1 /* C3 */] <0.4517969f ? 0.20414557f : 0.3999101f)
            : (data[1 /* C3 */] <0.571875f ? 0.11313399f : 0.30929407f))
          : (data[0 /* C2 */] <0.6670508f
            ? (data[2 /* C4 */] <0.20960937f ? 0.2357557f : 0.36332712f)
            : (data[1 /* C3 */] <0.539375f ? 0.033190653f : 0.21071912f)))));
    return pred;
  }
}


class gbm2_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_4_class_0.score0(fdata);
  }
}
class gbm2_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.12745605f
      ? (data[1 /* C3 */] <0.27754393f
        ? (data[1 /* C3 */] <0.22234261f
          ? (data[1 /* C3 */] <0.182468f
            ? (data[1 /* C3 */] <0.12271737f ? -0.42653954f : -0.35291913f)
            : (data[2 /* C4 */] <0.06273437f ? -0.31899428f : -0.26859137f))
          : (data[0 /* C2 */] <0.3573047f
            ? (data[2 /* C4 */] <0.08265625f ? -0.21624404f : -0.15253372f)
            : (data[2 /* C4 */] <0.09703125f ? -0.24894908f : -0.18968016f)))
        : (data[1 /* C3 */] <0.39766333f
          ? (data[2 /* C4 */] <0.10253906f
            ? (data[2 /* C4 */] <0.092926025f ? -0.17884529f : -0.13239315f)
            : (data[2 /* C4 */] <0.12236786f ? -0.09437874f : -0.05887072f))
          : (data[0 /* C2 */] <0.5573633f
            ? (data[2 /* C4 */] <0.122421876f ? 0.021506662f : -0.03830279f)
            : (data[0 /* C2 */] <0.5725615f ? 0.16527225f : 0.029883446f))))
      : (data[2 /* C4 */] <0.16270174f
        ? (data[2 /* C4 */] <0.15248245f
          ? (data[0 /* C2 */] <0.5076563f
            ? (data[1 /* C3 */] <0.34234375f ? -0.07206522f : 0.0767195f)
            : (data[1 /* C3 */] <0.4665625f ? -0.0056146206f : 0.04582269f))
          : (data[1 /* C3 */] <0.37625f
            ? -0.12709026f
            : (data[1 /* C3 */] <0.40723634f ? 0.2370093f : 0.06528376f)))
        : (data[2 /* C4 */] <0.18159428f
          ? (data[0 /* C2 */] <0.5733008f
            ? (data[1 /* C3 */] <0.4517969f ? 0.17107932f : 0.28919703f)
            : (data[1 /* C3 */] <0.53875f ? 0.08089064f : 0.17370878f))
          : (data[2 /* C4 */] <0.21123196f
            ? (data[1 /* C3 */] <0.58085936f ? 0.15874748f : 0.30438837f)
            : (data[1 /* C3 */] <0.54398435f ? 0.38491726f : 0.19091348f)))));
    return pred;
  }
}


class gbm2_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_5_class_0.score0(fdata);
  }
}
class gbm2_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.12745605f
      ? (data[1 /* C3 */] <0.27754393f
        ? (data[0 /* C2 */] <0.28725585f
          ? (data[1 /* C3 */] <0.16671875f
            ? (data[1 /* C3 */] <0.11260498f ? -0.39945015f : -0.33281714f)
            : (data[0 /* C2 */] <0.26203126f ? -0.2907938f : -0.2477939f))
          : (data[2 /* C4 */] <0.077714846f
            ? (data[1 /* C3 */] <0.22285156f ? -0.24280599f : -0.20897974f)
            : (data[0 /* C2 */] <0.3573828f ? -0.15002961f : -0.20958377f)))
        : (data[1 /* C3 */] <0.39766333f
          ? (data[2 /* C4 */] <0.10253906f
            ? (data[1 /* C3 */] <0.34289062f ? -0.14201684f : -0.074651085f)
            : (data[2 /* C4 */] <0.12236786f ? -0.084940895f : -0.05298369f))
          : (data[1 /* C3 */] <0.45266488f
            ? (data[2 /* C4 */] <0.122421876f ? 0.036024533f : -0.030716013f)
            : 0.11673374f)))
      : (data[2 /* C4 */] <0.16270174f
        ? (data[2 /* C4 */] <0.15248245f
          ? (data[0 /* C2 */] <0.4921875f
            ? (data[0 /* C2 */] <0.48702392f ? 0.035874713f : 0.26813298f)
            : (data[1 /* C3 */] <0.480625f ? 0.0019258073f : 0.06577384f))
          : (data[1 /* C3 */] <0.37625f
            ? -0.11438121f
            : (data[1 /* C3 */] <0.40723634f ? 0.2133084f : 0.05875538f)))
        : (data[2 /* C4 */] <0.18159428f
          ? (data[0 /* C2 */] <0.5733008f
            ? (data[1 /* C3 */] <0.4517969f ? 0.15397136f : 0.26027733f)
            : (data[1 /* C3 */] <0.4517969f ? 0.21553695f : 0.076438986f))
          : (data[2 /* C4 */] <0.21123196f
            ? (data[0 /* C2 */] <0.573125f ? 0.25171435f : 0.14134586f)
            : (data[1 /* C3 */] <0.54398435f ? 0.34642553f : 0.17182216f)))));
    return pred;
  }
}


class gbm2_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_6_class_0.score0(fdata);
  }
}
class gbm2_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.12745605f
      ? (data[1 /* C3 */] <0.27754393f
        ? (data[1 /* C3 */] <0.22234261f
          ? (data[0 /* C2 */] <0.25160158f
            ? (data[0 /* C2 */] <0.1674399f ? -0.34662455f : -0.28445336f)
            : (data[1 /* C3 */] <0.19292969f ? -0.25910452f : -0.22030303f))
          : (data[0 /* C2 */] <0.36246094f
            ? (data[2 /* C4 */] <0.08265625f ? -0.17778444f : -0.12876573f)
            : (data[2 /* C4 */] <0.09703125f ? -0.21765849f : -0.1560658f)))
        : (data[1 /* C3 */] <0.39766333f
          ? (data[2 /* C4 */] <0.10253906f
            ? (data[2 /* C4 */] <0.092926025f ? -0.14719981f : -0.10585043f)
            : (data[2 /* C4 */] <0.12236786f ? -0.0764468f : -0.047685362f))
          : (data[1 /* C3 */] <0.44762307f
            ? (data[2 /* C4 */] <0.11296875f ? -0.07272882f : 0.006006262f)
            : (data[1 /* C3 */] <0.45762435f ? 0.17392208f : 0.025332605f))))
      : (data[2 /* C4 */] <0.16270174f
        ? (data[1 /* C3 */] <0.5071289f
          ? (data[1 /* C3 */] <0.31512824f
            ? -0.18568718f
            : (data[1 /* C3 */] <0.4278646f ? 0.042545762f : 0.009985468f))
          : (data[0 /* C2 */] <0.63984376f
            ? 0.18182726f
            : (data[2 /* C4 */] <0.15742187f ? 0.044074323f : 0.15451247f)))
        : (data[2 /* C4 */] <0.1929298f
          ? (data[0 /* C2 */] <0.5674414f
            ? (data[0 /* C2 */] <0.5624632f ? 0.14579627f : 0.3062349f)
            : (data[1 /* C3 */] <0.5221875f ? 0.06981472f : 0.12813586f))
          : (data[0 /* C2 */] <0.6670508f
            ? (data[1 /* C3 */] <0.465625f ? 0.07987108f : 0.23221427f)
            : (data[1 /* C3 */] <0.539375f ? -0.005113741f : 0.15574668f)))));
    return pred;
  }
}


class gbm2_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_7_class_0.score0(fdata);
  }
}
class gbm2_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.12745605f
      ? (data[1 /* C3 */] <0.27754393f
        ? (data[1 /* C3 */] <0.22234261f
          ? (data[1 /* C3 */] <0.16743332f
            ? (data[1 /* C3 */] <0.11297343f ? -0.32532093f : -0.27027625f)
            : (data[0 /* C2 */] <0.261875f ? -0.23464245f : -0.19774304f))
          : (data[0 /* C2 */] <0.3573047f
            ? (data[1 /* C3 */] <0.25234374f ? -0.15645215f : -0.101605795f)
            : (data[2 /* C4 */] <0.09703125f ? -0.18436886f : -0.13460213f)))
        : (data[1 /* C3 */] <0.39766333f
          ? (data[2 /* C4 */] <0.10253906f
            ? (data[1 /* C3 */] <0.34289062f ? -0.115614966f : -0.05566729f)
            : (data[1 /* C3 */] <0.38242188f ? -0.06768182f : -0.036895946f))
          : (data[1 /* C3 */] <0.45266488f
            ? (data[2 /* C4 */] <0.122421876f ? 0.03239058f : -0.028944694f)
            : 0.09955533f)))
      : (data[2 /* C4 */] <0.1578065f
        ? (data[0 /* C2 */] <0.50751954f
          ? (data[1 /* C3 */] <0.3775f
            ? (data[1 /* C3 */] <0.32300782f ? -0.14255813f : 0.015190928f)
            : (data[2 /* C4 */] <0.14757812f ? 0.05772341f : 0.21541183f))
          : (data[1 /* C3 */] <0.39742187f
            ? (data[2 /* C4 */] <0.1425f ? -0.033358287f : -0.17385362f)
            : (data[2 /* C4 */] <0.15246093f ? 0.004533384f : 0.047668017f)))
        : (data[2 /* C4 */] <0.18249111f
          ? (data[0 /* C2 */] <0.5523828f
            ? (data[1 /* C3 */] <0.3940625f ? -0.014135488f : 0.17782123f)
            : (data[1 /* C3 */] <0.53234375f ? 0.05620319f : 0.14157397f))
          : (data[2 /* C4 */] <0.21210076f
            ? (data[0 /* C2 */] <0.7025f ? 0.13238831f : 0.062563784f)
            : (data[1 /* C3 */] <0.54398435f ? 0.29265684f : 0.13860646f)))));
    return pred;
  }
}


class gbm2_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_8_class_0.score0(fdata);
  }
}
class gbm2_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.12745605f
      ? (data[2 /* C4 */] <0.09745907f
        ? (data[1 /* C3 */] <0.22210938f
          ? (data[1 /* C3 */] <0.16792938f
            ? (data[1 /* C3 */] <0.113229215f ? -0.29278886f : -0.24324864f)
            : (data[2 /* C4 */] <0.07242188f ? -0.19995038f : -0.16387591f))
          : (data[0 /* C2 */] <0.428125f
            ? (data[2 /* C4 */] <0.0771875f ? -0.15440005f : -0.12294024f)
            : (data[1 /* C3 */] <0.3428125f ? -0.068005316f : 0.004975451f)))
        : (data[1 /* C3 */] <0.39730468f
          ? (data[2 /* C4 */] <0.1125f
            ? (data[1 /* C3 */] <0.35789064f ? -0.0880751f : -0.038018208f)
            : (data[0 /* C2 */] <0.458125f ? -0.027706029f : -0.0650958f))
          : (data[1 /* C3 */] <0.45247436f
            ? (data[2 /* C4 */] <0.12246094f ? 0.033128534f : -0.026050197f)
            : 0.12597865f)))
      : (data[2 /* C4 */] <0.1724922f
        ? (data[2 /* C4 */] <0.15249099f
          ? (data[0 /* C2 */] <0.49152344f
            ? (data[0 /* C2 */] <0.48741335f ? 0.027448433f : 0.23080371f)
            : (data[1 /* C3 */] <0.4665625f ? -0.004605993f : 0.03602471f))
          : (data[1 /* C3 */] <0.45625f
            ? (data[1 /* C3 */] <0.37708008f ? -0.04617353f : 0.09528671f)
            : (data[1 /* C3 */] <0.5326953f ? 0.02667067f : 0.16249262f)))
        : (data[0 /* C2 */] <0.51285154f
          ? -0.19562052f
          : (data[2 /* C4 */] <0.21230468f
            ? (data[0 /* C2 */] <0.5384375f ? 0.31947768f : 0.09521984f)
            : (data[1 /* C3 */] <0.5424219f ? 0.2837654f : 0.12474585f)))));
    return pred;
  }
}


class gbm2_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_9_class_0.score0(fdata);
  }
}
class gbm2_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.122490235f
      ? (data[1 /* C3 */] <0.24268067f
        ? (data[0 /* C2 */] <0.25266603f
          ? (data[0 /* C2 */] <0.16730306f
            ? -0.25433457f
            : (data[0 /* C2 */] <0.23772468f ? -0.20062529f : -0.22976738f))
          : (data[0 /* C2 */] <0.3223018f
            ? (data[1 /* C3 */] <0.223125f ? -0.16540568f : -0.14338219f)
            : (data[2 /* C4 */] <0.077109374f ? -0.117665395f : -0.09988838f)))
        : (data[1 /* C3 */] <0.38256344f
          ? (data[2 /* C4 */] <0.0975f
            ? (data[1 /* C3 */] <0.3378125f ? -0.10984141f : 0.05125814f)
            : (data[0 /* C2 */] <0.39875f ? -0.036932513f : -0.07236316f))
          : (data[1 /* C3 */] <0.42291522f
            ? (data[0 /* C2 */] <0.52308595f ? 0.0084505f : -0.06854211f)
            : (data[2 /* C4 */] <0.11179688f ? -0.026610695f : 0.12382399f))))
      : (data[2 /* C4 */] <0.1579105f
        ? (data[1 /* C3 */] <0.30259764f
          ? -0.18892677f
          : (data[2 /* C4 */] <0.13753906f
            ? (data[0 /* C2 */] <0.4321094f ? 0.12346084f : -0.011686722f)
            : (data[0 /* C2 */] <0.5210937f ? 0.0713748f : 0.009082203f)))
        : (data[1 /* C3 */] <0.5326953f
          ? (data[0 /* C2 */] <0.57183594f
            ? (data[1 /* C3 */] <0.39289063f ? -0.056892168f : 0.13343243f)
            : (data[2 /* C4 */] <0.20546874f ? 0.050208792f : 0.18254034f))
          : (data[0 /* C2 */] <0.70314455f
            ? (data[2 /* C4 */] <0.19882813f ? 0.14936225f : 0.24410072f)
            : (data[2 /* C4 */] <0.22101563f ? 0.04735317f : 0.22197132f)))));
    return pred;
  }
}


class gbm2_Forest_10 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_10_class_0.score0(fdata);
  }
}
class gbm2_Tree_10_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.37748536f
      ? (data[1 /* C3 */] <0.27765346f
        ? (data[0 /* C2 */] <0.262041f
          ? (data[0 /* C2 */] <0.20212944f
            ? (data[0 /* C2 */] <0.15743549f ? -0.2416872f : -0.20458268f)
            : (data[0 /* C2 */] <0.23739432f ? -0.16405332f : -0.18690711f))
          : (data[1 /* C3 */] <0.2371875f
            ? (data[0 /* C2 */] <0.32734376f ? -0.13962176f : -0.09835088f)
            : (data[0 /* C2 */] <0.35796875f ? -0.08350634f : -0.14000152f)))
        : (data[2 /* C4 */] <0.11917969f
          ? (data[2 /* C4 */] <0.09264359f
            ? (data[0 /* C2 */] <0.42734376f ? -0.11133785f : -0.019865822f)
            : (data[0 /* C2 */] <0.39679688f ? -0.01641124f : -0.07278879f))
          : (data[0 /* C2 */] <0.46722656f
            ? (data[1 /* C3 */] <0.30746093f ? -0.12441468f : 0.024617812f)
            : (data[1 /* C3 */] <0.3623828f ? -0.087123334f : -0.028014652f))))
      : (data[2 /* C4 */] <0.15780273f
        ? (data[2 /* C4 */] <0.1427415f
          ? (data[0 /* C2 */] <0.4929883f
            ? (data[2 /* C4 */] <0.1321875f ? 3.2054548E-5f : 0.10632592f)
            : (data[1 /* C3 */] <0.40191406f ? -0.038960412f : 0.00456356f))
          : (data[0 /* C2 */] <0.54253906f
            ? (data[0 /* C2 */] <0.5380252f ? 0.073646225f : 0.26319706f)
            : (data[1 /* C3 */] <0.45226562f ? -0.021835862f : 0.0265466f)))
        : (data[2 /* C4 */] <0.18222052f
          ? (data[1 /* C3 */] <0.41269532f
            ? (data[2 /* C4 */] <0.16265625f ? 0.15684362f : 0.23515527f)
            : (data[1 /* C3 */] <0.53288573f ? 0.04272875f : 0.105107404f))
          : (data[0 /* C2 */] <0.6481836f
            ? (data[1 /* C3 */] <0.5159375f ? 0.115486264f : 0.29396883f)
            : (data[1 /* C3 */] <0.528125f ? -0.005216729f : 0.112502076f)))));
    return pred;
  }
}


class gbm2_Forest_11 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_11_class_0.score0(fdata);
  }
}
class gbm2_Tree_11_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.34262207f
      ? (data[1 /* C3 */] <0.22240503f
        ? (data[1 /* C3 */] <0.16747525f
          ? (data[1 /* C3 */] <0.1125557f
            ? -0.21546261f
            : (data[2 /* C4 */] <0.0525f ? -0.18697302f : -0.16338f))
          : (data[2 /* C4 */] <0.072578125f
            ? (data[0 /* C2 */] <0.23734374f ? -0.108921394f : -0.15113252f)
            : (data[2 /* C4 */] <0.08243286f ? -0.10265547f : -0.16976285f)))
        : (data[2 /* C4 */] <0.09773438f
          ? (data[2 /* C4 */] <0.077500306f
            ? (data[2 /* C4 */] <0.0672073f ? -0.06294127f : -0.12449644f)
            : (data[0 /* C2 */] <0.35746095f ? -0.0675813f : -0.100026295f))
          : (data[0 /* C2 */] <0.41683593f
            ? (data[1 /* C3 */] <0.3071875f ? -0.06521458f : 0.002251232f)
            : (data[2 /* C4 */] <0.116875f ? -0.09850736f : -0.01627507f))))
      : (data[2 /* C4 */] <0.15228516f
        ? (data[2 /* C4 */] <0.12761673f
          ? (data[0 /* C2 */] <0.5569922f
            ? (data[0 /* C2 */] <0.45818174f ? 0.0084930165f : -0.040940657f)
            : (data[0 /* C2 */] <0.57225126f ? 0.14268924f : -0.003805532f))
          : (data[0 /* C2 */] <0.49220702f
            ? (data[2 /* C4 */] <0.14734375f ? 0.04664139f : 0.28483382f)
            : (data[1 /* C3 */] <0.4825f ? -0.003369474f : 0.04924784f)))
        : (data[2 /* C4 */] <0.18283875f
          ? (data[0 /* C2 */] <0.608457f
            ? (data[1 /* C3 */] <0.483125f ? 0.059043806f : 0.14498104f)
            : (data[1 /* C3 */] <0.49734375f ? -0.015596423f : 0.05583356f))
          : (data[1 /* C3 */] <0.43197265f
            ? -0.05236163f
            : (data[0 /* C2 */] <0.5675f ? 0.25585654f : 0.08838334f)))));
    return pred;
  }
}


class gbm2_Forest_12 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_12_class_0.score0(fdata);
  }
}
class gbm2_Tree_12_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.37748536f
      ? (data[1 /* C3 */] <0.27765346f
        ? (data[0 /* C2 */] <0.262041f
          ? (data[1 /* C3 */] <0.15296875f
            ? (data[2 /* C4 */] <0.0525f ? -0.17836729f : -0.13913667f)
            : (data[0 /* C2 */] <0.2383203f ? -0.122725144f : -0.15347603f))
          : (data[1 /* C3 */] <0.2371875f
            ? (data[0 /* C2 */] <0.29671875f ? -0.10241689f : -0.123589896f)
            : (data[0 /* C2 */] <0.36234376f ? -0.07120705f : -0.12710273f)))
        : (data[2 /* C4 */] <0.11917969f
          ? (data[1 /* C3 */] <0.3527344f
            ? (data[0 /* C2 */] <0.39679688f ? -0.039639093f : -0.07275635f)
            : (data[0 /* C2 */] <0.45789063f ? 0.052829813f : -0.05423806f))
          : (data[0 /* C2 */] <0.46722656f
            ? (data[2 /* C4 */] <0.13578124f ? -0.008557026f : 0.105014965f)
            : (data[2 /* C4 */] <0.1515625f ? -0.034274403f : -0.12798265f))))
      : (data[2 /* C4 */] <0.17325196f
        ? (data[2 /* C4 */] <0.14265245f
          ? (data[0 /* C2 */] <0.48337892f
            ? (data[0 /* C2 */] <0.4774498f ? -0.01329051f : 0.21376617f)
            : (data[1 /* C3 */] <0.40191406f ? -0.024676258f : 0.003848903f))
          : (data[1 /* C3 */] <0.41683593f
            ? (data[0 /* C2 */] <0.49375f ? 0.214448f : 0.07747217f)
            : (data[1 /* C3 */] <0.5324487f ? 0.016512105f : 0.11111141f)))
        : (data[2 /* C4 */] <0.21263307f
          ? (data[0 /* C2 */] <0.5667578f
            ? (data[1 /* C3 */] <0.45226562f ? 0.10905295f : 0.2666802f)
            : (data[1 /* C3 */] <0.5772656f ? 0.05460483f : 0.155562f))
          : (data[0 /* C2 */] <0.6684766f
            ? (data[1 /* C3 */] <0.5171875f ? 0.14259213f : 0.3973508f)
            : (data[1 /* C3 */] <0.596875f ? 0.10516399f : -0.024831248f)))));
    return pred;
  }
}


class gbm2_Forest_13 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_13_class_0.score0(fdata);
  }
}
class gbm2_Tree_13_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.37748536f
      ? (data[1 /* C3 */] <0.27765346f
        ? (data[0 /* C2 */] <0.28711915f
          ? (data[1 /* C3 */] <0.1821875f
            ? (data[0 /* C2 */] <0.23742187f ? -0.13998632f : -0.17316808f)
            : (data[1 /* C3 */] <0.20259033f ? -0.09793487f : -0.12837039f))
          : (data[0 /* C2 */] <0.36263657f
            ? (data[1 /* C3 */] <0.27207032f ? -0.07814121f : 0.023279171f)
            : (data[0 /* C2 */] <0.37752995f ? -0.12895246f : -0.06754442f)))
        : (data[2 /* C4 */] <0.11917969f
          ? (data[2 /* C4 */] <0.09264359f
            ? (data[0 /* C2 */] <0.43132812f ? -0.08400973f : 0.0052348804f)
            : (data[0 /* C2 */] <0.39679688f ? -0.003875698f : -0.054167032f))
          : (data[0 /* C2 */] <0.46722656f
            ? (data[2 /* C4 */] <0.13578124f ? -0.007701294f : 0.09451348f)
            : (data[2 /* C4 */] <0.1515625f ? -0.03084699f : -0.11518434f))))
      : (data[2 /* C4 */] <0.16773437f
        ? (data[2 /* C4 */] <0.14237808f
          ? (data[0 /* C2 */] <0.4666992f
            ? 0.11139596f
            : (data[0 /* C2 */] <0.47763517f ? -0.12410459f : -0.003125297f))
          : (data[1 /* C3 */] <0.41683593f
            ? (data[0 /* C2 */] <0.49375f ? 0.1930032f : 0.07165878f)
            : (data[1 /* C3 */] <0.4969766f ? 0.004470775f : 0.05482003f)))
        : (data[2 /* C4 */] <0.21249908f
          ? (data[0 /* C2 */] <0.59824216f
            ? (data[1 /* C3 */] <0.46203125f ? 0.072603025f : 0.18939373f)
            : (data[1 /* C3 */] <0.5128125f ? 0.024339281f : 0.06345155f))
          : (data[1 /* C3 */] <0.5424219f
            ? (data[2 /* C4 */] <0.2196875f ? 0.3209137f : 0.12352164f)
            : (data[2 /* C4 */] <0.224375f ? 0.01150401f : 0.15966073f)))));
    return pred;
  }
}


class gbm2_Forest_14 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_14_class_0.score0(fdata);
  }
}
class gbm2_Tree_14_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.34262207f
      ? (data[1 /* C3 */] <0.22240503f
        ? (data[1 /* C3 */] <0.16747525f
          ? (data[1 /* C3 */] <0.1125557f
            ? -0.16208097f
            : (data[1 /* C3 */] <0.14246534f ? -0.120452516f : -0.14338027f))
          : (data[2 /* C4 */] <0.072578125f
            ? (data[1 /* C3 */] <0.20242187f ? -0.096846364f : -0.1254301f)
            : (data[2 /* C4 */] <0.08243286f ? -0.07071748f : -0.13154711f)))
        : (data[2 /* C4 */] <0.09773438f
          ? (data[0 /* C2 */] <0.2973047f
            ? -0.010836307f
            : (data[0 /* C2 */] <0.30747315f ? -0.12831035f : -0.06831288f))
          : (data[0 /* C2 */] <0.42210937f
            ? (data[1 /* C3 */] <0.3071875f ? -0.049925175f : 3.7354774E-5f)
            : (data[2 /* C4 */] <0.121875f ? -0.07592546f : 0.0032656607f))))
      : (data[2 /* C4 */] <0.15780273f
        ? (data[2 /* C4 */] <0.12768029f
          ? (data[0 /* C2 */] <0.5569922f
            ? (data[0 /* C2 */] <0.45818174f ? 0.012033346f : -0.031768396f)
            : (data[0 /* C2 */] <0.57225126f ? 0.12850636f : -0.0034973996f))
          : (data[0 /* C2 */] <0.50683594f
            ? (data[1 /* C3 */] <0.37765625f ? 0.015371578f : 0.061893772f)
            : (data[1 /* C3 */] <0.40171874f ? -0.040427014f : 0.0064523425f)))
        : (data[1 /* C3 */] <0.5326465f
          ? (data[0 /* C2 */] <0.6670508f
            ? (data[2 /* C4 */] <0.1903125f ? 0.038243793f : 0.095119506f)
            : (data[0 /* C2 */] <0.6724835f ? -0.07298621f : -0.007862353f))
          : (data[0 /* C2 */] <0.702207f
            ? (data[2 /* C4 */] <0.19882813f ? 0.10273619f : 0.17899872f)
            : (data[2 /* C4 */] <0.22101563f ? 0.010075666f : 0.15691732f)))));
    return pred;
  }
}


class gbm2_Forest_15 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_15_class_0.score0(fdata);
  }
}
class gbm2_Tree_15_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.37748536f
      ? (data[1 /* C3 */] <0.30221778f
        ? (data[0 /* C2 */] <0.28711915f
          ? (data[1 /* C3 */] <0.15261719f
            ? (data[1 /* C3 */] <0.14804138f ? -0.120612554f : -0.15308249f)
            : (data[0 /* C2 */] <0.2521875f ? -0.1065526f : -0.088698536f))
          : (data[2 /* C4 */] <0.1225f
            ? (data[2 /* C4 */] <0.08804688f ? -0.073437355f : -0.04767114f)
            : -0.13712797f))
        : (data[2 /* C4 */] <0.11917969f
          ? (data[0 /* C2 */] <0.3975f
            ? (data[0 /* C2 */] <0.38748047f ? 0.07292095f : 0.034506712f)
            : (data[1 /* C3 */] <0.35257813f ? -0.051363338f : -0.020602046f))
          : (data[0 /* C2 */] <0.46722656f
            ? (data[1 /* C3 */] <0.36242187f ? 0.029699555f : -0.081362695f)
            : (data[1 /* C3 */] <0.36242187f ? -0.06895478f : -0.017442148f))))
      : (data[2 /* C4 */] <0.17325196f
        ? (data[2 /* C4 */] <0.1525432f
          ? (data[0 /* C2 */] <0.49291015f
            ? (data[2 /* C4 */] <0.13207032f ? 0.0024918467f : 0.120471925f)
            : (data[1 /* C3 */] <0.4016797f ? -0.027777476f : 0.0055114147f))
          : (data[1 /* C3 */] <0.40722656f
            ? (data[0 /* C2 */] <0.5221875f ? 0.09602576f : 0.22482638f)
            : (data[1 /* C3 */] <0.5322235f ? 0.018095912f : 0.10006848f)))
        : (data[0 /* C2 */] <0.55296874f
          ? (data[1 /* C3 */] <0.42746094f
            ? (data[1 /* C3 */] <0.4126294f ? 0.17257059f : 0.02122867f)
            : 0.22684692f)
          : (data[2 /* C4 */] <0.19757813f
            ? (data[1 /* C3 */] <0.5830078f ? 0.034881502f : 0.33163798f)
            : (data[0 /* C2 */] <0.70125f ? 0.112300105f : 0.017852342f)))));
    return pred;
  }
}


class gbm2_Forest_16 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_16_class_0.score0(fdata);
  }
}
class gbm2_Tree_16_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.34262207f
      ? (data[1 /* C3 */] <0.24262846f
        ? (data[2 /* C4 */] <0.052734375f
          ? (data[0 /* C2 */] <0.20248047f
            ? (data[2 /* C4 */] <0.042578124f ? -0.116271764f : -0.14442001f)
            : (data[2 /* C4 */] <0.047265626f ? -0.08202848f : -0.10722145f))
          : (data[0 /* C2 */] <0.3216211f
            ? (data[0 /* C2 */] <0.3133293f ? -0.07649437f : -0.10874776f)
            : (data[2 /* C4 */] <0.07726563f ? -0.05224377f : -0.039041825f)))
        : (data[2 /* C4 */] <0.07734375f
          ? (data[1 /* C3 */] <0.2524219f ? -0.10931186f : -0.06222274f)
          : (data[0 /* C2 */] <0.32742187f
            ? 0.04065605f
            : (data[2 /* C4 */] <0.0971875f ? -0.05394044f : -0.033884086f))))
      : (data[2 /* C4 */] <0.15228516f
        ? (data[2 /* C4 */] <0.12761673f
          ? (data[1 /* C3 */] <0.42234376f
            ? (data[0 /* C2 */] <0.45382813f ? 0.009907089f : -0.025326757f)
            : (data[0 /* C2 */] <0.57007813f ? 0.060379975f : -0.0036988156f))
          : (data[0 /* C2 */] <0.49220702f
            ? (data[2 /* C4 */] <0.14734375f ? 0.034719203f : 0.21954754f)
            : (data[1 /* C3 */] <0.46703124f ? -0.0076749693f : 0.02386552f)))
        : (data[1 /* C3 */] <0.37240234f
          ? -0.08527866f
          : (data[1 /* C3 */] <0.41252387f
            ? (data[1 /* C3 */] <0.3925893f ? 0.0071800444f : 0.14273341f)
            : (data[2 /* C4 */] <0.183125f ? 0.023556845f : 0.056465164f)))));
    return pred;
  }
}


class gbm2_Forest_17 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_17_class_0.score0(fdata);
  }
}
class gbm2_Tree_17_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.37748536f
      ? (data[1 /* C3 */] <0.27765346f
        ? (data[0 /* C2 */] <0.262041f
          ? (data[0 /* C2 */] <0.15756106f
            ? -0.12525927f
            : (data[0 /* C2 */] <0.23278965f ? -0.09574362f : -0.08217485f))
          : (data[0 /* C2 */] <0.36255905f
            ? (data[1 /* C3 */] <0.2713672f ? -0.054534648f : 0.038371086f)
            : (data[0 /* C2 */] <0.3774797f ? -0.09820845f : -0.04531479f)))
        : (data[2 /* C4 */] <0.11917969f
          ? (data[0 /* C2 */] <0.3975f
            ? (data[2 /* C4 */] <0.09703125f ? -0.047048524f : 0.028037548f)
            : (data[1 /* C3 */] <0.3022656f ? -0.09536344f : -0.03548257f))
          : (data[0 /* C2 */] <0.47220704f
            ? (data[1 /* C3 */] <0.30746093f ? -0.0923988f : 0.0133397905f)
            : (data[1 /* C3 */] <0.3623828f ? -0.08492703f : -0.018794565f))))
      : (data[2 /* C4 */] <0.17325196f
        ? (data[0 /* C2 */] <0.46765625f
          ? 0.13713814f
          : (data[0 /* C2 */] <0.47790405f
            ? -0.110318996f
            : (data[0 /* C2 */] <0.48184305f ? 0.16340601f : 0.00888663f)))
        : (data[0 /* C2 */] <0.53240234f
          ? 0.16866079f
          : (data[2 /* C4 */] <0.22148438f
            ? (data[0 /* C2 */] <0.70125f ? 0.04663116f : -0.0037521743f)
            : (data[1 /* C3 */] <0.49679688f ? -0.0470039f : 0.17237334f)))));
    return pred;
  }
}


class gbm2_Forest_18 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_18_class_0.score0(fdata);
  }
}
class gbm2_Tree_18_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.112558596f
      ? (data[1 /* C3 */] <0.24268067f
        ? (data[1 /* C3 */] <0.1825642f
          ? (data[0 /* C2 */] <0.23822266f
            ? (data[0 /* C2 */] <0.23184678f ? -0.09011797f : -0.011781144f)
            : -0.11964578f)
          : (data[0 /* C2 */] <0.32757813f
            ? (data[2 /* C4 */] <0.08203125f ? -0.058526136f : -0.088291965f)
            : -0.026130538f))
        : (data[1 /* C3 */] <0.35224664f
          ? (data[0 /* C2 */] <0.35865235f
            ? (data[2 /* C4 */] <0.07734375f ? -0.068118624f : -0.009171936f)
            : (data[1 /* C3 */] <0.27289063f ? -0.08106772f : -0.03945127f))
          : (data[0 /* C2 */] <0.4725f
            ? (data[1 /* C3 */] <0.35875f ? -0.021935642f : 0.03985836f)
            : (data[1 /* C3 */] <0.36375f ? 0.037316207f : -0.05380325f))))
      : (data[2 /* C4 */] <0.15727037f
        ? (data[0 /* C2 */] <0.39294922f
          ? (data[2 /* C4 */] <0.12234375f ? -0.06578887f : -0.10799249f)
          : (data[1 /* C3 */] <0.46779296f
            ? (data[0 /* C2 */] <0.57273436f ? 0.0032149293f : -0.024783572f)
            : (data[0 /* C2 */] <0.6133594f ? 0.042024393f : 0.004791926f)))
        : (data[1 /* C3 */] <0.3921875f
          ? (data[0 /* C2 */] <0.48753905f ? 0.0332024f : -0.1518618f)
          : (data[1 /* C3 */] <0.4022583f
            ? 0.2481183f
            : (data[1 /* C3 */] <0.5319356f ? 0.024321008f : 0.056186922f)))));
    return pred;
  }
}


class gbm2_Forest_19 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_19_class_0.score0(fdata);
  }
}
class gbm2_Tree_19_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.37748536f
      ? (data[1 /* C3 */] <0.2524593f
        ? (data[1 /* C3 */] <0.18265435f
          ? (data[0 /* C2 */] <0.23742187f
            ? (data[0 /* C2 */] <0.2336151f ? -0.08110617f : -0.010603023f)
            : -0.10768122f)
          : (data[0 /* C2 */] <0.3366797f
            ? (data[1 /* C3 */] <0.24289063f ? -0.055061687f : -0.010657694f)
            : -0.10349893f))
        : (data[1 /* C3 */] <0.3424501f
          ? (data[0 /* C2 */] <0.43236327f
            ? (data[2 /* C4 */] <0.10265625f ? -0.035819937f : -0.00604823f)
            : (data[1 /* C3 */] <0.3220703f ? 0.014752418f : -0.057455346f))
          : (data[0 /* C2 */] <0.45726562f
            ? (data[1 /* C3 */] <0.3675f ? 0.037973437f : -0.123482026f)
            : (data[2 /* C4 */] <0.145625f ? -0.020649256f : -0.093406536f))))
      : (data[2 /* C4 */] <0.15228516f
        ? (data[0 /* C2 */] <0.49203125f
          ? (data[0 /* C2 */] <0.47763f
            ? (data[0 /* C2 */] <0.4673507f ? 0.07339814f : -0.10306972f)
            : (data[2 /* C4 */] <0.14289063f ? 0.04525607f : 0.24927641f))
          : (data[1 /* C3 */] <0.40240234f
            ? (data[0 /* C2 */] <0.523125f ? -0.0121309925f : -0.06386585f)
            : (data[1 /* C3 */] <0.42653793f ? 0.026648996f : -0.006978752f)))
        : (data[0 /* C2 */] <0.57277346f
          ? (data[1 /* C3 */] <0.4622656f
            ? (data[2 /* C4 */] <0.186875f ? 0.052877847f : -0.06240689f)
            : (data[2 /* C4 */] <0.168125f ? 0.0432658f : 0.29435384f))
          : (data[2 /* C4 */] <0.19859375f
            ? (data[1 /* C3 */] <0.5835937f ? 0.012320229f : 0.24308617f)
            : (data[0 /* C2 */] <0.7025f ? 0.09042924f : 0.0020161578f)))));
    return pred;
  }
}


class gbm2_Forest_20 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_20_class_0.score0(fdata);
  }
}
class gbm2_Tree_20_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.112558596f
      ? (data[1 /* C3 */] <0.22234374f
        ? (data[2 /* C4 */] <0.052421875f
          ? (data[0 /* C2 */] <0.19789062f
            ? (data[2 /* C4 */] <0.0421875f ? -0.07834163f : -0.10394311f)
            : (data[2 /* C4 */] <0.0471875f ? -0.05133826f : -0.07331154f))
          : (data[2 /* C4 */] <0.08252991f
            ? (data[2 /* C4 */] <0.07242127f ? -0.059314188f : -0.033228442f)
            : -0.08560259f))
        : (data[1 /* C3 */] <0.35781157f
          ? (data[0 /* C2 */] <0.29748046f
            ? 0.022534749f
            : (data[0 /* C2 */] <0.3076767f ? -0.08336802f : -0.03257861f))
          : (data[0 /* C2 */] <0.46666014f
            ? (data[1 /* C3 */] <0.36847657f ? 0.117577195f : -0.049736414f)
            : (data[2 /* C4 */] <0.102578126f ? -0.073025115f : -0.013425497f))))
      : (data[1 /* C3 */] <0.51229006f
        ? (data[0 /* C2 */] <0.6464258f
          ? (data[2 /* C4 */] <0.18636718f
            ? (data[2 /* C4 */] <0.15235627f ? -0.00136894f : 0.017751291f)
            : (data[1 /* C3 */] <0.453125f ? -0.10343112f : 0.09952547f))
          : (data[1 /* C3 */] <0.49273437f
            ? -0.14351259f
            : (data[2 /* C4 */] <0.186875f ? -0.016121745f : -0.13019069f)))
        : (data[0 /* C2 */] <0.70302737f
          ? (data[2 /* C4 */] <0.19660157f
            ? (data[2 /* C4 */] <0.19268586f ? 0.053079553f : -0.0490061f)
            : (data[0 /* C2 */] <0.6473047f ? 0.27597237f : 0.08396856f))
          : (data[1 /* C3 */] <0.5524414f
            ? (data[0 /* C2 */] <0.71703124f ? -0.04110436f : -0.11143068f)
            : (data[2 /* C4 */] <0.22015625f ? 0.0059428667f : 0.11073611f)))));
    return pred;
  }
}


class gbm2_Forest_21 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_21_class_0.score0(fdata);
  }
}
class gbm2_Tree_21_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.37748536f
      ? (data[1 /* C3 */] <0.30221778f
        ? (data[0 /* C2 */] <0.28711915f
          ? (data[1 /* C3 */] <0.121992186f
            ? (data[0 /* C2 */] <0.15703125f ? -0.08982207f : -0.0718036f)
            : (data[1 /* C3 */] <0.20246704f ? -0.051328722f : -0.06619989f))
          : (data[2 /* C4 */] <0.1225f
            ? (data[0 /* C2 */] <0.3976172f ? -0.02912977f : -0.06866617f)
            : -0.100045726f))
        : (data[0 /* C2 */] <0.39788085f
          ? (data[1 /* C3 */] <0.30773437f ? 0.060740013f : 0.04026466f)
          : (data[2 /* C4 */] <0.12359375f
            ? (data[1 /* C3 */] <0.34765625f ? -0.03165499f : -0.0122596035f)
            : (data[0 /* C2 */] <0.46726564f ? 0.03175093f : -0.030890755f))))
      : (data[1 /* C3 */] <0.5124121f
        ? (data[0 /* C2 */] <0.6474219f
          ? (data[2 /* C4 */] <0.18757813f
            ? (data[0 /* C2 */] <0.6123437f ? 0.012791857f : -0.014115229f)
            : (data[1 /* C3 */] <0.46734375f ? -0.035557933f : 0.09980057f))
          : (data[1 /* C3 */] <0.4978125f
            ? (data[2 /* C4 */] <0.166875f ? -0.14842251f : -0.06738952f)
            : (data[2 /* C4 */] <0.181875f ? -0.0065018386f : -0.09643333f)))
        : (data[0 /* C2 */] <0.7022656f
          ? (data[2 /* C4 */] <0.19724609f
            ? (data[2 /* C4 */] <0.19266616f ? 0.04758773f : -0.044105455f)
            : (data[0 /* C2 */] <0.6473047f ? 0.24837512f : 0.075571746f))
          : (data[1 /* C3 */] <0.5524414f
            ? (data[2 /* C4 */] <0.18546875f ? -0.028143944f : -0.09198665f)
            : (data[2 /* C4 */] <0.22015625f ? 0.005348537f : 0.09966252f)))));
    return pred;
  }
}


class gbm2_Forest_22 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_22_class_0.score0(fdata);
  }
}
class gbm2_Tree_22_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.1373877f
      ? (data[1 /* C3 */] <0.41234863f
        ? (data[2 /* C4 */] <0.08753906f
          ? (data[0 /* C2 */] <0.39273438f
            ? (data[2 /* C4 */] <0.05246094f ? -0.06312365f : -0.041933868f)
            : 0.033304147f)
          : (data[0 /* C2 */] <0.5382031f
            ? (data[0 /* C2 */] <0.32533568f ? -0.06490002f : -0.015142415f)
            : (data[2 /* C4 */] <0.12726563f ? -0.0014457544f : -0.15901677f)))
        : (data[1 /* C3 */] <0.41753033f
          ? (data[0 /* C2 */] <0.5373047f ? 0.05600564f : 0.1087701f)
          : (data[0 /* C2 */] <0.5679297f
            ? (data[0 /* C2 */] <0.5520489f ? 0.0074548456f : 0.063403256f)
            : (data[2 /* C4 */] <0.1321875f ? 0.0043879114f : -0.03875713f))))
      : (data[0 /* C2 */] <0.45222655f
        ? 0.17152406f
        : (data[1 /* C3 */] <0.51230466f
          ? (data[0 /* C2 */] <0.64765626f
            ? (data[1 /* C3 */] <0.37847656f ? -0.046561617f : 0.014254834f)
            : (data[1 /* C3 */] <0.49265626f ? -0.11805907f : -0.03412157f))
          : (data[0 /* C2 */] <0.7025f
            ? (data[2 /* C4 */] <0.19703124f ? 0.034459542f : 0.08838066f)
            : (data[1 /* C3 */] <0.5730078f ? -0.026543118f : 0.038232077f)))));
    return pred;
  }
}


class gbm2_Forest_23 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_23_class_0.score0(fdata);
  }
}
class gbm2_Tree_23_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.1373877f
      ? (data[1 /* C3 */] <0.41234863f
        ? (data[2 /* C4 */] <0.08753906f
          ? (data[0 /* C2 */] <0.39273438f
            ? (data[0 /* C2 */] <0.35301757f ? -0.037351158f : -0.05883082f)
            : 0.029973729f)
          : (data[0 /* C2 */] <0.5382031f
            ? (data[0 /* C2 */] <0.32533568f ? -0.058410026f : -0.013628171f)
            : (data[2 /* C4 */] <0.12726563f ? -0.0013011773f : -0.14311512f)))
        : (data[1 /* C3 */] <0.41753033f
          ? (data[0 /* C2 */] <0.5373047f ? 0.050405093f : 0.09789307f)
          : (data[1 /* C3 */] <0.4872403f
            ? (data[1 /* C3 */] <0.46727833f ? 0.0059187943f : 0.08652053f)
            : -0.0673045f)))
      : (data[0 /* C2 */] <0.45222655f
        ? 0.15437165f
        : (data[1 /* C3 */] <0.51230466f
          ? (data[0 /* C2 */] <0.64765626f
            ? (data[2 /* C4 */] <0.18640625f ? 0.0074861115f : 0.051596306f)
            : (data[1 /* C3 */] <0.4969922f ? -0.08874332f : -0.027115794f))
          : (data[0 /* C2 */] <0.7025f
            ? (data[1 /* C3 */] <0.53292966f ? 0.023836946f : 0.06820239f)
            : (data[1 /* C3 */] <0.55191404f ? -0.0537339f : 0.014774338f)))));
    return pred;
  }
}


class gbm2_Forest_24 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_24_class_0.score0(fdata);
  }
}
class gbm2_Tree_24_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.34262207f
      ? (data[2 /* C4 */] <0.07724609f
        ? (data[2 /* C4 */] <0.052503202f
          ? (data[0 /* C2 */] <0.20257813f
            ? (data[2 /* C4 */] <0.042578124f ? -0.052596558f : -0.077180624f)
            : (data[2 /* C4 */] <0.047265626f ? -0.028761188f : -0.05058658f))
          : (data[0 /* C2 */] <0.32322267f
            ? (data[1 /* C3 */] <0.2328125f ? -0.03576955f : 0.023104383f)
            : (data[2 /* C4 */] <0.07234375f ? -0.0176459f : -0.06653695f)))
        : (data[2 /* C4 */] <0.13243619f
          ? (data[2 /* C4 */] <0.122399576f
            ? (data[0 /* C2 */] <0.41375f ? -0.013860456f : -0.034564987f)
            : (data[1 /* C3 */] <0.31210938f ? -0.035134707f : 0.058550816f))
          : (data[1 /* C3 */] <0.326875f ? -0.10781887f : -0.040622838f)))
      : (data[2 /* C4 */] <0.15780273f
        ? (data[1 /* C3 */] <0.48260742f
          ? (data[1 /* C3 */] <0.42777947f
            ? (data[2 /* C4 */] <0.13742188f ? -0.006424277f : 0.029442482f)
            : (data[1 /* C3 */] <0.43226716f ? -0.07995624f : -0.0058238697f))
          : (data[0 /* C2 */] <0.61759764f
            ? (data[0 /* C2 */] <0.6023936f ? -0.0103188865f : 0.14695172f)
            : (data[1 /* C3 */] <0.521875f ? 0.010996751f : -0.059843265f)))
        : (data[0 /* C2 */] <0.5725977f
          ? (data[1 /* C3 */] <0.39146483f
            ? (data[0 /* C2 */] <0.48773438f ? 0.04695916f : -0.15665726f)
            : (data[1 /* C3 */] <0.40210876f ? 0.21279028f : 0.049863014f))
          : (data[1 /* C3 */] <0.5320508f
            ? (data[0 /* C2 */] <0.666875f ? 0.011115372f : -0.046497032f)
            : (data[0 /* C2 */] <0.681875f ? 0.09937788f : 0.010750959f)))));
    return pred;
  }
}


class gbm2_Forest_25 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_25_class_0.score0(fdata);
  }
}
class gbm2_Tree_25_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.112558596f
      ? (data[2 /* C4 */] <0.07749396f
        ? (data[2 /* C4 */] <0.05252032f
          ? (data[0 /* C2 */] <0.1821875f
            ? (data[2 /* C4 */] <0.032421876f ? -0.07719413f : -0.043893334f)
            : (data[2 /* C4 */] <0.042578124f ? -0.033041704f : -0.045831844f))
          : (data[0 /* C2 */] <0.3221875f
            ? (data[1 /* C3 */] <0.2328125f ? -0.032192603f : 0.020793963f)
            : (data[2 /* C4 */] <0.07234375f ? -0.015881315f : -0.05988326f)))
        : (data[1 /* C3 */] <0.3928125f
          ? (data[1 /* C3 */] <0.3579077f
            ? (data[0 /* C2 */] <0.39742187f ? -0.012920946f : -0.028896235f)
            : (data[0 /* C2 */] <0.4584375f ? 0.11927764f : -0.0032275454f))
          : (data[0 /* C2 */] <0.5280078f ? -0.12913841f : -0.011708212f)))
      : (data[2 /* C4 */] <0.16720633f
        ? (data[1 /* C3 */] <0.521875f
          ? (data[0 /* C2 */] <0.6363281f
            ? (data[1 /* C3 */] <0.49890625f ? 2.5136996E-4f : 0.08115561f)
            : (data[2 /* C4 */] <0.15757813f ? -0.0055375597f : -0.05609113f))
          : (data[1 /* C3 */] <0.53740966f
            ? (data[0 /* C2 */] <0.6626172f ? 0.02437354f : 0.1557124f)
            : 0.015981713f))
        : (data[0 /* C2 */] <0.51353514f
          ? -0.14495397f
          : (data[0 /* C2 */] <0.59714454f
            ? (data[1 /* C3 */] <0.46296874f ? 0.037566286f : 0.12143426f)
            : (data[1 /* C3 */] <0.48078126f ? -0.027083598f : 0.019108793f)))));
    return pred;
  }
}


class gbm2_Forest_26 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_26_class_0.score0(fdata);
  }
}
class gbm2_Tree_26_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.37748536f
      ? (data[1 /* C3 */] <0.30221778f
        ? (data[2 /* C4 */] <0.12359375f
          ? (data[0 /* C2 */] <0.28734374f
            ? (data[0 /* C2 */] <0.15794678f ? -0.057478115f : -0.03414989f)
            : (data[0 /* C2 */] <0.39693236f ? -0.016686138f : -0.055281717f))
          : -0.08682043f)
        : (data[0 /* C2 */] <0.39788085f
          ? (data[1 /* C3 */] <0.30773437f ? 0.06017047f : 0.04208412f)
          : (data[0 /* C2 */] <0.47245398f
            ? (data[2 /* C4 */] <0.12359375f ? -0.013574444f : 0.019491166f)
            : (data[0 /* C2 */] <0.48749807f ? -0.03967867f : -0.0020161336f))))
      : (data[2 /* C4 */] <0.16773437f
        ? (data[1 /* C3 */] <0.42746094f
          ? (data[2 /* C4 */] <0.14742188f
            ? (data[0 /* C2 */] <0.5515625f ? 0.006815568f : -0.051183343f)
            : (data[0 /* C2 */] <0.5015625f ? 0.13912396f : 0.037197217f))
          : (data[1 /* C3 */] <0.43299943f
            ? (data[2 /* C4 */] <0.13804688f ? -0.020120973f : -0.09131825f)
            : (data[0 /* C2 */] <0.52804685f ? -0.11449429f : 7.345495E-4f)))
        : (data[0 /* C2 */] <0.6222851f
          ? (data[2 /* C4 */] <0.19291015f
            ? (data[2 /* C4 */] <0.1873616f ? 0.036400005f : -0.04174305f)
            : (data[1 /* C3 */] <0.4819531f ? 0.03187653f : 0.19575948f))
          : (data[0 /* C2 */] <0.62755466f
            ? (data[2 /* C4 */] <0.17539063f ? -0.1366269f : -0.00498086f)
            : (data[1 /* C3 */] <0.48671874f ? 0.08223605f : 0.011285502f)))));
    return pred;
  }
}


class gbm2_Forest_27 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_27_class_0.score0(fdata);
  }
}
class gbm2_Tree_27_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.34262207f
      ? (data[2 /* C4 */] <0.13242188f
        ? (data[2 /* C4 */] <0.08741913f
          ? (data[0 /* C2 */] <0.39328125f
            ? (data[0 /* C2 */] <0.3534961f ? -0.024634128f : -0.047447383f)
            : 0.03298228f)
          : (data[0 /* C2 */] <0.43265626f
            ? (data[2 /* C4 */] <0.1171875f ? -0.009788398f : 0.033976592f)
            : (data[1 /* C3 */] <0.32195312f ? 0.018866364f : -0.040448055f)))
        : (data[0 /* C2 */] <0.4471289f ? -0.089050665f : -0.027354078f))
      : (data[1 /* C3 */] <0.51252043f
        ? (data[0 /* C2 */] <0.6464258f
          ? (data[2 /* C4 */] <0.18921874f
            ? (data[0 /* C2 */] <0.6090625f ? 0.0061538992f : -0.013723221f)
            : (data[1 /* C3 */] <0.45199218f ? -0.09964447f : 0.06676888f))
          : (data[1 /* C3 */] <0.49259767f
            ? -0.09929601f
            : (data[2 /* C4 */] <0.181875f ? -8.621827E-4f : -0.09161785f)))
        : (data[2 /* C4 */] <0.2240625f
          ? (data[0 /* C2 */] <0.7017969f
            ? (data[1 /* C3 */] <0.57789063f ? 0.024488728f : 0.1993797f)
            : (data[0 /* C2 */] <0.75703615f ? -0.023893435f : 0.090177044f))
          : (data[1 /* C3 */] <0.57248044f ? 0.14761698f : 0.06613559f))));
    return pred;
  }
}


class gbm2_Forest_28 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_28_class_0.score0(fdata);
  }
}
class gbm2_Tree_28_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.13242188f
      ? (data[1 /* C3 */] <0.4524414f
        ? (data[0 /* C2 */] <0.28862303f
          ? (data[1 /* C3 */] <0.20158203f
            ? (data[1 /* C3 */] <0.19242065f ? -0.032659717f : -0.005357801f)
            : (data[0 /* C2 */] <0.27679688f ? -0.079465844f : -0.024046458f))
          : (data[1 /* C3 */] <0.41296875f
            ? (data[0 /* C2 */] <0.52f ? -0.011198602f : -0.023558334f)
            : (data[0 /* C2 */] <0.545f ? 0.054769825f : -0.029778093f)))
        : (data[0 /* C2 */] <0.5913574f ? 0.11858272f : -0.035340335f))
      : (data[0 /* C2 */] <0.45222655f
        ? (data[1 /* C3 */] <0.34245118f ? -0.05065872f : 0.27359295f)
        : (data[1 /* C3 */] <0.3725293f
          ? (data[0 /* C2 */] <0.47328126f
            ? (data[0 /* C2 */] <0.4575708f ? -0.11949136f : 0.01521701f)
            : (data[2 /* C4 */] <0.15054688f ? -0.11036665f : -0.050445575f))
          : (data[0 /* C2 */] <0.5520313f
            ? (data[1 /* C3 */] <0.4308594f ? 0.014347945f : 0.0677144f)
            : (data[1 /* C3 */] <0.48242188f ? -0.009290321f : 0.015268159f)))));
    return pred;
  }
}


class gbm2_Forest_29 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_29_class_0.score0(fdata);
  }
}
class gbm2_Tree_29_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.14235352f
      ? (data[1 /* C3 */] <0.3025293f
        ? (data[2 /* C4 */] <0.1225f
          ? (data[0 /* C2 */] <0.39703125f
            ? (data[2 /* C4 */] <0.0975f ? -0.019649135f : 0.006330917f)
            : (data[2 /* C4 */] <0.1021875f ? -0.027728956f : -0.07684308f))
          : -0.07303035f)
        : (data[0 /* C2 */] <0.40825194f
          ? (data[2 /* C4 */] <0.092421874f
            ? -0.030622032f
            : (data[2 /* C4 */] <0.11238525f ? 0.06944548f : -0.023099735f))
          : (data[2 /* C4 */] <0.11265625f
            ? (data[1 /* C3 */] <0.39125f ? -0.014460909f : -0.05889706f)
            : (data[0 /* C2 */] <0.43265626f ? 0.048633505f : -0.004346404f))))
      : (data[0 /* C2 */] <0.5526758f
        ? (data[1 /* C3 */] <0.43235353f
          ? (data[1 /* C3 */] <0.3776313f
            ? (data[1 /* C3 */] <0.3526643f ? 0.018988289f : -0.06501931f)
            : (data[0 /* C2 */] <0.54179686f ? 0.04107316f : -0.03419725f))
          : (data[0 /* C2 */] <0.5376953f
            ? (data[1 /* C3 */] <0.4375f ? 0.030360162f : -0.04650218f)
            : (data[1 /* C3 */] <0.4421875f ? 0.23314092f : 0.07374989f)))
        : (data[0 /* C2 */] <0.56292284f
          ? (data[1 /* C3 */] <0.43291014f
            ? -0.09880565f
            : (data[1 /* C3 */] <0.4527156f ? -0.012409247f : -0.0756512f))
          : (data[1 /* C3 */] <0.42177734f
            ? 0.13830923f
            : (data[0 /* C2 */] <0.56890625f ? 0.08078198f : 0.0033737265f)))));
    return pred;
  }
}


class gbm2_Forest_30 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_30_class_0.score0(fdata);
  }
}
class gbm2_Tree_30_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.15228516f
      ? (data[1 /* C3 */] <0.34262207f
        ? (data[0 /* C2 */] <0.44663087f
          ? (data[2 /* C4 */] <0.09785156f
            ? (data[0 /* C2 */] <0.421875f ? -0.019013885f : 0.020425498f)
            : (data[0 /* C2 */] <0.4103125f ? 0.008280651f : -0.016597897f))
          : (data[0 /* C2 */] <0.4575895f
            ? (data[2 /* C4 */] <0.10734375f ? -0.031587124f : -0.09262005f)
            : 0.022952959f))
        : (data[0 /* C2 */] <0.6532324f
          ? (data[0 /* C2 */] <0.6422582f
            ? (data[1 /* C3 */] <0.48308593f ? -0.0027774046f : 0.0370978f)
            : -0.1016398f)
          : 0.070055366f))
      : (data[0 /* C2 */] <0.49775392f
        ? (data[0 /* C2 */] <0.47255173f ? -6.883795E-6f : -0.11265828f)
        : (data[0 /* C2 */] <0.5020913f
          ? 0.22128025f
          : (data[0 /* C2 */] <0.513092f
            ? -0.177458f
            : (data[1 /* C3 */] <0.41265625f ? 0.099329874f : 0.009400073f)))));
    return pred;
  }
}


class gbm2_Forest_31 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_31_class_0.score0(fdata);
  }
}
class gbm2_Tree_31_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.15228516f
      ? (data[1 /* C3 */] <0.46754882f
        ? (data[0 /* C2 */] <0.56756836f
          ? (data[2 /* C4 */] <0.13242188f
            ? (data[1 /* C3 */] <0.41375f ? -0.01094686f : 0.01981816f)
            : (data[0 /* C2 */] <0.49609375f ? 0.037674088f : -0.0011335512f))
          : (data[2 /* C4 */] <0.13242188f
            ? (data[0 /* C2 */] <0.58734375f ? -0.010018972f : 0.0656449f)
            : (data[0 /* C2 */] <0.5971875f ? -0.032925412f : -0.06329002f)))
        : (data[0 /* C2 */] <0.6129199f
          ? (data[0 /* C2 */] <0.6075128f
            ? (data[2 /* C4 */] <0.1471875f ? 0.044353224f : -0.013157403f)
            : 0.12700911f)
          : (data[0 /* C2 */] <0.6526567f
            ? (data[0 /* C2 */] <0.6423599f ? -0.0024701483f : -0.09147583f)
            : 0.06304987f)))
      : (data[0 /* C2 */] <0.60759765f
        ? (data[2 /* C4 */] <0.20260742f
          ? (data[2 /* C4 */] <0.19256523f
            ? (data[2 /* C4 */] <0.1875761f ? 0.021620432f : -0.07390023f)
            : (data[1 /* C3 */] <0.45921874f ? 0.0903146f : 0.27728564f))
          : -0.15840594f)
        : (data[1 /* C3 */] <0.49704102f
          ? (data[2 /* C4 */] <0.18734375f
            ? (data[0 /* C2 */] <0.6325f ? -0.02379373f : -0.07741539f)
            : (data[1 /* C3 */] <0.49195313f ? 0.08483449f : -0.07794453f))
          : (data[0 /* C2 */] <0.64203125f
            ? (data[2 /* C4 */] <0.2f ? 0.023625432f : 0.25860348f)
            : (data[1 /* C3 */] <0.53164065f ? -0.016367711f : 0.021261116f)))));
    return pred;
  }
}


class gbm2_Forest_32 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_32_class_0.score0(fdata);
  }
}
class gbm2_Tree_32_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.38242432f
      ? (data[0 /* C2 */] <0.5172656f
        ? (data[2 /* C4 */] <0.12359375f
          ? (data[0 /* C2 */] <0.49265626f
            ? (data[0 /* C2 */] <0.2642505f ? -0.026295498f : -0.008272027f)
            : (data[0 /* C2 */] <0.49754396f ? -0.09362367f : -0.04480587f))
          : (data[1 /* C3 */] <0.3076367f
            ? -0.06928752f
            : (data[0 /* C2 */] <0.4314453f ? 0.11926849f : 0.0038215506f)))
        : -0.07601962f)
      : (data[0 /* C2 */] <0.5028125f
        ? (data[1 /* C3 */] <0.40777344f
          ? (data[2 /* C4 */] <0.1471875f
            ? (data[0 /* C2 */] <0.48273438f ? 0.0814942f : 0.0157347f)
            : (data[2 /* C4 */] <0.15261474f ? 0.22173187f : 0.025511598f))
          : -0.07285359f)
        : (data[1 /* C3 */] <0.3922461f
          ? (data[2 /* C4 */] <0.1478125f
            ? (data[2 /* C4 */] <0.13249756f ? -0.046739135f : 0.08654582f)
            : -0.23500699f)
          : (data[2 /* C4 */] <0.17125f
            ? (data[1 /* C3 */] <0.426875f ? 0.0126991505f : -0.0039318455f)
            : (data[0 /* C2 */] <0.5389063f ? 0.2025715f : 0.01093075f)))));
    return pred;
  }
}


class gbm2_Forest_33 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_33_class_0.score0(fdata);
  }
}
class gbm2_Tree_33_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.48265624f
      ? (data[0 /* C2 */] <0.6372266f
        ? (data[2 /* C4 */] <0.20304687f
          ? (data[2 /* C4 */] <0.16814819f
            ? (data[0 /* C2 */] <0.57375f ? -0.0024088016f : -0.015842343f)
            : (data[1 /* C3 */] <0.39367187f ? -0.08339935f : 0.02513717f))
          : -0.09057475f)
        : -0.1433845f)
      : (data[0 /* C2 */] <0.6227734f
        ? (data[2 /* C4 */] <0.19273438f
          ? (data[2 /* C4 */] <0.17739196f
            ? (data[0 /* C2 */] <0.61742187f ? 0.070158795f : 0.018444637f)
            : (data[1 /* C3 */] <0.49746093f ? 0.00423165f : -0.10406132f))
          : 0.1576091f)
        : (data[0 /* C2 */] <0.62727875f
          ? (data[2 /* C4 */] <0.17710938f
            ? (data[2 /* C4 */] <0.1624292f ? -0.009617928f : -0.13480797f)
            : 0.03603672f)
          : (data[1 /* C3 */] <0.48757812f
            ? (data[2 /* C4 */] <0.17125f ? -0.013870761f : 0.19746293f)
            : (data[1 /* C3 */] <0.49646056f ? -0.036694776f : 0.008565459f)))));
    return pred;
  }
}


class gbm2_Forest_34 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_34_class_0.score0(fdata);
  }
}
class gbm2_Tree_34_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.34262207f
      ? (data[2 /* C4 */] <0.1269043f
        ? (data[2 /* C4 */] <0.12269068f
          ? (data[0 /* C2 */] <0.41296875f
            ? (data[2 /* C4 */] <0.1021875f ? -0.01201082f : 0.026397374f)
            : (data[0 /* C2 */] <0.45206177f ? -0.0235096f : 0.03162836f))
          : 0.046318516f)
        : (data[0 /* C2 */] <0.4471289f
          ? (data[1 /* C3 */] <0.31480467f ? -0.06999629f : -0.047769748f)
          : -0.021601269f))
      : (data[0 /* C2 */] <0.45222655f
        ? (data[2 /* C4 */] <0.13695313f
          ? (data[2 /* C4 */] <0.12759918f
            ? (data[1 /* C3 */] <0.36257812f ? 0.029042853f : -0.06025525f)
            : -0.09595438f)
          : 0.30559856f)
        : (data[1 /* C3 */] <0.48260742f
          ? (data[0 /* C2 */] <0.63640624f
            ? (data[0 /* C2 */] <0.59814084f ? 0.0019828274f : -0.016184866f)
            : -0.12904601f)
          : (data[0 /* C2 */] <0.6223438f
            ? (data[2 /* C4 */] <0.1946875f ? 0.03418655f : 0.1418482f)
            : (data[0 /* C2 */] <0.6268592f ? -0.040635493f : 0.006334347f)))));
    return pred;
  }
}


class gbm2_Forest_35 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_35_class_0.score0(fdata);
  }
}
class gbm2_Tree_35_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.38242432f
      ? (data[0 /* C2 */] <0.5172656f
        ? (data[2 /* C4 */] <0.16332032f
          ? (data[2 /* C4 */] <0.12249024f
            ? (data[0 /* C2 */] <0.494375f ? -0.008199041f : -0.05649135f)
            : (data[1 /* C3 */] <0.30890626f ? -0.05977085f : 0.0062784203f))
          : 0.06806677f)
        : -0.067671366f)
      : (data[0 /* C2 */] <0.5028125f
        ? (data[1 /* C3 */] <0.40777344f
          ? (data[2 /* C4 */] <0.1471875f
            ? (data[2 /* C4 */] <0.11755127f ? 0.08446087f : 0.016132964f)
            : (data[2 /* C4 */] <0.15261474f ? 0.1996013f : 0.023003055f))
          : -0.065525554f)
        : (data[1 /* C3 */] <0.3922461f
          ? (data[2 /* C4 */] <0.1478125f
            ? (data[2 /* C4 */] <0.13249756f ? -0.04202255f : 0.077933855f)
            : -0.2090339f)
          : (data[0 /* C2 */] <0.52316403f
            ? (data[0 /* C2 */] <0.512521f ? -0.027347561f : 0.053352445f)
            : (data[1 /* C3 */] <0.40296876f ? -0.057865933f : 0.003896477f)))));
    return pred;
  }
}


class gbm2_Forest_36 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_36_class_0.score0(fdata);
  }
}
class gbm2_Tree_36_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.15228516f
      ? (data[1 /* C3 */] <0.46754882f
        ? (data[0 /* C2 */] <0.56756836f
          ? (data[2 /* C4 */] <0.14707032f
            ? (data[1 /* C3 */] <0.4009375f ? -0.0066982266f : 0.006705444f)
            : (data[0 /* C2 */] <0.49609375f ? 0.13474277f : 0.0029921604f))
          : (data[2 /* C4 */] <0.13242188f
            ? (data[0 /* C2 */] <0.58734375f ? -0.008208895f : 0.061196577f)
            : (data[2 /* C4 */] <0.14739075f ? -0.024288323f : -0.046554044f)))
        : (data[0 /* C2 */] <0.6129199f
          ? (data[0 /* C2 */] <0.6075128f
            ? (data[2 /* C4 */] <0.1471875f ? 0.039198402f : -0.01230019f)
            : 0.114367366f)
          : (data[0 /* C2 */] <0.6526567f
            ? (data[0 /* C2 */] <0.6423599f ? 2.6925709E-4f : -0.08017928f)
            : 0.055258345f)))
      : (data[0 /* C2 */] <0.49775392f
        ? (data[0 /* C2 */] <0.47255173f ? -0.009804925f : -0.10382259f)
        : (data[0 /* C2 */] <0.5020913f
          ? 0.19745585f
          : (data[0 /* C2 */] <0.513092f
            ? -0.1492628f
            : (data[1 /* C3 */] <0.41265625f ? 0.08873195f : 0.0056111147f)))));
    return pred;
  }
}


class gbm2_Forest_37 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_37_class_0.score0(fdata);
  }
}
class gbm2_Tree_37_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.5125806f
      ? (data[0 /* C2 */] <0.64734375f
        ? (data[2 /* C4 */] <0.16332032f
          ? (data[1 /* C3 */] <0.25228515f
            ? (data[0 /* C2 */] <0.33328125f ? -0.010554136f : -0.05135646f)
            : (data[0 /* C2 */] <0.63609374f ? -0.0013737305f : -0.038787168f))
          : (data[0 /* C2 */] <0.53367186f
            ? (data[1 /* C3 */] <0.37851563f ? -0.036797658f : 0.08244925f)
            : (data[1 /* C3 */] <0.43164062f ? -0.05278855f : 0.009263299f)))
        : (data[2 /* C4 */] <0.18097657f
          ? (data[1 /* C3 */] <0.49259767f
            ? -0.12311168f
            : (data[1 /* C3 */] <0.5025224f ? 0.02601783f : -0.022643732f))
          : (data[2 /* C4 */] <0.19240922f ? -0.08862022f : -0.042849623f)))
      : (data[0 /* C2 */] <0.6827539f
        ? (data[1 /* C3 */] <0.5424219f
          ? (data[0 /* C2 */] <0.6674023f
            ? (data[2 /* C4 */] <0.20625f ? 0.026021792f : 0.14819703f)
            : (data[2 /* C4 */] <0.19125f ? -0.021428587f : -0.13884227f))
          : (data[0 /* C2 */] <0.6574414f
            ? -0.057808943f
            : (data[1 /* C3 */] <0.5576562f ? 0.2334008f : 0.08163417f)))
        : (data[1 /* C3 */] <0.5825f
          ? (data[1 /* C3 */] <0.5424219f
            ? (data[1 /* C3 */] <0.5374945f ? -0.020299962f : 0.10858505f)
            : (data[2 /* C4 */] <0.19617188f ? -0.05582702f : 0.004461814f))
          : (data[2 /* C4 */] <0.2021875f
            ? 0.225356f
            : (data[1 /* C3 */] <0.5971875f ? 0.095528044f : -0.09939492f)))));
    return pred;
  }
}


class gbm2_Forest_38 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_38_class_0.score0(fdata);
  }
}
class gbm2_Tree_38_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.48265624f
      ? (data[0 /* C2 */] <0.6372266f
        ? (data[2 /* C4 */] <0.20304687f
          ? (data[2 /* C4 */] <0.16814819f
            ? (data[1 /* C3 */] <0.426875f ? -2.5577415E-4f : -0.011787286f)
            : (data[0 /* C2 */] <0.6f ? 0.029962268f : -0.017022623f))
          : -0.08193588f)
        : -0.111076176f)
      : (data[0 /* C2 */] <0.61265624f
        ? (data[2 /* C4 */] <0.18785156f
          ? (data[2 /* C4 */] <0.1775148f
            ? (data[1 /* C3 */] <0.49742186f ? 0.0728852f : 0.009792987f)
            : -0.11209417f)
          : 0.2107624f)
        : (data[1 /* C3 */] <0.5123926f
          ? (data[1 /* C3 */] <0.48756805f
            ? (data[2 /* C4 */] <0.16785157f ? -0.006729342f : 0.07000515f)
            : (data[2 /* C4 */] <0.20816407f ? -0.017488642f : 0.09044217f))
          : (data[0 /* C2 */] <0.6821875f
            ? (data[1 /* C3 */] <0.5424219f ? 0.012398508f : 0.08878139f)
            : (data[1 /* C3 */] <0.5825f ? -0.015971785f : 0.057538047f)))));
    return pred;
  }
}


class gbm2_Forest_39 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_39_class_0.score0(fdata);
  }
}
class gbm2_Tree_39_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.112558596f
      ? (data[1 /* C3 */] <0.3925928f
        ? (data[1 /* C3 */] <0.35764667f
          ? (data[0 /* C2 */] <0.44765624f
            ? (data[1 /* C3 */] <0.3409375f ? -0.008022014f : 0.04600079f)
            : (data[2 /* C4 */] <0.103125f ? 0.0051048016f : -0.03807453f))
          : (data[0 /* C2 */] <0.45820314f
            ? 0.11532677f
            : (data[2 /* C4 */] <0.1025f ? -0.06368082f : 0.02713768f)))
        : (data[0 /* C2 */] <0.5274414f ? -0.10955661f : -0.011149135f))
      : (data[2 /* C4 */] <0.2327836f
        ? (data[2 /* C4 */] <0.22266157f
          ? (data[0 /* C2 */] <0.71351564f
            ? (data[1 /* C3 */] <0.5765625f ? 0.002566956f : 0.16457438f)
            : (data[0 /* C2 */] <0.7222992f ? -0.07510417f : -0.0018359335f))
          : (data[1 /* C3 */] <0.53203124f ? -0.018628322f : 0.15747163f))
        : -0.059302483f));
    return pred;
  }
}


class gbm2_Forest_40 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_40_class_0.score0(fdata);
  }
}
class gbm2_Tree_40_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.38242432f
      ? (data[0 /* C2 */] <0.5172656f
        ? (data[2 /* C4 */] <0.16332032f
          ? (data[0 /* C2 */] <0.25203124f
            ? (data[2 /* C4 */] <0.05625f ? -0.011815639f : -0.040626567f)
            : (data[0 /* C2 */] <0.47391114f ? -0.0018584392f : -0.013944035f))
          : 0.06655323f)
        : -0.061763603f)
      : (data[0 /* C2 */] <0.5028125f
        ? (data[1 /* C3 */] <0.40777344f
          ? (data[2 /* C4 */] <0.1471875f
            ? (data[0 /* C2 */] <0.48273438f ? 0.071378425f : 0.012555055f)
            : (data[2 /* C4 */] <0.15261474f ? 0.17134306f : 0.016323471f))
          : -0.06166522f)
        : (data[1 /* C3 */] <0.3922461f
          ? (data[2 /* C4 */] <0.1478125f
            ? (data[2 /* C4 */] <0.13249756f ? -0.037515398f : 0.07071645f)
            : -0.1894352f)
          : (data[0 /* C2 */] <0.55222654f
            ? (data[2 /* C4 */] <0.1790625f ? 0.008051391f : 0.17208198f)
            : (data[0 /* C2 */] <0.5624911f ? -0.031537265f : 0.0021792403f)))));
    return pred;
  }
}


class gbm2_Forest_41 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_41_class_0.score0(fdata);
  }
}
class gbm2_Tree_41_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.5326269f
      ? (data[0 /* C2 */] <0.6574609f
        ? (data[1 /* C3 */] <0.5225781f
          ? (data[1 /* C3 */] <0.51709867f
            ? (data[1 /* C3 */] <0.4809972f ? -0.0019083469f : 0.011688547f)
            : (data[2 /* C4 */] <0.1765625f ? -0.11615201f : 0.02123112f))
          : (data[2 /* C4 */] <0.18539062f
            ? (data[0 /* C2 */] <0.6471875f ? -0.05555835f : 0.08811133f)
            : 0.1380696f))
        : (data[2 /* C4 */] <0.18759766f
          ? (data[2 /* C4 */] <0.15265426f
            ? 0.049361583f
            : (data[0 /* C2 */] <0.6671094f ? 0.0039391317f : -0.031804495f))
          : (data[0 /* C2 */] <0.67751956f
            ? (data[2 /* C4 */] <0.19765624f ? -0.13500488f : -0.057672806f)
            : -0.026643382f)))
      : (data[0 /* C2 */] <0.6827539f
        ? (data[0 /* C2 */] <0.6625305f
          ? (data[2 /* C4 */] <0.1775586f
            ? 0.03536661f
            : (data[2 /* C4 */] <0.19763382f ? -0.09398194f : -0.038117584f))
          : (data[1 /* C3 */] <0.5375781f
            ? 0.27510908f
            : (data[1 /* C3 */] <0.5427649f ? -0.082922645f : 0.14375296f)))
        : (data[0 /* C2 */] <0.68766147f
          ? -0.14031681f
          : (data[1 /* C3 */] <0.5426367f
            ? (data[0 /* C2 */] <0.6978125f ? -0.0221599f : 0.15633217f)
            : (data[1 /* C3 */] <0.552702f ? -0.05487236f : 0.00941438f)))));
    return pred;
  }
}


class gbm2_Forest_42 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_42_class_0.score0(fdata);
  }
}
class gbm2_Tree_42_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.3025293f
      ? (data[0 /* C2 */] <0.36767578f
        ? (data[1 /* C3 */] <0.2722461f
          ? (data[1 /* C3 */] <0.2671544f
            ? (data[0 /* C2 */] <0.34234375f ? -0.010110481f : 0.020055596f)
            : (data[0 /* C2 */] <0.3559375f ? 0.0027205034f : -0.06363675f))
          : (data[0 /* C2 */] <0.35707033f ? 0.06432774f : 0.040313825f))
        : (data[2 /* C4 */] <0.11757813f
          ? (data[2 /* C4 */] <0.09761963f
            ? (data[0 /* C2 */] <0.38246095f ? -0.03721827f : -0.011733751f)
            : (data[0 /* C2 */] <0.3975f ? 0.02001448f : -0.043660015f))
          : -0.07138806f))
      : (data[0 /* C2 */] <0.39730468f
        ? (data[2 /* C4 */] <0.10152344f ? 0.068032354f : 0.03197987f)
        : (data[2 /* C4 */] <0.23394531f
          ? (data[2 /* C4 */] <0.22297913f
            ? (data[0 /* C2 */] <0.7125f ? 0.0017575481f : -0.025873806f)
            : (data[1 /* C3 */] <0.53351563f ? -0.017010203f : 0.13821916f))
          : -0.054404058f)));
    return pred;
  }
}


class gbm2_Forest_43 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_43_class_0.score0(fdata);
  }
}
class gbm2_Tree_43_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C3 */] <0.5125806f
      ? (data[0 /* C2 */] <0.64734375f
        ? (data[2 /* C4 */] <0.18759766f
          ? (data[0 /* C2 */] <0.6138281f
            ? (data[1 /* C3 */] <0.47445312f ? -0.0012050823f : 0.024805605f)
            : (data[2 /* C4 */] <0.14742188f ? 0.020463558f : -0.019005455f))
          : (data[1 /* C3 */] <0.453125f
            ? (data[0 /* C2 */] <0.5633594f ? -0.05998335f : -0.13099009f)
            : (data[2 /* C4 */] <0.219375f ? 0.052715134f : -0.0176776f)))
        : (data[2 /* C4 */] <0.18759766f
          ? (data[1 /* C3 */] <0.49259767f
            ? -0.10702468f
            : (data[0 /* C2 */] <0.65292966f ? -0.03887794f : 0.014500356f))
          : (data[2 /* C4 */] <0.19747025f ? -0.057993308f : -0.06540612f)))
      : (data[0 /* C2 */] <0.6372266f
        ? (data[1 /* C3 */] <0.5176367f
          ? (data[0 /* C2 */] <0.6275f ? 0.011935443f : 0.15597048f)
          : (data[0 /* C2 */] <0.6275f ? 0.04856996f : 0.0022756197f))
        : (data[0 /* C2 */] <0.7025028f
          ? (data[1 /* C3 */] <0.53240234f
            ? (data[0 /* C2 */] <0.6625f ? 0.015907325f : -0.030162932f)
            : (data[0 /* C2 */] <0.65734375f ? -0.03614499f : 0.04542113f))
          : (data[1 /* C3 */] <0.5524414f
            ? (data[2 /* C4 */] <0.19125f ? -0.019277535f : -0.081693634f)
            : (data[2 /* C4 */] <0.18546875f ? -0.035554346f : 0.013654105f)))));
    return pred;
  }
}


class gbm2_Forest_44 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_44_class_0.score0(fdata);
  }
}
class gbm2_Tree_44_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.112558596f
      ? (data[1 /* C3 */] <0.3925928f
        ? (data[0 /* C2 */] <0.48771486f
          ? (data[0 /* C2 */] <0.47320536f
            ? (data[1 /* C3 */] <0.35859376f ? -0.006218981f : 0.04814833f)
            : (data[2 /* C4 */] <0.107421875f ? -0.04471434f : -0.06306532f))
          : (data[2 /* C4 */] <0.107421875f ? 0.10824187f : -0.012735739f))
        : (data[0 /* C2 */] <0.5274414f ? -0.09925163f : -0.011061844f))
      : (data[0 /* C2 */] <0.3922461f
        ? (data[2 /* C4 */] <0.122929685f ? -0.04723946f : -0.048059043f)
        : (data[0 /* C2 */] <0.43187928f
          ? (data[1 /* C3 */] <0.30828124f
            ? -0.022304527f
            : (data[2 /* C4 */] <0.1178125f ? 0.019774085f : 0.09058032f))
          : (data[1 /* C3 */] <0.34203124f
            ? (data[1 /* C3 */] <0.33250853f ? 0.0054230606f : -0.06909613f)
            : (data[0 /* C2 */] <0.4528125f ? 0.03466788f : 0.0012852821f)))));
    return pred;
  }
}


class gbm2_Forest_45 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_45_class_0.score0(fdata);
  }
}
class gbm2_Tree_45_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.15228516f
      ? (data[0 /* C2 */] <0.65240234f
        ? (data[0 /* C2 */] <0.6422527f
          ? (data[1 /* C3 */] <0.46732423f
            ? (data[0 /* C2 */] <0.569375f ? -0.0014932649f : -0.022048818f)
            : (data[1 /* C3 */] <0.49242753f ? 0.020991055f : -0.023044134f))
          : -0.0671144f)
        : 0.04921842f)
      : (data[0 /* C2 */] <0.4926953f
        ? (data[0 /* C2 */] <0.47259924f ? -0.011278613f : -0.117585756f)
        : (data[0 /* C2 */] <0.50213784f
          ? 0.118650295f
          : (data[0 /* C2 */] <0.5131369f
            ? -0.13469633f
            : (data[1 /* C3 */] <0.4078125f ? 0.091912605f : 0.0034556354f)))));
    return pred;
  }
}


class gbm2_Forest_46 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_46_class_0.score0(fdata);
  }
}
class gbm2_Tree_46_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.23229004f
      ? (data[2 /* C4 */] <0.22230883f
        ? (data[2 /* C4 */] <0.21753266f
          ? (data[2 /* C4 */] <0.21243425f
            ? (data[1 /* C3 */] <0.57609373f ? -6.507738E-4f : 0.0357548f)
            : (data[1 /* C3 */] <0.54015625f ? 0.16864f : -0.018528722f))
          : -0.06157498f)
        : (data[1 /* C3 */] <0.5322949f ? -0.014553204f : 0.12234648f))
      : -0.048220303f);
    return pred;
  }
}


class gbm2_Forest_47 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_47_class_0.score0(fdata);
  }
}
class gbm2_Tree_47_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C2 */] <0.7571875f
      ? (data[0 /* C2 */] <0.7471945f
        ? (data[1 /* C3 */] <0.57267576f
          ? (data[0 /* C2 */] <0.72929686f
            ? (data[2 /* C4 */] <0.211875f ? -5.59598E-4f : 0.037061892f)
            : -0.070504256f)
          : (data[2 /* C4 */] <0.18539062f
            ? 0.15191306f
            : (data[0 /* C2 */] <0.731875f ? -0.047583796f : 0.11254928f)))
        : -0.0798069f)
      : 0.05056052f);
    return pred;
  }
}


class gbm2_Forest_48 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_48_class_0.score0(fdata);
  }
}
class gbm2_Tree_48_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C2 */] <0.48763672f
      ? (data[0 /* C2 */] <0.48239815f
        ? (data[1 /* C3 */] <0.3875f
          ? (data[0 /* C2 */] <0.46734375f
            ? (data[2 /* C4 */] <0.12359375f ? -0.0046016998f : 0.02390035f)
            : (data[2 /* C4 */] <0.14125f ? -0.010904279f : -0.09350731f))
          : 0.074228585f)
        : (data[2 /* C4 */] <0.13683593f
          ? (data[1 /* C3 */] <0.36742187f
            ? 0.03458887f
            : (data[2 /* C4 */] <0.1225f ? -0.120102435f : -0.1320744f))
          : 0.024015466f))
      : (data[0 /* C2 */] <0.4924321f
        ? (data[1 /* C3 */] <0.371875f
          ? 0.17743814f
          : (data[1 /* C3 */] <0.38278806f
            ? -0.046673864f
            : (data[2 /* C4 */] <0.12992187f ? 0.0062712957f : 0.17736891f)))
        : (data[1 /* C3 */] <0.401875f
          ? (data[0 /* C2 */] <0.52875f
            ? (data[2 /* C4 */] <0.15671875f ? -0.014621112f : 0.08877442f)
            : (data[2 /* C4 */] <0.1275f ? -0.011181485f : -0.07830822f))
          : (data[0 /* C2 */] <0.55375f
            ? (data[2 /* C4 */] <0.14f ? -4.5294806E-4f : 0.03891031f)
            : (data[0 /* C2 */] <0.561914f ? -0.02680726f : 8.756807E-4f)))));
    return pred;
  }
}


class gbm2_Forest_49 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm2_Tree_49_class_0.score0(fdata);
  }
}
class gbm2_Tree_49_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C4 */] <0.23229004f
      ? (data[2 /* C4 */] <0.22230883f
        ? (data[1 /* C3 */] <0.5873242f
          ? (data[1 /* C3 */] <0.5790066f
            ? (data[2 /* C4 */] <0.213125f ? -5.256786E-4f : 0.029737476f)
            : 0.08305653f)
          : (data[0 /* C2 */] <0.7461914f ? -0.11721361f : -0.0015630722f))
        : (data[1 /* C3 */] <0.5322949f ? -0.016891614f : 0.11047155f))
      : -0.045433167f);
    return pred;
  }
}


