package ai.h2o.hive.udf.models;/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2016-03-16T13:29:09.724-07:00
  3.8.1.3
  
  Standalone prediction code with sample test data for GBMModel named gbm3

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/gbm3 > gbm3.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m gbm3.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="gbm3", algorithm="gbm")
public class gbm3 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 3; }
  public int nclasses() { return 1; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_gbm3.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* C3 */ null,
    /* C4 */ null,
    /* C5 */ null,
    /* C9 */ null
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {1.0};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {1.0};

  public gbm3() { super(NAMES,DOMAINS); }
  public String getUUID() { return Long.toString(692212135234798296L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    double[] fdata = hex.genmodel.GenModel.SharedTree_clean(data);
    gbm3_Forest_0.score0(fdata,preds);
    gbm3_Forest_1.score0(fdata,preds);
    gbm3_Forest_2.score0(fdata,preds);
    gbm3_Forest_3.score0(fdata,preds);
    gbm3_Forest_4.score0(fdata,preds);
    gbm3_Forest_5.score0(fdata,preds);
    gbm3_Forest_6.score0(fdata,preds);
    gbm3_Forest_7.score0(fdata,preds);
    gbm3_Forest_8.score0(fdata,preds);
    gbm3_Forest_9.score0(fdata,preds);
    gbm3_Forest_10.score0(fdata,preds);
    gbm3_Forest_11.score0(fdata,preds);
    gbm3_Forest_12.score0(fdata,preds);
    gbm3_Forest_13.score0(fdata,preds);
    gbm3_Forest_14.score0(fdata,preds);
    gbm3_Forest_15.score0(fdata,preds);
    gbm3_Forest_16.score0(fdata,preds);
    gbm3_Forest_17.score0(fdata,preds);
    gbm3_Forest_18.score0(fdata,preds);
    gbm3_Forest_19.score0(fdata,preds);
    gbm3_Forest_20.score0(fdata,preds);
    gbm3_Forest_21.score0(fdata,preds);
    gbm3_Forest_22.score0(fdata,preds);
    gbm3_Forest_23.score0(fdata,preds);
    gbm3_Forest_24.score0(fdata,preds);
    gbm3_Forest_25.score0(fdata,preds);
    gbm3_Forest_26.score0(fdata,preds);
    gbm3_Forest_27.score0(fdata,preds);
    gbm3_Forest_28.score0(fdata,preds);
    gbm3_Forest_29.score0(fdata,preds);
    gbm3_Forest_30.score0(fdata,preds);
    gbm3_Forest_31.score0(fdata,preds);
    gbm3_Forest_32.score0(fdata,preds);
    gbm3_Forest_33.score0(fdata,preds);
    gbm3_Forest_34.score0(fdata,preds);
    gbm3_Forest_35.score0(fdata,preds);
    gbm3_Forest_36.score0(fdata,preds);
    gbm3_Forest_37.score0(fdata,preds);
    gbm3_Forest_38.score0(fdata,preds);
    gbm3_Forest_39.score0(fdata,preds);
    gbm3_Forest_40.score0(fdata,preds);
    gbm3_Forest_41.score0(fdata,preds);
    gbm3_Forest_42.score0(fdata,preds);
    gbm3_Forest_43.score0(fdata,preds);
    gbm3_Forest_44.score0(fdata,preds);
    gbm3_Forest_45.score0(fdata,preds);
    gbm3_Forest_46.score0(fdata,preds);
    gbm3_Forest_47.score0(fdata,preds);
    gbm3_Forest_48.score0(fdata,preds);
    gbm3_Forest_49.score0(fdata,preds);
    preds[0] += 9.933684462532918;
    preds[0] = preds[0];
    return preds;
  }
}
// The class representing training column names
class NamesHolder_gbm3 implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    NamesHolder_gbm3_0.fill(VALUES);
  }
  static final class NamesHolder_gbm3_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "C3";
      sa[1] = "C4";
      sa[2] = "C5";
    }
  }
}

class gbm3_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_0_class_0.score0(fdata);
  }
}
class gbm3_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.122490235f
      ? (data[0 /* C3 */] <0.24268067f
        ? (data[0 /* C3 */] <0.1876961f
          ? (data[2 /* C5 */] <0.023304688f
            ? -0.66003513f
            : (data[0 /* C3 */] <0.16773437f ? -0.5556326f : -0.49877384f))
          : (data[0 /* C3 */] <0.22263347f
            ? (data[1 /* C4 */] <0.06234375f ? -0.47597712f : -0.40927753f)
            : (data[2 /* C5 */] <0.130625f ? -0.27757898f : -0.3495088f)))
        : (data[0 /* C3 */] <0.38256344f
          ? (data[1 /* C4 */] <0.1021875f
            ? (data[0 /* C3 */] <0.32726562f ? -0.2651446f : -0.17670177f)
            : (data[2 /* C5 */] <0.60414064f ? -0.15118834f : -0.264797f))
          : (data[2 /* C5 */] <0.60957813f
            ? (data[2 /* C5 */] <0.54613614f ? -0.031829983f : -0.16211845f)
            : (data[0 /* C3 */] <0.42257813f ? 0.031121353f : 0.1583557f))))
      : (data[1 /* C4 */] <0.16282998f
        ? (data[1 /* C4 */] <0.13748685f
          ? (data[2 /* C5 */] <0.8065625f
            ? (data[0 /* C3 */] <0.30875f ? -0.21003512f : -0.033784147f)
            : (data[0 /* C3 */] <0.4225f ? 0.18489243f : 0.04576199f))
          : (data[0 /* C3 */] <0.51125f
            ? (data[0 /* C3 */] <0.42634767f ? 0.10491236f : 0.03731173f)
            : (data[1 /* C4 */] <0.15734375f ? 0.1399649f : 0.26853633f)))
        : (data[1 /* C4 */] <0.19305405f
          ? (data[0 /* C3 */] <0.4526172f
            ? (data[2 /* C5 */] <0.97733593f ? 0.24029493f : 0.33844975f)
            : (data[0 /* C3 */] <0.5728567f ? 0.15825757f : 0.38440934f))
          : (data[1 /* C4 */] <0.22233361f
            ? (data[2 /* C5 */] <1.1170079f ? 0.46288157f : 0.27411124f)
            : (data[0 /* C3 */] <0.49789062f ? 0.29754066f : 0.5177427f)))));
    return pred;
  }
}


class gbm3_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_1_class_0.score0(fdata);
  }
}
class gbm3_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.122490235f
      ? (data[0 /* C3 */] <0.23745117f
        ? (data[0 /* C3 */] <0.18756218f
          ? (data[2 /* C5 */] <0.023304688f
            ? -0.5940316f
            : (data[0 /* C3 */] <0.16773437f ? -0.5000693f : -0.4488965f))
          : (data[0 /* C3 */] <0.22258464f
            ? (data[1 /* C4 */] <0.0625f ? -0.42837945f : -0.36834982f)
            : (data[2 /* C5 */] <0.130625f ? -0.24982104f : -0.32947025f)))
        : (data[0 /* C3 */] <0.38273063f
          ? (data[1 /* C4 */] <0.1021875f
            ? (data[0 /* C3 */] <0.3275f ? -0.2403928f : -0.15903161f)
            : (data[2 /* C5 */] <0.60414064f ? -0.1365952f : -0.2383173f))
          : (data[2 /* C5 */] <0.60957813f
            ? (data[2 /* C5 */] <0.54613614f ? -0.02864699f : -0.14590664f)
            : (data[0 /* C3 */] <0.42257813f ? 0.028009236f : 0.14252013f))))
      : (data[1 /* C4 */] <0.16282998f
        ? (data[1 /* C4 */] <0.15255973f
          ? (data[1 /* C4 */] <0.13253586f
            ? (data[2 /* C5 */] <0.759125f ? -0.05633291f : 0.07745495f)
            : (data[0 /* C3 */] <0.424375f ? 0.06048473f : 0.009304362f))
          : (data[0 /* C3 */] <0.37625f
            ? -0.13113244f
            : (data[0 /* C3 */] <0.40723634f ? 0.2921403f : 0.08829614f)))
        : (data[1 /* C4 */] <0.19305405f
          ? (data[0 /* C3 */] <0.4526172f
            ? (data[0 /* C3 */] <0.3927893f ? 0.11462664f : 0.25789243f)
            : (data[1 /* C4 */] <0.17242187f ? 0.10431218f : 0.1722664f))
          : (data[1 /* C4 */] <0.22233361f
            ? (data[2 /* C5 */] <1.1170079f ? 0.41659337f : 0.24670006f)
            : (data[0 /* C3 */] <0.49789062f ? 0.2677866f : 0.46596837f)))));
    return pred;
  }
}


class gbm3_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_2_class_0.score0(fdata);
  }
}
class gbm3_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.122490235f
      ? (data[0 /* C3 */] <0.24268067f
        ? (data[0 /* C3 */] <0.19246143f
          ? (data[2 /* C5 */] <0.023304688f
            ? -0.53462845f
            : (data[0 /* C3 */] <0.16785157f ? -0.45006236f : -0.39874354f))
          : (data[0 /* C3 */] <0.22254443f
            ? (data[1 /* C4 */] <0.06234375f ? -0.38626617f : -0.32885876f)
            : (data[2 /* C5 */] <0.130625f ? -0.22483896f : -0.28476226f)))
        : (data[0 /* C3 */] <0.3474598f
          ? (data[1 /* C4 */] <0.0975f
            ? (data[1 /* C4 */] <0.07769531f ? -0.27384198f : -0.21716347f)
            : (data[1 /* C4 */] <0.112441406f ? -0.16358238f : -0.12242315f))
          : (data[2 /* C5 */] <0.64979297f
            ? (data[0 /* C3 */] <0.38222656f ? -0.10716634f : -0.06599421f)
            : (data[1 /* C4 */] <0.11179688f ? -0.046098743f : 0.09759368f))))
      : (data[1 /* C4 */] <0.1579105f
        ? (data[1 /* C4 */] <0.13746999f
          ? (data[2 /* C5 */] <0.8065625f
            ? (data[0 /* C3 */] <0.30875f ? -0.18631876f : -0.028924122f)
            : (data[0 /* C3 */] <0.4225f ? 0.15932174f : 0.037218247f))
          : (data[0 /* C3 */] <0.4232031f
            ? (data[0 /* C3 */] <0.37804747f ? 0.031227713f : 0.0998601f)
            : (data[2 /* C5 */] <0.984625f ? -0.0010672588f : 0.056431018f)))
        : (data[1 /* C4 */] <0.18259245f
          ? (data[0 /* C3 */] <0.44246092f
            ? (data[0 /* C3 */] <0.37265655f ? -0.029646428f : 0.22291724f)
            : (data[2 /* C5 */] <1.6050313f ? 0.10022594f : 0.22246416f))
          : (data[1 /* C4 */] <0.21219894f
            ? (data[0 /* C3 */] <0.57625f ? 0.19320324f : 0.31079662f)
            : (data[0 /* C3 */] <0.54398435f ? 0.48635167f : 0.2269602f)))));
    return pred;
  }
}


class gbm3_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_3_class_0.score0(fdata);
  }
}
class gbm3_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.122490235f
      ? (data[0 /* C3 */] <0.24268067f
        ? (data[0 /* C3 */] <0.1876961f
          ? (data[2 /* C5 */] <0.023304688f
            ? -0.4811656f
            : (data[0 /* C3 */] <0.16773437f ? -0.4050561f : -0.3641325f))
          : (data[0 /* C3 */] <0.22263347f
            ? (data[1 /* C4 */] <0.06234375f ? -0.34664372f : -0.29823193f)
            : (data[0 /* C3 */] <0.2275178f ? -0.19952333f : -0.25722992f)))
        : (data[0 /* C3 */] <0.38256344f
          ? (data[1 /* C4 */] <0.1021875f
            ? (data[0 /* C3 */] <0.34308594f ? -0.19102378f : -0.0951308f)
            : (data[2 /* C5 */] <0.5674375f ? -0.10734744f : -0.1678418f))
          : (data[2 /* C5 */] <0.60957813f
            ? (data[2 /* C5 */] <0.54613614f ? -0.019182822f : -0.12471657f)
            : (data[0 /* C3 */] <0.42257813f ? 0.022965152f : 0.123463705f))))
      : (data[1 /* C4 */] <0.16282998f
        ? (data[1 /* C4 */] <0.14251114f
          ? (data[0 /* C3 */] <0.30125f
            ? -0.22672777f
            : (data[2 /* C5 */] <0.80534375f ? -0.015172799f : 0.04301417f))
          : (data[0 /* C3 */] <0.51125f
            ? (data[0 /* C3 */] <0.42746094f ? 0.09442051f : 0.031589977f)
            : (data[1 /* C4 */] <0.15742187f ? 0.1149187f : 0.22108418f)))
        : (data[1 /* C4 */] <0.21194409f
          ? (data[1 /* C4 */] <0.18242066f
            ? (data[0 /* C3 */] <0.4578125f ? 0.18992569f : 0.10345626f)
            : (data[0 /* C3 */] <0.5824219f ? 0.1754579f : 0.31086212f))
          : (data[0 /* C3 */] <0.54222655f
            ? (data[2 /* C5 */] <1.3959453f ? 0.2465492f : 0.5593684f)
            : (data[2 /* C5 */] <1.9886875f ? 0.27513123f : 0.16082954f)))));
    return pred;
  }
}


class gbm3_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_4_class_0.score0(fdata);
  }
}
class gbm3_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.12745605f
      ? (data[0 /* C3 */] <0.27754393f
        ? (data[0 /* C3 */] <0.22234261f
          ? (data[0 /* C3 */] <0.182468f
            ? (data[0 /* C3 */] <0.112758934f ? -0.44606727f : -0.3559113f)
            : (data[1 /* C4 */] <0.06273437f ? -0.3131718f : -0.27023157f))
          : (data[1 /* C4 */] <0.077714846f
            ? (data[1 /* C4 */] <0.06739334f ? -0.16610117f : -0.2390679f)
            : (data[2 /* C5 */] <0.2371875f ? -0.17828116f : -0.24665935f)))
        : (data[2 /* C5 */] <0.6510957f
          ? (data[1 /* C4 */] <0.10253906f
            ? (data[1 /* C4 */] <0.092926025f ? -0.1782461f : -0.1344985f)
            : (data[2 /* C5 */] <0.29075f ? -0.01891028f : -0.088844016f))
          : (data[2 /* C5 */] <0.90338993f
            ? (data[0 /* C3 */] <0.40289062f ? 0.04086548f : -0.01379339f)
            : (data[0 /* C3 */] <0.44453126f ? 0.05135773f : 0.18217383f))))
      : (data[1 /* C4 */] <0.16270174f
        ? (data[1 /* C4 */] <0.15248245f
          ? (data[2 /* C5 */] <1.239f
            ? (data[0 /* C3 */] <0.424375f ? 0.037056014f : -0.0076536024f)
            : (data[2 /* C5 */] <1.3073125f ? 0.20185617f : 0.103347f))
          : (data[0 /* C3 */] <0.37625f
            ? -0.12781703f
            : (data[0 /* C3 */] <0.40723634f ? 0.23906817f : 0.065970026f)))
        : (data[1 /* C4 */] <0.21182236f
          ? (data[1 /* C4 */] <0.18255839f
            ? (data[0 /* C3 */] <0.45328125f ? 0.17769326f : 0.09449525f)
            : (data[2 /* C5 */] <1.1111797f ? 0.2373076f : 0.15368615f))
          : (data[0 /* C3 */] <0.54222655f
            ? (data[2 /* C5 */] <1.3959453f ? 0.22189425f : 0.50343156f)
            : (data[0 /* C3 */] <0.5977972f ? 0.20914058f : 0.08262643f)))));
    return pred;
  }
}


class gbm3_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_5_class_0.score0(fdata);
  }
}
class gbm3_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.122490235f
      ? (data[0 /* C3 */] <0.23745117f
        ? (data[0 /* C3 */] <0.18257327f
          ? (data[2 /* C5 */] <0.023304688f
            ? -0.3914475f
            : (data[0 /* C3 */] <0.1673047f ? -0.32878926f : -0.2970675f))
          : (data[0 /* C3 */] <0.2225077f
            ? (data[1 /* C4 */] <0.0625f ? -0.2818546f : -0.24320844f)
            : (data[0 /* C3 */] <0.2274851f ? -0.1582878f : -0.22381248f)))
        : (data[0 /* C3 */] <0.34749493f
          ? (data[1 /* C4 */] <0.0975f
            ? (data[0 /* C3 */] <0.3269531f ? -0.1679606f : -0.08736383f)
            : (data[2 /* C5 */] <0.29828125f ? -0.08311569f : -0.12473563f))
          : (data[2 /* C5 */] <0.64979297f
            ? (data[2 /* C5 */] <0.6093013f ? -0.07308249f : -0.025193447f)
            : (data[1 /* C4 */] <0.11179688f ? -0.055282068f : 0.07786982f))))
      : (data[1 /* C4 */] <0.1579105f
        ? (data[1 /* C4 */] <0.13746999f
          ? (data[2 /* C5 */] <0.832f
            ? (data[0 /* C3 */] <0.30875f ? -0.14829639f : -0.022065101f)
            : (data[0 /* C3 */] <0.4225f ? 0.24973515f : 0.026642328f))
          : (data[0 /* C3 */] <0.41148436f
            ? (data[0 /* C3 */] <0.37736326f ? 0.02340711f : 0.09445847f)
            : (data[2 /* C5 */] <0.679375f ? -0.11840592f : 0.022867389f)))
        : (data[1 /* C4 */] <0.19208552f
          ? (data[0 /* C3 */] <0.5327539f
            ? (data[0 /* C3 */] <0.45268416f ? 0.14517641f : 0.074864686f)
            : (data[1 /* C4 */] <0.1675f ? 0.28642264f : 0.15281431f))
          : (data[1 /* C4 */] <0.21406789f
            ? (data[2 /* C5 */] <1.1170079f ? 0.33808717f : 0.14541626f)
            : (data[0 /* C3 */] <0.54398435f ? 0.35455036f : 0.16545397f)))));
    return pred;
  }
}


class gbm3_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_6_class_0.score0(fdata);
  }
}
class gbm3_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.12745605f
      ? (data[0 /* C3 */] <0.27754393f
        ? (data[0 /* C3 */] <0.22234261f
          ? (data[0 /* C3 */] <0.182468f
            ? (data[0 /* C3 */] <0.112758934f ? -0.3627978f : -0.2880665f)
            : (data[1 /* C4 */] <0.072578125f ? -0.23776224f : -0.2058154f))
          : (data[1 /* C4 */] <0.08265625f
            ? (data[1 /* C4 */] <0.06780396f ? -0.12999913f : -0.18620689f)
            : (data[0 /* C3 */] <0.26757812f ? -0.12514484f : -0.18821175f)))
        : (data[2 /* C5 */] <0.6510957f
          ? (data[1 /* C4 */] <0.10253906f
            ? (data[0 /* C3 */] <0.34214842f ? -0.12882268f : -0.069045864f)
            : (data[2 /* C5 */] <0.29075f ? -0.0084569855f : -0.072222084f))
          : (data[2 /* C5 */] <0.90338993f
            ? (data[2 /* C5 */] <0.7144725f ? -0.026316574f : 0.024485642f)
            : (data[0 /* C3 */] <0.45734376f ? 0.16128378f : 0.027041193f))))
      : (data[1 /* C4 */] <0.16270174f
        ? (data[1 /* C4 */] <0.15248245f
          ? (data[2 /* C5 */] <1.239f
            ? (data[0 /* C3 */] <0.424375f ? 0.031190043f : -0.008609385f)
            : (data[2 /* C5 */] <1.3073125f ? 0.17884545f : 0.09067841f))
          : (data[0 /* C3 */] <0.37625f
            ? -0.12291097f
            : (data[0 /* C3 */] <0.40723634f ? 0.20388964f : 0.053035762f)))
        : (data[1 /* C4 */] <0.19670832f
          ? (data[0 /* C3 */] <0.58339846f
            ? (data[0 /* C3 */] <0.45789614f ? 0.1486739f : 0.08446784f)
            : 0.41697708f)
          : (data[0 /* C3 */] <0.46714842f
            ? -0.052369043f
            : (data[2 /* C5 */] <1.5005469f ? 0.2638437f : 0.16093427f)))));
    return pred;
  }
}


class gbm3_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_7_class_0.score0(fdata);
  }
}
class gbm3_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.117524415f
      ? (data[2 /* C5 */] <0.1508955f
        ? (data[0 /* C3 */] <0.19246094f
          ? (data[2 /* C5 */] <0.0413125f
            ? (data[2 /* C5 */] <0.017970704f ? -0.33799997f : -0.2805386f)
            : (data[1 /* C4 */] <0.057148438f ? -0.23050633f : -0.24891502f))
          : (data[2 /* C5 */] <0.11184375f
            ? (data[0 /* C3 */] <0.20164062f ? -0.17875834f : -0.2246595f)
            : (data[2 /* C5 */] <0.13032569f ? -0.15276317f : -0.20712395f)))
        : (data[0 /* C3 */] <0.3523828f
          ? (data[1 /* C4 */] <0.09748047f
            ? (data[0 /* C3 */] <0.32765624f ? -0.13712423f : -0.06172674f)
            : (data[2 /* C5 */] <0.3881875f ? -0.08213328f : -0.12536705f))
          : (data[0 /* C3 */] <0.3822383f
            ? (data[2 /* C5 */] <0.54696876f ? -0.043341246f : -0.14327678f)
            : (data[1 /* C4 */] <0.111875f ? -0.044494122f : 0.085931115f))))
      : (data[1 /* C4 */] <0.15213051f
        ? (data[0 /* C3 */] <0.3071094f
          ? (data[0 /* C3 */] <0.29756898f ? -0.19311875f : -0.114089794f)
          : (data[2 /* C5 */] <0.94240624f
            ? (data[1 /* C4 */] <0.13265625f ? -0.026515732f : 0.012970564f)
            : (data[0 /* C3 */] <0.4215625f ? 0.29371685f : 0.028858224f)))
        : (data[1 /* C4 */] <0.18268894f
          ? (data[2 /* C5 */] <1.692746f
            ? (data[0 /* C3 */] <0.4175f ? 0.13074443f : 0.05837233f)
            : (data[0 /* C3 */] <0.5628125f ? 0.25066698f : 0.028081711f))
          : (data[1 /* C4 */] <0.2122924f
            ? (data[0 /* C3 */] <0.57625f ? 0.1149489f : 0.20181148f)
            : (data[0 /* C3 */] <0.54398435f ? 0.30165577f : 0.13281514f)))));
    return pred;
  }
}


class gbm3_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_8_class_0.score0(fdata);
  }
}
class gbm3_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.117524415f
      ? (data[2 /* C5 */] <0.1508955f
        ? (data[0 /* C3 */] <0.18257813f
          ? (data[2 /* C5 */] <0.0181875f
            ? -0.29959026f
            : (data[2 /* C5 */] <0.04134668f ? -0.25125104f : -0.22060695f))
          : (data[2 /* C5 */] <0.099125f
            ? (data[2 /* C5 */] <0.078109376f ? -0.22605902f : -0.18820512f)
            : (data[2 /* C5 */] <0.10389453f ? -0.103059605f : -0.17193983f)))
        : (data[0 /* C3 */] <0.3425f
          ? (data[1 /* C4 */] <0.09748047f
            ? (data[1 /* C4 */] <0.08758011f ? -0.13453197f : -0.111588545f)
            : (data[2 /* C5 */] <0.2933125f ? -0.055869136f : -0.10323891f))
          : (data[0 /* C3 */] <0.38225585f
            ? (data[2 /* C5 */] <0.5175f ? -0.043571886f : -0.13032779f)
            : (data[1 /* C4 */] <0.111875f ? -0.040044755f : 0.07733803f))))
      : (data[1 /* C4 */] <0.16300672f
        ? (data[1 /* C4 */] <0.13755548f
          ? (data[2 /* C5 */] <0.8065625f
            ? (data[0 /* C3 */] <0.30875f ? -0.12246962f : -0.025444923f)
            : (data[1 /* C4 */] <0.13242188f ? 0.08406154f : 0.012958384f))
          : (data[2 /* C5 */] <1.4552188f
            ? (data[0 /* C3 */] <0.42515624f ? 0.054984234f : 0.011952602f)
            : 0.17394944f))
        : (data[1 /* C4 */] <0.21211185f
          ? (data[0 /* C3 */] <0.53738284f
            ? (data[0 /* C3 */] <0.45719606f ? 0.11894466f : 0.06639996f)
            : (data[2 /* C5 */] <1.4457891f ? 0.23453067f : 0.11460294f))
          : (data[0 /* C3 */] <0.54222655f
            ? (data[2 /* C5 */] <1.3959453f ? 0.1167345f : 0.36997107f)
            : (data[1 /* C4 */] <0.22929688f ? 0.08918486f : 0.19757321f)))));
    return pred;
  }
}


class gbm3_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_9_class_0.score0(fdata);
  }
}
class gbm3_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.122490235f
      ? (data[0 /* C3 */] <0.27754393f
        ? (data[0 /* C3 */] <0.22234261f
          ? (data[0 /* C3 */] <0.16743332f
            ? (data[0 /* C3 */] <0.11297343f ? -0.26564258f : -0.21913244f)
            : (data[1 /* C4 */] <0.072578125f ? -0.18017967f : -0.15244508f))
          : (data[2 /* C5 */] <0.23711719f
            ? (data[1 /* C4 */] <0.08265625f ? -0.13210067f : -0.09846807f)
            : (data[2 /* C5 */] <0.26204187f ? -0.20575574f : -0.14217748f)))
        : (data[0 /* C3 */] <0.38235852f
          ? (data[1 /* C4 */] <0.09234375f
            ? (data[2 /* C5 */] <0.3716875f ? -0.11759732f : -0.0039522364f)
            : (data[2 /* C5 */] <0.60414064f ? -0.06367034f : -0.15664236f))
          : (data[2 /* C5 */] <0.60957813f
            ? (data[2 /* C5 */] <0.54613614f ? 0.008209977f : -0.08631506f)
            : (data[1 /* C4 */] <0.11179688f ? -0.012845354f : 0.068935014f))))
      : (data[1 /* C4 */] <0.16282998f
        ? (data[0 /* C3 */] <0.5071289f
          ? (data[0 /* C3 */] <0.30756173f
            ? -0.14138852f
            : (data[2 /* C5 */] <0.3925625f ? 0.21126357f : 0.011037407f))
          : (data[2 /* C5 */] <1.1626875f
            ? 0.28946114f
            : (data[0 /* C3 */] <0.5275781f ? 0.028950745f : 0.13613905f)))
        : (data[1 /* C4 */] <0.18172002f
          ? (data[0 /* C3 */] <0.41144532f
            ? (data[0 /* C3 */] <0.39246765f ? 0.03324341f : 0.2844772f)
            : (data[2 /* C5 */] <1.7141094f ? 0.0529694f : 0.15865496f))
          : (data[1 /* C4 */] <0.21135376f
            ? (data[2 /* C5 */] <1.3610781f ? 0.13007268f : 0.08423656f)
            : (data[0 /* C3 */] <0.54398435f ? 0.24434115f : 0.10758023f)))));
    return pred;
  }
}


class gbm3_Forest_10 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_10_class_0.score0(fdata);
  }
}
class gbm3_Tree_10_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.12745605f
      ? (data[0 /* C3 */] <0.27754393f
        ? (data[0 /* C3 */] <0.22234261f
          ? (data[0 /* C3 */] <0.16743332f
            ? (data[0 /* C3 */] <0.11297343f ? -0.2390783f : -0.19721921f)
            : (data[0 /* C3 */] <0.19248463f ? -0.17238362f : -0.14653082f))
          : (data[2 /* C5 */] <0.23711719f
            ? (data[1 /* C4 */] <0.07726563f ? -0.12615524f : -0.091977805f)
            : (data[0 /* C3 */] <0.2722656f ? -0.12969519f : -0.18817323f)))
        : (data[2 /* C5 */] <0.71554494f
          ? (data[1 /* C4 */] <0.10253906f
            ? (data[0 /* C3 */] <0.34214842f ? -0.085602336f : -0.037357446f)
            : (data[2 /* C5 */] <0.29223436f ? 0.014220957f : -0.047852125f))
          : (data[1 /* C4 */] <0.11230469f
            ? -0.06975211f
            : (data[2 /* C5 */] <0.9415078f ? 0.032094095f : 0.19560851f))))
      : (data[1 /* C4 */] <0.1724922f
        ? (data[1 /* C4 */] <0.15249099f
          ? (data[0 /* C3 */] <0.42125f
            ? (data[2 /* C5 */] <0.7835625f ? 0.013468128f : 0.096500166f)
            : (data[0 /* C3 */] <0.4672949f ? -0.02166398f : 0.031371616f))
          : (data[0 /* C3 */] <0.45625f
            ? (data[0 /* C3 */] <0.37708008f ? -0.06993052f : 0.08443787f)
            : (data[0 /* C3 */] <0.5326953f ? 0.017949272f : 0.14831266f)))
        : (data[0 /* C3 */] <0.39283204f
          ? -0.18309344f
          : (data[1 /* C4 */] <0.21230468f
            ? (data[2 /* C5 */] <1.0915157f ? 0.13835022f : 0.07412392f)
            : (data[0 /* C3 */] <0.5424219f ? 0.23881504f : 0.09682221f)))));
    return pred;
  }
}


class gbm3_Forest_11 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_11_class_0.score0(fdata);
  }
}
class gbm3_Tree_11_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.12745605f
      ? (data[0 /* C3 */] <0.27754393f
        ? (data[0 /* C3 */] <0.22234261f
          ? (data[2 /* C5 */] <0.041789062f
            ? (data[2 /* C5 */] <0.017542602f ? -0.22465256f : -0.18462649f)
            : (data[0 /* C3 */] <0.19292969f ? -0.15772644f : -0.13187777f))
          : (data[2 /* C5 */] <0.23711719f
            ? (data[1 /* C4 */] <0.08804688f ? -0.1028903f : -0.073963605f)
            : (data[2 /* C5 */] <0.26204187f ? -0.1683121f : -0.11364072f)))
        : (data[2 /* C5 */] <0.71554494f
          ? (data[1 /* C4 */] <0.10253906f
            ? (data[0 /* C3 */] <0.34214842f ? -0.077042066f : -0.033621714f)
            : (data[2 /* C5 */] <0.29223436f ? 0.012798837f : -0.043066874f))
          : (data[1 /* C4 */] <0.11230469f
            ? -0.06277694f
            : (data[2 /* C5 */] <0.9415078f ? 0.028884696f : 0.1760477f))))
      : (data[1 /* C4 */] <0.1724922f
        ? (data[1 /* C4 */] <0.15249099f
          ? (data[0 /* C3 */] <0.39125f
            ? (data[2 /* C5 */] <0.5391875f ? -0.011099062f : 0.070833884f)
            : (data[2 /* C5 */] <1.247875f ? -0.0042952145f : 0.10822911f))
          : (data[0 /* C3 */] <0.45625f
            ? (data[2 /* C5 */] <1.19225f ? 0.07502437f : -0.09310484f)
            : (data[0 /* C3 */] <0.5326953f ? 0.016154362f : 0.1334814f)))
        : (data[0 /* C3 */] <0.39283204f
          ? -0.16478413f
          : (data[1 /* C4 */] <0.21230468f
            ? (data[0 /* C3 */] <0.41890624f ? 0.21493669f : 0.07149713f)
            : (data[0 /* C3 */] <0.5424219f ? 0.2149335f : 0.08714003f)))));
    return pred;
  }
}


class gbm3_Forest_12 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_12_class_0.score0(fdata);
  }
}
class gbm3_Tree_12_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.12745605f
      ? (data[0 /* C3 */] <0.27754393f
        ? (data[0 /* C3 */] <0.22234261f
          ? (data[2 /* C5 */] <0.041789062f
            ? (data[0 /* C3 */] <0.1375f ? -0.16426483f : -0.19942515f)
            : (data[0 /* C3 */] <0.19292969f ? -0.14195381f : -0.11868997f))
          : (data[0 /* C3 */] <0.26738936f
            ? (data[1 /* C4 */] <0.08265625f ? -0.10035388f : -0.05813757f)
            : (data[0 /* C3 */] <0.2724433f ? -0.13317893f : -0.082956f)))
        : (data[2 /* C5 */] <0.6510957f
          ? (data[1 /* C4 */] <0.10253906f
            ? (data[2 /* C5 */] <0.2170625f ? -0.11964326f : -0.06271076f)
            : (data[2 /* C5 */] <0.5281875f ? -0.030596446f : -0.05785204f))
          : (data[0 /* C3 */] <0.45257813f
            ? (data[1 /* C4 */] <0.122421876f ? 0.036800336f : -0.018435523f)
            : 0.095870875f)))
      : (data[1 /* C4 */] <0.1724922f
        ? (data[1 /* C4 */] <0.15249099f
          ? (data[0 /* C3 */] <0.39125f
            ? (data[2 /* C5 */] <0.5391875f ? -0.009989176f : 0.06375047f)
            : (data[2 /* C5 */] <1.247875f ? -0.0038656795f : 0.09740624f))
          : (data[0 /* C3 */] <0.42625f
            ? (data[0 /* C3 */] <0.3769922f ? -0.07043998f : 0.10542147f)
            : (data[0 /* C3 */] <0.5316699f ? 0.022881187f : 0.120133296f)))
        : (data[0 /* C3 */] <0.39283204f
          ? -0.14830568f
          : (data[1 /* C4 */] <0.21230468f
            ? (data[2 /* C5 */] <1.0915157f ? 0.11588672f : 0.05947419f)
            : (data[0 /* C3 */] <0.5424219f ? 0.19344017f : 0.078426026f)))));
    return pred;
  }
}


class gbm3_Forest_13 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_13_class_0.score0(fdata);
  }
}
class gbm3_Tree_13_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.112558596f
      ? (data[2 /* C5 */] <0.1508955f
        ? (data[2 /* C5 */] <0.07441207f
          ? (data[2 /* C5 */] <0.023497334f
            ? -0.17428088f
            : (data[0 /* C3 */] <0.1425f ? -0.12229033f : -0.14224851f))
          : (data[2 /* C5 */] <0.13021722f
            ? (data[2 /* C5 */] <0.119863994f ? -0.11000238f : -0.053391807f)
            : (data[1 /* C4 */] <0.071875f ? -0.090998605f : -0.13831244f)))
        : (data[0 /* C3 */] <0.356875f
          ? (data[2 /* C5 */] <0.15885547f
            ? -0.012370332f
            : (data[1 /* C4 */] <0.0825f ? -0.09964704f : -0.062185608f))
          : (data[2 /* C5 */] <0.5280625f
            ? (data[2 /* C5 */] <0.49656838f ? -0.030626591f : 0.14337792f)
            : (data[2 /* C5 */] <0.6066172f ? -0.09653556f : -0.005801819f))))
      : (data[1 /* C4 */] <0.15727037f
        ? (data[1 /* C4 */] <0.1375387f
          ? (data[2 /* C5 */] <0.80432034f
            ? (data[2 /* C5 */] <0.7768366f ? -0.019232642f : -0.109784424f)
            : (data[1 /* C4 */] <0.13234375f ? 0.0762676f : 0.009470184f))
          : (data[0 /* C3 */] <0.41365233f
            ? (data[0 /* C3 */] <0.37790602f ? 0.005580369f : 0.061023887f)
            : (data[2 /* C5 */] <0.679375f ? -0.11716633f : 0.008220049f)))
        : (data[0 /* C3 */] <0.5328125f
          ? (data[0 /* C3 */] <0.37263182f
            ? -0.09957914f
            : (data[0 /* C3 */] <0.4132033f ? 0.16206905f : 0.03968474f))
          : (data[1 /* C4 */] <0.220625f
            ? (data[2 /* C5 */] <1.98225f ? 0.09371432f : 0.028261872f)
            : (data[2 /* C5 */] <2.1930625f ? 0.29459426f : 0.14203727f)))));
    return pred;
  }
}


class gbm3_Forest_14 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_14_class_0.score0(fdata);
  }
}
class gbm3_Tree_14_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C3 */] <0.34262207f
      ? (data[0 /* C3 */] <0.22240503f
        ? (data[0 /* C3 */] <0.16747525f
          ? (data[2 /* C5 */] <0.018570313f
            ? -0.1649792f
            : (data[1 /* C4 */] <0.03722656f ? -0.10125985f : -0.13601044f))
          : (data[1 /* C4 */] <0.072578125f
            ? (data[0 /* C3 */] <0.20242187f ? -0.09893128f : -0.12330228f)
            : (data[1 /* C4 */] <0.08243286f ? -0.07129647f : -0.1332092f)))
        : (data[0 /* C3 */] <0.27752766f
          ? (data[0 /* C3 */] <0.26747355f
            ? (data[1 /* C4 */] <0.08203125f ? -0.08160266f : -0.0468317f)
            : (data[2 /* C5 */] <0.2168672f ? -0.07510672f : -0.11253183f))
          : (data[1 /* C4 */] <0.11742187f
            ? (data[0 /* C3 */] <0.32734376f ? -0.04626779f : -0.07887416f)
            : (data[0 /* C3 */] <0.3071875f ? -0.089004725f : 0.01107856f))))
      : (data[1 /* C4 */] <0.15228516f
        ? (data[1 /* C4 */] <0.12761673f
          ? (data[2 /* C5 */] <0.7129844f
            ? (data[2 /* C5 */] <0.5312705f ? -0.0151025485f : -0.04363067f)
            : (data[2 /* C5 */] <0.7714238f ? 0.10958304f : 0.009152336f))
          : (data[0 /* C3 */] <0.35703126f
            ? (data[1 /* C4 */] <0.13765626f ? 0.046175297f : 0.18031505f)
            : (data[2 /* C5 */] <1.2390156f ? 8.723514E-4f : 0.086948186f)))
        : (data[1 /* C4 */] <0.18283875f
          ? (data[2 /* C5 */] <1.6925312f
            ? (data[0 /* C3 */] <0.418125f ? 0.082490295f : 0.024560068f)
            : (data[0 /* C3 */] <0.5623438f ? 0.17514475f : -0.033032075f))
          : (data[2 /* C5 */] <0.8900117f
            ? -0.05378529f
            : (data[2 /* C5 */] <1.1017058f ? 0.15131843f : 0.06642704f)))));
    return pred;
  }
}


class gbm3_Forest_15 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_15_class_0.score0(fdata);
  }
}
class gbm3_Tree_15_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.5727661f
      ? (data[0 /* C3 */] <0.27754393f
        ? (data[0 /* C3 */] <0.192786f
          ? (data[2 /* C5 */] <0.041789062f
            ? (data[0 /* C3 */] <0.13726562f ? -0.119362354f : -0.15276569f)
            : (data[2 /* C5 */] <0.0625387f ? -0.08996092f : -0.11446163f))
          : (data[2 /* C5 */] <0.15030469f
            ? (data[2 /* C5 */] <0.13024567f ? -0.0747022f : -0.10619516f)
            : (data[0 /* C3 */] <0.266875f ? -0.051905848f : -0.086999245f)))
        : (data[1 /* C4 */] <0.1321875f
          ? (data[0 /* C3 */] <0.3876758f
            ? (data[1 /* C4 */] <0.1178125f ? -0.039700054f : -0.011199429f)
            : (data[1 /* C4 */] <0.12289062f ? -0.037225075f : -0.17983419f))
          : (data[2 /* C5 */] <0.520293f
            ? (data[0 /* C3 */] <0.3573828f ? 0.018659048f : -0.07276598f)
            : (data[0 /* C3 */] <0.36226562f ? 0.12916583f : 0.013456567f))))
      : (data[1 /* C4 */] <0.17325196f
        ? (data[1 /* C4 */] <0.1525432f
          ? (data[2 /* C5 */] <1.2383633f
            ? (data[0 /* C3 */] <0.42671874f ? 0.012018924f : -0.009585744f)
            : (data[2 /* C5 */] <1.3067553f ? 0.12547632f : 0.036933243f))
          : (data[0 /* C3 */] <0.45826173f
            ? (data[2 /* C5 */] <1.1848671f ? 0.05723457f : -0.11768017f)
            : (data[0 /* C3 */] <0.53252244f ? 0.0065052635f : 0.097048275f)))
        : (data[2 /* C5 */] <0.9249531f
          ? (data[0 /* C3 */] <0.4429297f
            ? (data[0 /* C3 */] <0.4220221f ? 0.13102274f : -0.009930264f)
            : -0.18541707f)
          : (data[2 /* C5 */] <1.0734333f
            ? (data[2 /* C5 */] <1.0571984f ? 0.11798964f : 0.33516926f)
            : (data[0 /* C3 */] <0.43125f ? -0.17569192f : 0.05131769f)))));
    return pred;
  }
}


class gbm3_Forest_16 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_16_class_0.score0(fdata);
  }
}
class gbm3_Tree_16_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C3 */] <0.34262207f
      ? (data[0 /* C3 */] <0.22240503f
        ? (data[1 /* C4 */] <0.052734375f
          ? (data[2 /* C5 */] <0.042242188f
            ? (data[1 /* C4 */] <0.0421875f ? -0.11145987f : -0.14359434f)
            : -0.09151884f)
          : (data[1 /* C4 */] <0.08246002f
            ? (data[1 /* C4 */] <0.07237705f ? -0.08796788f : -0.058836058f)
            : -0.11403528f))
        : (data[0 /* C3 */] <0.30233285f
          ? (data[2 /* C5 */] <0.27757812f
            ? (data[2 /* C5 */] <0.25821018f ? -0.05407096f : 0.012251055f)
            : (data[1 /* C4 */] <0.09296875f ? -0.049291f : -0.09398418f))
          : (data[2 /* C5 */] <0.302875f
            ? (data[2 /* C5 */] <0.2836387f ? -0.029963741f : 0.10280051f)
            : (data[1 /* C4 */] <0.11671875f ? -0.054866273f : 9.274497E-4f))))
      : (data[2 /* C5 */] <0.90088767f
        ? (data[1 /* C4 */] <0.14566407f
          ? (data[0 /* C3 */] <0.4276953f
            ? (data[2 /* C5 */] <0.81639063f ? -0.011375412f : 0.13649374f)
            : (data[2 /* C5 */] <0.86445314f ? -0.037484746f : -0.080234915f))
          : (data[0 /* C3 */] <0.4175f
            ? (data[2 /* C5 */] <0.777125f ? 0.038310748f : 0.17862575f)
            : (data[0 /* C3 */] <0.43751952f ? -0.047847003f : 0.024978856f)))
        : (data[0 /* C3 */] <0.39742187f
          ? -0.1629872f
          : (data[0 /* C3 */] <0.442807f
            ? (data[2 /* C5 */] <1.142f ? 0.14426407f : -0.10671101f)
            : (data[1 /* C4 */] <0.186875f ? 0.017726097f : 0.06910761f)))));
    return pred;
  }
}


class gbm3_Forest_17 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_17_class_0.score0(fdata);
  }
}
class gbm3_Tree_17_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.112558596f
      ? (data[2 /* C5 */] <0.1508955f
        ? (data[1 /* C4 */] <0.052421875f
          ? (data[2 /* C5 */] <0.04246875f
            ? (data[1 /* C4 */] <0.042578124f ? -0.1003139f : -0.12923491f)
            : (data[2 /* C5 */] <0.0528313f ? -0.08917807f : -0.080702156f))
          : (data[2 /* C5 */] <0.099125f
            ? (data[2 /* C5 */] <0.06249414f ? -0.066332914f : -0.08725258f)
            : (data[2 /* C5 */] <0.10389453f ? -0.0025417458f : -0.07031395f)))
        : (data[0 /* C3 */] <0.356875f
          ? (data[2 /* C5 */] <0.15885547f
            ? 0.007914522f
            : (data[1 /* C4 */] <0.0825f ? -0.0716086f : -0.041492824f))
          : (data[0 /* C3 */] <0.3673755f
            ? (data[2 /* C5 */] <0.482125f ? -0.010121889f : 0.13442302f)
            : (data[1 /* C4 */] <0.10703125f ? 0.011221412f : -0.065743454f))))
      : (data[2 /* C5 */] <0.9229463f
        ? (data[1 /* C4 */] <0.14671876f
          ? (data[2 /* C5 */] <0.80691797f
            ? (data[2 /* C5 */] <0.7701106f ? -0.009803514f : -0.065100886f)
            : (data[0 /* C3 */] <0.42625f ? 0.08362395f : -0.016863205f))
          : (data[0 /* C3 */] <0.4178125f
            ? (data[0 /* C3 */] <0.37727052f ? -0.062259886f : 0.09507516f)
            : (data[0 /* C3 */] <0.43238768f ? -0.044102114f : 0.012148259f)))
        : (data[0 /* C3 */] <0.4421875f
          ? (data[0 /* C3 */] <0.397572f
            ? -0.13539848f
            : (data[2 /* C5 */] <1.1463907f ? 0.15638831f : -0.09603987f))
          : (data[1 /* C4 */] <0.186875f
            ? (data[2 /* C5 */] <1.5472578f ? 0.009822453f : 0.072900094f)
            : (data[2 /* C5 */] <1.2499921f ? 0.15775676f : 0.048018776f)))));
    return pred;
  }
}


class gbm3_Forest_18 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_18_class_0.score0(fdata);
  }
}
class gbm3_Tree_18_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C3 */] <0.34262207f
      ? (data[0 /* C3 */] <0.24262846f
        ? (data[0 /* C3 */] <0.18252872f
          ? (data[2 /* C5 */] <0.018570313f
            ? -0.11485893f
            : (data[1 /* C4 */] <0.03722656f ? -0.05710927f : -0.085953526f))
          : (data[2 /* C5 */] <0.17717187f
            ? (data[2 /* C5 */] <0.16146801f ? -0.06113111f : -0.027924808f)
            : -0.09459677f))
        : (data[2 /* C5 */] <0.38860938f
          ? (data[2 /* C5 */] <0.3824779f
            ? (data[1 /* C4 */] <0.09765625f ? -0.04339303f : -0.021635335f)
            : 0.083432995f)
          : (data[2 /* C5 */] <0.40082946f
            ? (data[2 /* C5 */] <0.3938057f ? -0.14717382f : -0.12348107f)
            : (data[0 /* C3 */] <0.3273828f ? -0.08004486f : -0.023171399f))))
      : (data[1 /* C4 */] <0.15780273f
        ? (data[1 /* C4 */] <0.13270068f
          ? (data[2 /* C5 */] <0.8160156f
            ? (data[2 /* C5 */] <0.51654005f ? -0.005711584f : -0.026657002f)
            : (data[0 /* C3 */] <0.4215625f ? 0.14653248f : 0.023059756f))
          : (data[0 /* C3 */] <0.351875f
            ? (data[2 /* C5 */] <0.52365625f ? 0.20009618f : 0.09175234f)
            : (data[0 /* C3 */] <0.39183596f ? 0.032094866f : 0.0015279173f)))
        : (data[0 /* C3 */] <0.5326465f
          ? (data[2 /* C5 */] <1.107164f
            ? (data[2 /* C5 */] <1.0853307f ? 0.033821966f : 0.15133706f)
            : (data[2 /* C5 */] <1.1218568f ? -0.09146205f : 0.016341245f))
          : (data[1 /* C4 */] <0.220625f
            ? (data[1 /* C4 */] <0.17752442f ? 0.09873951f : 0.035136115f)
            : (data[2 /* C5 */] <2.1930625f ? 0.24164769f : 0.10434645f)))));
    return pred;
  }
}


class gbm3_Forest_19 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_19_class_0.score0(fdata);
  }
}
class gbm3_Tree_19_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.5727661f
      ? (data[0 /* C3 */] <0.27754393f
        ? (data[2 /* C5 */] <0.113425784f
          ? (data[2 /* C5 */] <0.041173127f
            ? (data[0 /* C3 */] <0.13867188f ? -0.0766755f : -0.107802145f)
            : (data[2 /* C5 */] <0.10358414f ? -0.05880319f : -0.09016216f))
          : (data[2 /* C5 */] <0.21779938f
            ? (data[2 /* C5 */] <0.19661357f ? -0.0456616f : -0.0084835375f)
            : (data[2 /* C5 */] <0.27959955f ? -0.0658383f : -0.097112976f)))
        : (data[0 /* C3 */] <0.397633f
          ? (data[1 /* C4 */] <0.11742187f
            ? (data[2 /* C5 */] <0.4820078f ? -0.030469757f : 0.0015841043f)
            : (data[0 /* C3 */] <0.36265624f ? 0.014552368f : -0.03446246f))
          : -0.094613224f))
      : (data[1 /* C4 */] <0.16773437f
        ? (data[2 /* C5 */] <1.4880781f
          ? (data[0 /* C3 */] <0.4275f
            ? (data[2 /* C5 */] <0.915375f ? 0.010471723f : 0.10594662f)
            : (data[0 /* C3 */] <0.43365234f ? -0.064157f : 0.0014063803f))
          : (data[0 /* C3 */] <0.51486325f ? 0.17597926f : 0.07311172f))
        : (data[2 /* C5 */] <0.828166f
          ? (data[0 /* C3 */] <0.4332422f ? 0.0120794885f : -0.1661101f)
          : (data[0 /* C3 */] <0.4719922f
            ? (data[2 /* C5 */] <1.33075f ? 0.08393238f : -0.14848469f)
            : (data[1 /* C4 */] <0.18617187f ? 0.01301038f : 0.04927898f)))));
    return pred;
  }
}


class gbm3_Forest_20 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_20_class_0.score0(fdata);
  }
}
class gbm3_Tree_20_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.57828075f
      ? (data[0 /* C3 */] <0.3025293f
        ? (data[2 /* C5 */] <0.10775f
          ? (data[2 /* C5 */] <0.104032226f
            ? (data[2 /* C5 */] <0.09924947f ? -0.06558123f : 0.009705816f)
            : -0.101364404f)
          : (data[1 /* C4 */] <0.1225f
            ? (data[2 /* C5 */] <0.2793125f ? -0.03173991f : -0.06249429f)
            : -0.11480315f))
        : (data[1 /* C4 */] <0.1321875f
          ? (data[2 /* C5 */] <0.5181016f
            ? (data[1 /* C4 */] <0.12289062f ? -0.01938151f : 0.030898988f)
            : (data[2 /* C5 */] <0.52278113f ? -0.12426414f : -0.043592747f))
          : (data[2 /* C5 */] <0.521625f
            ? (data[0 /* C3 */] <0.35742188f ? 0.017035699f : -0.07106702f)
            : (data[2 /* C5 */] <0.5374805f ? 0.14690745f : 0.020878658f))))
      : (data[0 /* C3 */] <0.51229006f
        ? (data[2 /* C5 */] <1.5966718f
          ? (data[0 /* C3 */] <0.361875f
            ? (data[2 /* C5 */] <0.6261953f ? -0.013375036f : -0.14378363f)
            : (data[1 /* C4 */] <0.18921874f ? 0.006531984f : 0.04794229f))
          : (data[2 /* C5 */] <1.647052f ? 0.22254053f : 0.013387168f))
        : (data[1 /* C4 */] <0.2240625f
          ? (data[2 /* C5 */] <2.1469376f
            ? (data[2 /* C5 */] <2.1115959f ? 0.036767684f : 0.19842981f)
            : (data[2 /* C5 */] <2.3900142f ? -0.12027902f : 0.11278909f))
          : (data[0 /* C3 */] <0.5798633f ? 0.18676227f : 0.088536434f))));
    return pred;
  }
}


class gbm3_Forest_21 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_21_class_0.score0(fdata);
  }
}
class gbm3_Tree_21_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.112558596f
      ? (data[1 /* C4 */] <0.07749396f
        ? (data[1 /* C4 */] <0.05252032f
          ? (data[0 /* C3 */] <0.11171875f
            ? -0.0874925f
            : (data[1 /* C4 */] <0.0375f ? -0.04154078f : -0.07222335f))
          : (data[2 /* C5 */] <0.11023437f
            ? (data[0 /* C3 */] <0.20164062f ? -0.04469854f : -0.078327954f)
            : (data[2 /* C5 */] <0.120090574f ? -0.009289066f : -0.048848543f)))
        : (data[0 /* C3 */] <0.356875f
          ? (data[2 /* C5 */] <0.38426563f
            ? (data[0 /* C3 */] <0.34269533f ? -0.027233278f : 0.06750778f)
            : (data[0 /* C3 */] <0.3514844f ? -0.058765825f : -0.019892009f))
          : (data[2 /* C5 */] <0.50523436f
            ? (data[2 /* C5 */] <0.48187596f ? -0.0056393924f : 0.11372564f)
            : (data[0 /* C3 */] <0.38785157f ? -0.04678043f : -0.011663833f))))
      : (data[2 /* C5 */] <0.9229463f
        ? (data[1 /* C4 */] <0.14671876f
          ? (data[0 /* C3 */] <0.4271875f
            ? (data[2 /* C5 */] <0.8234297f ? -0.007663783f : 0.11392624f)
            : (data[2 /* C5 */] <0.9004844f ? -0.03775506f : 0.04149698f))
          : (data[2 /* C5 */] <0.8234297f
            ? (data[2 /* C5 */] <0.80919755f ? 0.034511447f : 0.18207105f)
            : (data[0 /* C3 */] <0.43761718f ? -0.07472182f : 0.013496882f)))
        : (data[0 /* C3 */] <0.4421875f
          ? (data[0 /* C3 */] <0.397572f
            ? -0.13436317f
            : (data[2 /* C5 */] <1.1463907f ? 0.1327709f : -0.086792424f))
          : (data[1 /* C4 */] <0.186875f
            ? (data[0 /* C3 */] <0.573125f ? 0.008080556f : 0.15584196f)
            : (data[2 /* C5 */] <1.5175313f ? 0.083222084f : 0.014880892f)))));
    return pred;
  }
}


class gbm3_Forest_22 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_22_class_0.score0(fdata);
  }
}
class gbm3_Tree_22_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.57828075f
      ? (data[0 /* C3 */] <0.27754393f
        ? (data[0 /* C3 */] <0.192786f
          ? (data[0 /* C3 */] <0.11259024f
            ? -0.07874326f
            : (data[1 /* C4 */] <0.03722656f ? -0.029038634f : -0.056314297f))
          : (data[2 /* C5 */] <0.21541406f
            ? (data[2 /* C5 */] <0.20648193f ? -0.033758443f : 0.03461733f)
            : (data[0 /* C3 */] <0.266875f ? -0.037978984f : -0.06275857f)))
        : (data[1 /* C4 */] <0.1321875f
          ? (data[2 /* C5 */] <0.5181016f
            ? (data[1 /* C4 */] <0.12289062f ? -0.017543321f : 0.024739118f)
            : (data[2 /* C5 */] <0.52278113f ? -0.11021803f : -0.038591534f))
          : (data[2 /* C5 */] <0.521625f
            ? (data[0 /* C3 */] <0.34273437f ? -0.084592514f : 0.0033222386f)
            : (data[0 /* C3 */] <0.36226562f ? 0.12800775f : 0.013492581f))))
      : (data[2 /* C5 */] <1.7150577f
        ? (data[2 /* C5 */] <1.6440228f
          ? (data[2 /* C5 */] <1.5940764f
            ? (data[2 /* C5 */] <1.5306028f ? 0.010471353f : -0.046363547f)
            : (data[1 /* C4 */] <0.18921874f ? 0.1548348f : 0.03318738f))
          : (data[2 /* C5 */] <1.6759416f
            ? (data[2 /* C5 */] <1.6609577f ? -0.109854415f : -0.1278369f)
            : (data[2 /* C5 */] <1.6890885f ? 0.0983312f : -0.059975814f)))
        : (data[2 /* C5 */] <1.8516942f
          ? (data[2 /* C5 */] <1.797584f
            ? (data[2 /* C5 */] <1.7351818f ? 0.25580126f : 0.014288842f)
            : (data[2 /* C5 */] <1.821514f ? 0.38682666f : 0.10252245f))
          : (data[1 /* C4 */] <0.22160156f
            ? (data[2 /* C5 */] <1.8867812f ? -0.16231789f : 0.014779035f)
            : 0.12186199f))));
    return pred;
  }
}


class gbm3_Forest_23 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_23_class_0.score0(fdata);
  }
}
class gbm3_Tree_23_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.7299336f
      ? (data[0 /* C3 */] <0.3025293f
        ? (data[1 /* C4 */] <0.12359375f
          ? (data[1 /* C4 */] <0.08786743f
            ? (data[1 /* C4 */] <0.052857753f ? -0.056823086f : -0.036470775f)
            : (data[2 /* C5 */] <0.28067186f ? -0.00934632f : -0.05432712f))
          : -0.107009985f)
        : (data[0 /* C3 */] <0.39740965f
          ? (data[1 /* C4 */] <0.13242188f
            ? (data[2 /* C5 */] <0.67120314f ? -0.014891842f : 0.12015831f)
            : (data[2 /* C5 */] <0.5210781f ? -0.018322347f : 0.060778685f))
          : (data[1 /* C4 */] <0.12359375f
            ? (data[2 /* C5 */] <0.64864844f ? 0.004126237f : 0.1440523f)
            : (data[1 /* C4 */] <0.1422705f ? -0.059894662f : -5.3865137E-5f))))
      : (data[0 /* C3 */] <0.37748536f
        ? -0.13217816f
        : (data[0 /* C3 */] <0.39238852f
          ? 0.14178632f
          : (data[1 /* C4 */] <0.19859375f
            ? (data[0 /* C3 */] <0.5822656f ? 0.009712077f : 0.2221657f)
            : (data[0 /* C3 */] <0.5982031f ? 0.053490147f : -0.08682942f)))));
    return pred;
  }
}


class gbm3_Forest_24 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_24_class_0.score0(fdata);
  }
}
class gbm3_Tree_24_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.8043814f
      ? (data[1 /* C4 */] <0.14676757f
        ? (data[2 /* C5 */] <0.7758047f
          ? (data[0 /* C3 */] <0.30191407f
            ? (data[1 /* C4 */] <0.12234375f ? -0.02849049f : -0.096309f)
            : (data[0 /* C3 */] <0.42805085f ? -0.0058184937f : -0.048468035f))
          : (data[0 /* C3 */] <0.42285156f
            ? (data[0 /* C3 */] <0.4075241f ? -0.096298106f : -0.21433274f)
            : (data[0 /* C3 */] <0.4471283f ? 0.014253018f : -0.090994835f)))
        : (data[2 /* C5 */] <0.7883359f
          ? (data[2 /* C5 */] <0.7752004f
            ? (data[2 /* C5 */] <0.5493314f ? -0.07639893f : 0.023485646f)
            : 0.30063158f)
          : -0.08539732f))
      : (data[0 /* C3 */] <0.37748536f
        ? -0.12471463f
        : (data[0 /* C3 */] <0.4174045f
          ? (data[2 /* C5 */] <0.9939687f
            ? (data[2 /* C5 */] <0.9258784f ? 0.084014334f : 0.36774454f)
            : -0.09710823f)
          : (data[0 /* C3 */] <0.51189643f
            ? (data[1 /* C4 */] <0.186875f ? 0.001893922f : 0.03830207f)
            : (data[2 /* C5 */] <1.1838437f ? 0.14794314f : 0.025516769f)))));
    return pred;
  }
}


class gbm3_Forest_25 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_25_class_0.score0(fdata);
  }
}
class gbm3_Tree_25_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.112558596f
      ? (data[2 /* C5 */] <0.7988667f
        ? (data[2 /* C5 */] <0.49692893f
          ? (data[2 /* C5 */] <0.48919567f
            ? (data[0 /* C3 */] <0.22125f ? -0.03821136f : -0.018750882f)
            : -0.10798168f)
          : (data[2 /* C5 */] <0.5166231f
            ? 0.14951363f
            : (data[2 /* C5 */] <0.6096364f ? -0.057014897f : 0.054460783f)))
        : -0.10661698f)
      : (data[2 /* C5 */] <0.93949026f
        ? (data[0 /* C3 */] <0.42734376f
          ? (data[2 /* C5 */] <0.75875f
            ? (data[0 /* C3 */] <0.39765626f ? 0.004084682f : -0.020462357f)
            : (data[2 /* C5 */] <0.87422264f ? 0.047668945f : -0.057573818f))
          : (data[0 /* C3 */] <0.4324524f
            ? (data[2 /* C5 */] <0.86741406f ? -0.04631714f : -0.10679083f)
            : (data[1 /* C4 */] <0.1721875f ? -0.0031282161f : -0.060599413f)))
        : (data[2 /* C5 */] <0.9468575f
          ? 0.16219148f
          : (data[0 /* C3 */] <0.3976367f
            ? -0.11044342f
            : (data[0 /* C3 */] <0.44298324f ? 0.08620101f : 0.011308332f)))));
    return pred;
  }
}


class gbm3_Forest_26 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_26_class_0.score0(fdata);
  }
}
class gbm3_Tree_26_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.1373877f
      ? (data[0 /* C3 */] <0.41234863f
        ? (data[2 /* C5 */] <0.77292967f
          ? (data[0 /* C3 */] <0.24220704f
            ? (data[1 /* C4 */] <0.052734375f ? -0.04453139f : -0.02876394f)
            : (data[0 /* C3 */] <0.24745056f ? 0.0407656f : -0.0117664635f))
          : (data[2 /* C5 */] <0.8223039f ? -0.18816285f : 0.015701724f))
        : (data[0 /* C3 */] <0.4874832f
          ? (data[0 /* C3 */] <0.41754824f
            ? 0.08414036f
            : (data[2 /* C5 */] <0.85428125f ? -0.00690992f : 0.034044787f))
          : -0.09499482f))
      : (data[0 /* C3 */] <0.51229006f
        ? (data[0 /* C3 */] <0.41264677f
          ? (data[0 /* C3 */] <0.3771597f
            ? (data[0 /* C3 */] <0.35241792f ? 0.0744539f : -0.054112867f)
            : (data[2 /* C5 */] <0.77673435f ? 0.012789163f : 0.1404702f))
          : (data[2 /* C5 */] <0.7181875f
            ? (data[1 /* C4 */] <0.14257812f ? -0.12137496f : -0.03501325f)
            : (data[2 /* C5 */] <0.77768654f ? 0.05523019f : 3.6943372E-4f)))
        : (data[2 /* C5 */] <1.2590313f
          ? (data[2 /* C5 */] <1.2400445f
            ? (data[2 /* C5 */] <1.1840334f ? 0.1979254f : -0.067298405f)
            : 0.30511174f)
          : (data[2 /* C5 */] <1.7118386f
            ? (data[2 /* C5 */] <1.6312778f ? 0.020599412f : -0.05728337f)
            : (data[1 /* C4 */] <0.22015625f ? 0.026681608f : 0.14692925f)))));
    return pred;
  }
}


class gbm3_Forest_27 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_27_class_0.score0(fdata);
  }
}
class gbm3_Tree_27_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.112558596f
      ? (data[2 /* C5 */] <0.7988667f
        ? (data[0 /* C3 */] <0.356875f
          ? (data[2 /* C5 */] <0.41630077f
            ? (data[0 /* C3 */] <0.345625f ? -0.020186068f : 0.049774922f)
            : (data[1 /* C4 */] <0.107421875f ? -0.023615077f : -0.09012519f))
          : (data[1 /* C4 */] <0.102695316f
            ? -0.03573532f
            : (data[1 /* C4 */] <0.10748901f ? 0.07244271f : -0.0051637227f)))
        : -0.09430263f)
      : (data[1 /* C4 */] <0.16223834f
        ? (data[2 /* C5 */] <1.4810078f
          ? (data[0 /* C3 */] <0.5025586f
            ? (data[2 /* C5 */] <1.104289f ? 7.822075E-4f : -0.031178495f)
            : (data[2 /* C5 */] <1.163375f ? 0.17594561f : 0.004584621f))
          : 0.09276613f)
        : (data[2 /* C5 */] <0.6356074f
          ? -0.10550836f
          : (data[0 /* C3 */] <0.41144532f
            ? (data[2 /* C5 */] <0.84489065f ? 0.18581484f : 0.02986645f)
            : (data[2 /* C5 */] <0.94733596f ? -0.024540417f : 0.017556947f)))));
    return pred;
  }
}


class gbm3_Forest_28 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_28_class_0.score0(fdata);
  }
}
class gbm3_Tree_28_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.89813036f
      ? (data[0 /* C3 */] <0.27754393f
        ? (data[2 /* C5 */] <0.2365f
          ? (data[1 /* C4 */] <0.07765625f
            ? (data[0 /* C3 */] <0.16671875f ? -0.037653375f : -0.024571892f)
            : (data[1 /* C4 */] <0.092268065f ? -0.0054822257f : -0.035179053f))
          : (data[2 /* C5 */] <0.25621483f ? -0.08934948f : -0.033056613f))
        : (data[2 /* C5 */] <0.87f
          ? (data[2 /* C5 */] <0.8409766f
            ? (data[2 /* C5 */] <0.81866485f ? -0.0027799825f : -0.046179894f)
            : (data[1 /* C4 */] <0.14125f ? 0.10128843f : 0.0033085025f))
          : (data[0 /* C3 */] <0.43257812f
            ? (data[0 /* C3 */] <0.41742614f ? 0.0023573195f : -0.13027829f)
            : (data[1 /* C4 */] <0.1475f ? -0.07403462f : 3.550573E-4f))))
      : (data[0 /* C3 */] <0.3972412f
        ? -0.10402596f
        : (data[0 /* C3 */] <0.42291203f
          ? (data[2 /* C5 */] <1.1101563f
            ? (data[2 /* C5 */] <0.9414138f ? 0.08387683f : 0.3575985f)
            : -0.09534831f)
          : (data[1 /* C4 */] <0.16734375f
            ? (data[2 /* C5 */] <1.5615625f ? -0.002320719f : 0.093288414f)
            : (data[0 /* C3 */] <0.47246093f ? 0.069555745f : 0.010504695f)))));
    return pred;
  }
}


class gbm3_Forest_29 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_29_class_0.score0(fdata);
  }
}
class gbm3_Tree_29_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.1373877f
      ? (data[0 /* C3 */] <0.41234863f
        ? (data[2 /* C5 */] <0.77292967f
          ? (data[1 /* C4 */] <0.08753906f
            ? (data[0 /* C3 */] <0.3046094f ? -0.023447989f : 0.014544802f)
            : (data[2 /* C5 */] <0.15830469f ? -0.050069183f : -0.007431102f))
          : (data[2 /* C5 */] <0.8223039f ? -0.16842344f : 0.00988063f))
        : (data[0 /* C3 */] <0.4874832f
          ? (data[0 /* C3 */] <0.41754824f
            ? 0.07565651f
            : (data[2 /* C5 */] <0.85428125f ? -0.006195074f : 0.030035444f))
          : -0.08426902f))
      : (data[2 /* C5 */] <0.4486865f
        ? -0.10074101f
        : (data[0 /* C3 */] <0.35263672f
          ? (data[0 /* C3 */] <0.34745485f ? 0.059718575f : 0.21092583f)
          : (data[0 /* C3 */] <0.3770298f
            ? (data[2 /* C5 */] <0.71382815f ? -0.027850922f : -0.10052294f)
            : (data[0 /* C3 */] <0.3983556f ? 0.07442689f : 0.0064438456f)))));
    return pred;
  }
}


class gbm3_Forest_30 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_30_class_0.score0(fdata);
  }
}
class gbm3_Tree_30_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.8043814f
      ? (data[2 /* C5 */] <0.80124706f
        ? (data[1 /* C4 */] <0.14566407f
          ? (data[2 /* C5 */] <0.77554685f
            ? (data[0 /* C3 */] <0.30359375f ? -0.016738057f : -0.004590551f)
            : (data[0 /* C3 */] <0.42453125f ? -0.14353858f : -0.014728129f))
          : (data[2 /* C5 */] <0.76930857f
            ? (data[2 /* C5 */] <0.6815223f ? 0.044935968f : -0.021093875f)
            : (data[2 /* C5 */] <0.7900216f ? 0.18272904f : -0.052196853f)))
        : -0.13181427f)
      : (data[2 /* C5 */] <0.80832887f
        ? 0.15247972f
        : (data[0 /* C3 */] <0.37242186f
          ? -0.095626935f
          : (data[0 /* C3 */] <0.41687775f
            ? (data[2 /* C5 */] <0.99759376f ? 0.09906941f : -0.09569227f)
            : (data[0 /* C3 */] <0.5115837f ? 6.506334E-4f : 0.019016411f)))));
    return pred;
  }
}


class gbm3_Forest_31 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_31_class_0.score0(fdata);
  }
}
class gbm3_Tree_31_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.94224757f
      ? (data[0 /* C3 */] <0.34262207f
        ? (data[2 /* C5 */] <0.38754687f
          ? (data[2 /* C5 */] <0.37851062f
            ? (data[1 /* C4 */] <0.12625f ? -0.011154878f : -0.0858528f)
            : (data[1 /* C4 */] <0.10625f ? 0.0031063796f : 0.10488256f))
          : (data[2 /* C5 */] <0.43652683f
            ? (data[0 /* C3 */] <0.3221875f ? 0.0037374306f : -0.0720727f)
            : (data[0 /* C3 */] <0.3273828f ? -0.06345448f : 0.016098073f)))
        : (data[0 /* C3 */] <0.427766f
          ? (data[1 /* C4 */] <0.13742188f
            ? (data[0 /* C3 */] <0.4125f ? -0.007248115f : 0.025358167f)
            : (data[0 /* C3 */] <0.3525f ? 0.15698583f : 0.011002128f))
          : (data[0 /* C3 */] <0.43228063f
            ? (data[1 /* C4 */] <0.15734375f ? -0.05954413f : -5.87342E-4f)
            : (data[1 /* C4 */] <0.17265625f ? -0.0038997142f : -0.056635723f))))
      : (data[2 /* C5 */] <0.94960403f
        ? 0.19403352f
        : (data[0 /* C3 */] <0.44257814f
          ? (data[2 /* C5 */] <1.1404805f
            ? (data[1 /* C4 */] <0.15726562f ? 0.009131835f : 0.178835f)
            : -0.08463731f)
          : (data[1 /* C4 */] <0.19859375f
            ? (data[0 /* C3 */] <0.58273435f ? -4.992358E-5f : 0.18929933f)
            : (data[0 /* C3 */] <0.5971484f ? 0.0409021f : -0.093857646f)))));
    return pred;
  }
}


class gbm3_Forest_32 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_32_class_0.score0(fdata);
  }
}
class gbm3_Tree_32_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.89813036f
      ? (data[2 /* C5 */] <0.8701263f
        ? (data[2 /* C5 */] <0.8497796f
          ? (data[0 /* C3 */] <0.45308593f
            ? (data[2 /* C5 */] <0.82301563f ? -0.0049235667f : -0.054244593f)
            : (data[2 /* C5 */] <0.80977345f ? -0.03708634f : 0.15197378f))
          : (data[0 /* C3 */] <0.43796876f
            ? (data[2 /* C5 */] <0.85828125f ? 0.1712857f : 0.1220863f)
            : (data[1 /* C4 */] <0.151875f ? -0.07723734f : 0.077964984f)))
        : (data[0 /* C3 */] <0.43222657f
          ? (data[2 /* C5 */] <0.87425977f
            ? 0.022631856f
            : (data[2 /* C5 */] <0.88019484f ? -0.09520914f : -0.13287893f))
          : (data[1 /* C4 */] <0.1475f
            ? (data[2 /* C5 */] <0.87640625f ? -0.111316495f : -0.039982002f)
            : (data[0 /* C3 */] <0.44746095f ? 0.04357011f : -0.026651591f))))
      : (data[0 /* C3 */] <0.3972412f
        ? -0.087545894f
        : (data[0 /* C3 */] <0.42291203f
          ? (data[2 /* C5 */] <1.1101563f
            ? (data[2 /* C5 */] <0.9414138f ? 0.067340806f : 0.31066042f)
            : -0.07131514f)
          : (data[1 /* C4 */] <0.19859375f
            ? (data[0 /* C3 */] <0.58320314f ? 0.0025139519f : 0.17036937f)
            : (data[2 /* C5 */] <1.501375f ? 0.08282225f : 0.007954363f)))));
    return pred;
  }
}


class gbm3_Forest_33 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_33_class_0.score0(fdata);
  }
}
class gbm3_Tree_33_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.112558596f
      ? (data[2 /* C5 */] <0.7988667f
        ? (data[2 /* C5 */] <0.49692893f
          ? (data[2 /* C5 */] <0.48919567f
            ? (data[0 /* C3 */] <0.1915625f ? -0.025021719f : -0.009681433f)
            : -0.0922554f)
          : (data[2 /* C5 */] <0.5166231f
            ? 0.13925199f
            : (data[0 /* C3 */] <0.38710937f ? -0.06280208f : 0.032720704f)))
        : -0.08330986f)
      : (data[2 /* C5 */] <2.494621f
        ? (data[2 /* C5 */] <2.2011504f
          ? (data[2 /* C5 */] <2.1236837f
            ? (data[2 /* C5 */] <2.0343547f ? 0.0038694446f : -0.09521192f)
            : 0.09841912f)
          : (data[0 /* C3 */] <0.5765625f ? -0.13146809f : -0.04614565f))
        : 0.10155719f));
    return pred;
  }
}


class gbm3_Forest_34 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_34_class_0.score0(fdata);
  }
}
class gbm3_Tree_34_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.94224757f
      ? (data[1 /* C4 */] <0.14676757f
        ? (data[2 /* C5 */] <0.9273125f
          ? (data[0 /* C3 */] <0.4271289f
            ? (data[2 /* C5 */] <0.84028125f ? -0.006553935f : 0.117139794f)
            : (data[1 /* C4 */] <0.13707031f ? -0.003459777f : -0.042794336f))
          : -0.0605384f)
        : (data[2 /* C5 */] <0.82082814f
          ? (data[2 /* C5 */] <0.810215f
            ? (data[0 /* C3 */] <0.44183594f ? 0.028164396f : -0.08086504f)
            : 0.25170767f)
          : (data[2 /* C5 */] <0.83402663f
            ? -0.13321511f
            : (data[1 /* C4 */] <0.15265626f ? -0.06658657f : 0.018991409f))))
      : (data[2 /* C5 */] <0.94960403f
        ? 0.17179082f
        : (data[0 /* C3 */] <0.44257814f
          ? (data[2 /* C5 */] <1.1404805f
            ? (data[1 /* C4 */] <0.15726562f ? 0.0030185382f : 0.15805715f)
            : -0.0711058f)
          : (data[1 /* C4 */] <0.19859375f
            ? (data[0 /* C3 */] <0.58273435f ? -6.3486997E-4f : 0.15211995f)
            : (data[0 /* C3 */] <0.5971484f ? 0.03397509f : -0.089155264f)))));
    return pred;
  }
}


class gbm3_Forest_35 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_35_class_0.score0(fdata);
  }
}
class gbm3_Tree_35_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.89813036f
      ? (data[2 /* C5 */] <0.8666258f
        ? (data[2 /* C5 */] <0.84973854f
          ? (data[0 /* C3 */] <0.45308593f
            ? (data[2 /* C5 */] <0.82301563f ? -0.0037499731f : -0.045607902f)
            : (data[2 /* C5 */] <0.80977345f ? -0.030559363f : 0.13719375f))
          : (data[0 /* C3 */] <0.43796876f
            ? 0.15133719f
            : (data[1 /* C4 */] <0.151875f ? -0.05802434f : 0.10880718f)))
        : (data[1 /* C4 */] <0.16773437f
          ? (data[1 /* C4 */] <0.15768707f
            ? (data[1 /* C4 */] <0.13257839f ? -0.1001791f : -0.014241107f)
            : -0.111077674f)
          : 0.028948968f))
      : (data[0 /* C3 */] <0.3972412f
        ? -0.08129362f
        : (data[0 /* C3 */] <0.42291203f
          ? (data[2 /* C5 */] <1.1101563f
            ? (data[2 /* C5 */] <0.9414138f ? 0.058660414f : 0.27402955f)
            : -0.057459965f)
          : (data[2 /* C5 */] <0.91454685f
            ? (data[2 /* C5 */] <0.9057303f ? 0.008422069f : 0.08362504f)
            : (data[1 /* C4 */] <0.17125f ? -0.00373602f : 0.012884341f)))));
    return pred;
  }
}


class gbm3_Forest_36 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_36_class_0.score0(fdata);
  }
}
class gbm3_Tree_36_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.10262695f
      ? (data[0 /* C3 */] <0.3676074f
        ? (data[2 /* C5 */] <0.46650586f
          ? (data[2 /* C5 */] <0.2669135f
            ? (data[2 /* C5 */] <0.25863495f ? -0.009195609f : 0.08150861f)
            : (data[0 /* C3 */] <0.32625f ? -0.028800031f : 0.0066682594f))
          : 0.052797634f)
        : -0.077307284f)
      : (data[2 /* C5 */] <2.4449892f
        ? (data[2 /* C5 */] <2.1874454f
          ? (data[2 /* C5 */] <2.1086977f
            ? (data[2 /* C5 */] <1.9876229f ? 0.002954892f : -0.088162825f)
            : 0.1099015f)
          : (data[0 /* C3 */] <0.573125f ? -0.15659091f : -0.032519184f))
        : 0.08851667f));
    return pred;
  }
}


class gbm3_Forest_37 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_37_class_0.score0(fdata);
  }
}
class gbm3_Tree_37_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <1.7142984f
      ? (data[0 /* C3 */] <0.56226075f
        ? (data[0 /* C3 */] <0.5523533f
          ? (data[0 /* C3 */] <0.3425324f
            ? (data[0 /* C3 */] <0.333547f ? -0.0065390086f : -0.027489856f)
            : (data[2 /* C5 */] <1.6308906f ? 0.002135009f : -0.040782657f))
          : 0.104812756f)
        : (data[1 /* C4 */] <0.18980469f ? -0.05135904f : -0.15109165f))
      : (data[2 /* C5 */] <1.8477728f
        ? (data[2 /* C5 */] <1.7927309f
          ? (data[2 /* C5 */] <1.7356079f
            ? 0.21273181f
            : (data[2 /* C5 */] <1.7418305f ? -0.107264526f : 0.013654014f))
          : (data[2 /* C5 */] <1.816675f ? 0.36394814f : 0.07208451f))
        : (data[2 /* C5 */] <1.882146f
          ? -0.1814466f
          : (data[0 /* C3 */] <0.5479297f
            ? 0.18427607f
            : (data[0 /* C3 */] <0.5574988f ? -0.10221661f : 0.0026906703f)))));
    return pred;
  }
}


class gbm3_Forest_38 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_38_class_0.score0(fdata);
  }
}
class gbm3_Tree_38_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <1.5957334f
      ? (data[2 /* C5 */] <1.5801696f
        ? (data[0 /* C3 */] <0.51267576f
          ? (data[2 /* C5 */] <1.3211094f
            ? (data[2 /* C5 */] <1.3004984f ? -0.0019512761f : 0.09870799f)
            : (data[2 /* C5 */] <1.4058062f ? -0.061131958f : 0.009106189f))
          : (data[2 /* C5 */] <1.5183594f
            ? (data[1 /* C4 */] <0.1975f ? 0.02159213f : 0.12538235f)
            : (data[2 /* C5 */] <1.5645899f ? -0.06686619f : 0.11438241f)))
        : -0.17254308f)
      : (data[2 /* C5 */] <1.6329627f
        ? (data[2 /* C5 */] <1.6154921f
          ? (data[2 /* C5 */] <1.6065074f ? 0.15103859f : -0.022751227f)
          : 0.15940742f)
        : (data[1 /* C4 */] <0.22232422f
          ? (data[2 /* C5 */] <1.6731719f
            ? (data[1 /* C4 */] <0.18777344f ? -0.045145772f : -0.13356113f)
            : (data[2 /* C5 */] <1.8576397f ? 0.036126696f : -0.024606101f))
          : 0.13343595f)));
    return pred;
  }
}


class gbm3_Forest_39 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_39_class_0.score0(fdata);
  }
}
class gbm3_Tree_39_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.73269093f
      ? (data[1 /* C4 */] <0.16773437f
        ? (data[0 /* C3 */] <0.39773437f
          ? (data[1 /* C4 */] <0.13212891f
            ? (data[2 /* C5 */] <0.6754297f ? -0.007152562f : 0.15655485f)
            : (data[2 /* C5 */] <0.549875f ? -0.007251005f : 0.065252f))
          : (data[1 /* C4 */] <0.12246094f
            ? (data[2 /* C5 */] <0.64882815f ? 0.0052229147f : 0.13353968f)
            : (data[1 /* C4 */] <0.14738616f ? -0.0454603f : 0.016854798f)))
        : -0.091867976f)
      : (data[2 /* C5 */] <0.7531285f
        ? (data[2 /* C5 */] <0.7475067f
          ? (data[1 /* C4 */] <0.14251953f
            ? -0.025207637f
            : (data[2 /* C5 */] <0.74069923f ? 0.13247691f : 0.010581637f))
          : 0.11840894f)
        : (data[0 /* C3 */] <0.3770703f
          ? -0.067997895f
          : (data[0 /* C3 */] <0.3877316f
            ? 0.12598377f
            : (data[0 /* C3 */] <0.3959275f ? -0.15849021f : 0.0037617867f)))));
    return pred;
  }
}


class gbm3_Forest_40 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_40_class_0.score0(fdata);
  }
}
class gbm3_Tree_40_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <1.7142984f
      ? (data[2 /* C5 */] <1.6440674f
        ? (data[2 /* C5 */] <1.5927528f
          ? (data[2 /* C5 */] <1.5181863f
            ? (data[0 /* C3 */] <0.5147656f ? -0.0017446224f : 0.028704796f)
            : (data[1 /* C4 */] <0.19421875f ? -0.019301306f : -0.114938766f))
          : (data[1 /* C4 */] <0.18539062f
            ? (data[2 /* C5 */] <1.6153125f ? 0.038509917f : 0.20178983f)
            : (data[0 /* C3 */] <0.51730466f ? 0.08554594f : -0.055665746f)))
        : (data[2 /* C5 */] <1.6758343f
          ? (data[0 /* C3 */] <0.53753906f ? -0.09332866f : -0.120469265f)
          : (data[2 /* C5 */] <1.6891588f ? 0.07900846f : -0.06428724f)))
      : (data[2 /* C5 */] <1.7360015f
        ? 0.18746974f
        : (data[1 /* C4 */] <0.22232422f
          ? (data[2 /* C5 */] <1.8471016f
            ? (data[2 /* C5 */] <1.7952571f ? -0.03033788f : 0.17091785f)
            : (data[2 /* C5 */] <1.8850656f ? -0.15394007f : -0.008578295f))
          : 0.11244231f)));
    return pred;
  }
}


class gbm3_Forest_41 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_41_class_0.score0(fdata);
  }
}
class gbm3_Tree_41_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <2.4449892f
      ? (data[2 /* C5 */] <2.2040303f
        ? (data[2 /* C5 */] <1.7223362f
          ? (data[0 /* C3 */] <0.56203127f
            ? (data[0 /* C3 */] <0.5541089f ? -8.201136E-4f : 0.11409123f)
            : (data[2 /* C5 */] <1.5714453f ? -0.049989026f : -0.12069674f))
          : (data[2 /* C5 */] <1.8494812f
            ? (data[2 /* C5 */] <1.7926226f ? 0.01966784f : 0.15408282f)
            : (data[2 /* C5 */] <1.8824362f ? -0.14703819f : 0.012847152f)))
        : (data[1 /* C4 */] <0.211875f ? -0.12450573f : -0.0531547f))
      : 0.07536163f);
    return pred;
  }
}


class gbm3_Forest_42 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_42_class_0.score0(fdata);
  }
}
class gbm3_Tree_42_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.08772949f
      ? (data[2 /* C5 */] <0.25567383f
        ? (data[2 /* C5 */] <0.1793735f
          ? (data[2 /* C5 */] <0.1516589f
            ? (data[2 /* C5 */] <0.1306131f ? -0.009139123f : -0.0431581f)
            : (data[2 /* C5 */] <0.15956219f ? 0.09127172f : -0.0016767839f))
          : (data[2 /* C5 */] <0.20494725f
            ? (data[1 /* C4 */] <0.07734375f ? -0.017396823f : -0.06669843f)
            : (data[2 /* C5 */] <0.22074498f ? 0.031217568f : -0.045897823f)))
        : (data[1 /* C4 */] <0.08234375f ? 0.050573174f : -0.022482045f))
      : (data[1 /* C4 */] <0.2322631f
        ? (data[1 /* C4 */] <0.22226022f
          ? (data[2 /* C5 */] <2.148465f
            ? (data[2 /* C5 */] <2.1153638f ? 0.0012008254f : 0.1284053f)
            : (data[2 /* C5 */] <2.3908136f ? -0.11384334f : 0.056033127f))
          : (data[2 /* C5 */] <1.6898282f ? -0.0291641f : 0.1962587f))
        : -0.0587228f));
    return pred;
  }
}


class gbm3_Forest_43 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_43_class_0.score0(fdata);
  }
}
class gbm3_Tree_43_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <0.8043814f
      ? (data[2 /* C5 */] <0.80124706f
        ? (data[1 /* C4 */] <0.14566407f
          ? (data[2 /* C5 */] <0.76930857f
            ? (data[0 /* C3 */] <0.39765626f ? -0.0013116396f : -0.016143875f)
            : (data[0 /* C3 */] <0.41109374f ? -0.106698036f : -0.02313046f))
          : (data[2 /* C5 */] <0.77554685f
            ? (data[2 /* C5 */] <0.5463017f ? -0.06468631f : 0.012221693f)
            : (data[0 /* C3 */] <0.42003906f ? 0.27239782f : -0.03721166f)))
        : -0.11659351f)
      : (data[2 /* C5 */] <0.80832887f
        ? 0.13766675f
        : (data[0 /* C3 */] <0.41757813f
          ? (data[2 /* C5 */] <0.99759376f
            ? (data[2 /* C5 */] <0.923729f ? 0.02282146f : 0.19424224f)
            : -0.06798736f)
          : (data[0 /* C3 */] <0.4321045f
            ? (data[2 /* C5 */] <0.9660781f ? -0.045723245f : 0.07999708f)
            : (data[0 /* C3 */] <0.45763913f ? 0.01366005f : 1.6570705E-4f)))));
    return pred;
  }
}


class gbm3_Forest_44 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_44_class_0.score0(fdata);
  }
}
class gbm3_Tree_44_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.07724609f
      ? (data[2 /* C5 */] <0.20879932f
        ? (data[0 /* C3 */] <0.25265625f
          ? (data[0 /* C3 */] <0.24802369f
            ? (data[0 /* C3 */] <0.2374677f ? -0.013340205f : 0.0144989835f)
            : -0.074606895f)
          : 0.037954893f)
        : -0.048279855f)
      : (data[2 /* C5 */] <2.4449892f
        ? (data[2 /* C5 */] <2.1997168f
          ? (data[2 /* C5 */] <2.1149623f
            ? (data[2 /* C5 */] <1.9846522f ? 0.0013508731f : -0.08944364f)
            : 0.08011571f)
          : (data[2 /* C5 */] <2.2523859f ? -0.11719988f : -0.03826159f))
        : 0.06294965f));
    return pred;
  }
}


class gbm3_Forest_45 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_45_class_0.score0(fdata);
  }
}
class gbm3_Tree_45_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.1975293f
      ? (data[0 /* C3 */] <0.5825977f
        ? (data[2 /* C5 */] <1.8134687f
          ? (data[2 /* C5 */] <1.7851645f
            ? (data[0 /* C3 */] <0.53078127f ? -0.0014945829f : 0.019395014f)
            : 0.076804064f)
          : (data[0 /* C3 */] <0.5676953f
            ? (data[2 /* C5 */] <1.8685391f ? -0.16627666f : -0.058634628f)
            : 0.005206735f))
        : 0.13317308f)
      : (data[0 /* C3 */] <0.46754882f
        ? -0.12660414f
        : (data[0 /* C3 */] <0.5972602f
          ? (data[2 /* C5 */] <1.48575f
            ? (data[0 /* C3 */] <0.5178516f ? 0.03341013f : 0.211851f)
            : (data[2 /* C5 */] <1.590418f ? -0.082047865f : 0.036053378f))
          : -0.09337805f)));
    return pred;
  }
}


class gbm3_Forest_46 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_46_class_0.score0(fdata);
  }
}
class gbm3_Tree_46_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.21242675f
      ? (data[2 /* C5 */] <2.1471982f
        ? (data[2 /* C5 */] <2.1052997f
          ? (data[0 /* C3 */] <0.58351564f
            ? (data[0 /* C3 */] <0.55874145f ? -1.6842496E-4f : -0.030197637f)
            : 0.08475078f)
          : 0.12334461f)
        : (data[0 /* C3 */] <0.5772168f ? -0.13130209f : -0.004015007f))
      : (data[0 /* C3 */] <0.5425049f
        ? (data[2 /* C5 */] <1.3872285f
          ? -0.06324223f
          : (data[2 /* C5 */] <1.6142902f ? 0.11941692f : 0.21988489f))
        : (data[2 /* C5 */] <1.9015195f
          ? 0.08844824f
          : (data[2 /* C5 */] <2.2155285f
            ? (data[2 /* C5 */] <2.0356054f ? -0.061438125f : -0.11870643f)
            : 0.02073852f))));
    return pred;
  }
}


class gbm3_Forest_47 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_47_class_0.score0(fdata);
  }
}
class gbm3_Tree_47_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C5 */] <1.7253276f
      ? (data[2 /* C5 */] <1.6445466f
        ? (data[2 /* C5 */] <1.593217f
          ? (data[2 /* C5 */] <1.5186287f
            ? (data[0 /* C3 */] <0.5147656f ? -0.0012839483f : 0.023967925f)
            : (data[0 /* C3 */] <0.53984374f ? -0.07289037f : 0.008006648f))
          : (data[0 /* C3 */] <0.53148437f
            ? (data[0 /* C3 */] <0.51736325f ? 0.08552357f : -0.0903337f)
            : 0.12160249f))
        : (data[2 /* C5 */] <1.6757383f
          ? (data[1 /* C4 */] <0.18742187f ? -0.10020278f : -0.11826082f)
          : (data[2 /* C5 */] <1.689312f ? 0.06928886f : -0.048505746f)))
      : (data[2 /* C5 */] <1.8478078f
        ? (data[2 /* C5 */] <1.7976425f
          ? (data[2 /* C5 */] <1.7457901f
            ? 0.10384583f
            : (data[0 /* C3 */] <0.5367187f ? 0.02739688f : -0.05212394f))
          : (data[2 /* C5 */] <1.8216895f ? 0.25159714f : 0.058101185f))
        : (data[0 /* C3 */] <0.5426367f
          ? 0.11058297f
          : (data[0 /* C3 */] <0.5573153f
            ? (data[2 /* C5 */] <1.979125f ? -0.04979367f : -0.14951012f)
            : (data[2 /* C5 */] <2.44425f ? -0.011503313f : 0.05946249f)))));
    return pred;
  }
}


class gbm3_Forest_48 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_48_class_0.score0(fdata);
  }
}
class gbm3_Tree_48_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.10262695f
      ? (data[0 /* C3 */] <0.3676074f
        ? (data[2 /* C5 */] <0.46650586f
          ? (data[2 /* C5 */] <0.2669135f
            ? (data[1 /* C4 */] <0.096875f ? -0.0059608375f : 0.040870216f)
            : (data[0 /* C3 */] <0.32625f ? -0.023917416f : 0.008388764f))
          : 0.04844442f)
        : -0.07091009f)
      : (data[2 /* C5 */] <0.22810058f
        ? -0.07070574f
        : (data[2 /* C5 */] <0.29912323f
          ? (data[2 /* C5 */] <0.2701728f
            ? 0.0044597406f
            : (data[0 /* C3 */] <0.30242187f ? 0.06254112f : 0.13134526f))
          : (data[2 /* C5 */] <0.33859786f
            ? (data[2 /* C5 */] <0.31752166f ? 0.010882112f : -0.06276847f)
            : (data[0 /* C3 */] <0.31875f ? 0.04872559f : 0.001163757f)))));
    return pred;
  }
}


class gbm3_Forest_49 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm3_Tree_49_class_0.score0(fdata);
  }
}
class gbm3_Tree_49_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C4 */] <0.21242675f
      ? (data[2 /* C5 */] <2.1471982f
        ? (data[2 /* C5 */] <2.1052997f
          ? (data[0 /* C3 */] <0.58351564f
            ? (data[0 /* C3 */] <0.55874145f ? -1.6698184E-4f : -0.027443314f)
            : 0.074449115f)
          : 0.11480428f)
        : (data[0 /* C3 */] <0.5772168f ? -0.115087435f : -0.006127825f))
      : (data[0 /* C3 */] <0.5425049f
        ? (data[2 /* C5 */] <1.3872285f
          ? -0.05708638f
          : (data[2 /* C5 */] <1.6142902f ? 0.10915893f : 0.19183423f))
        : (data[2 /* C5 */] <1.9015195f
          ? 0.08267272f
          : (data[2 /* C5 */] <2.2155285f
            ? (data[0 /* C3 */] <0.57289064f ? -0.053586572f : -0.10682358f)
            : 0.017643008f))));
    return pred;
  }
}


