package ai.h2o.hive.udf.models;
/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2016-03-16T13:29:14.178-07:00
  3.8.1.3
  
  Standalone prediction code with sample test data for GBMModel named gbm4

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/gbm4 > gbm4.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m gbm4.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="gbm4", algorithm="gbm")
public class gbm4 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 3; }
  public int nclasses() { return 1; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_gbm4.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* C4 */ null,
    /* C5 */ null,
    /* C6 */ null,
    /* C9 */ null
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {1.0};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {1.0};

  public gbm4() { super(NAMES,DOMAINS); }
  public String getUUID() { return Long.toString(-8565762285252878800L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    double[] fdata = hex.genmodel.GenModel.SharedTree_clean(data);
    gbm4_Forest_0.score0(fdata,preds);
    gbm4_Forest_1.score0(fdata,preds);
    gbm4_Forest_2.score0(fdata,preds);
    gbm4_Forest_3.score0(fdata,preds);
    gbm4_Forest_4.score0(fdata,preds);
    gbm4_Forest_5.score0(fdata,preds);
    gbm4_Forest_6.score0(fdata,preds);
    gbm4_Forest_7.score0(fdata,preds);
    gbm4_Forest_8.score0(fdata,preds);
    gbm4_Forest_9.score0(fdata,preds);
    gbm4_Forest_10.score0(fdata,preds);
    gbm4_Forest_11.score0(fdata,preds);
    gbm4_Forest_12.score0(fdata,preds);
    gbm4_Forest_13.score0(fdata,preds);
    gbm4_Forest_14.score0(fdata,preds);
    gbm4_Forest_15.score0(fdata,preds);
    gbm4_Forest_16.score0(fdata,preds);
    gbm4_Forest_17.score0(fdata,preds);
    gbm4_Forest_18.score0(fdata,preds);
    gbm4_Forest_19.score0(fdata,preds);
    gbm4_Forest_20.score0(fdata,preds);
    gbm4_Forest_21.score0(fdata,preds);
    gbm4_Forest_22.score0(fdata,preds);
    gbm4_Forest_23.score0(fdata,preds);
    gbm4_Forest_24.score0(fdata,preds);
    gbm4_Forest_25.score0(fdata,preds);
    gbm4_Forest_26.score0(fdata,preds);
    gbm4_Forest_27.score0(fdata,preds);
    gbm4_Forest_28.score0(fdata,preds);
    gbm4_Forest_29.score0(fdata,preds);
    gbm4_Forest_30.score0(fdata,preds);
    gbm4_Forest_31.score0(fdata,preds);
    gbm4_Forest_32.score0(fdata,preds);
    gbm4_Forest_33.score0(fdata,preds);
    gbm4_Forest_34.score0(fdata,preds);
    gbm4_Forest_35.score0(fdata,preds);
    gbm4_Forest_36.score0(fdata,preds);
    gbm4_Forest_37.score0(fdata,preds);
    gbm4_Forest_38.score0(fdata,preds);
    gbm4_Forest_39.score0(fdata,preds);
    gbm4_Forest_40.score0(fdata,preds);
    gbm4_Forest_41.score0(fdata,preds);
    gbm4_Forest_42.score0(fdata,preds);
    gbm4_Forest_43.score0(fdata,preds);
    gbm4_Forest_44.score0(fdata,preds);
    gbm4_Forest_45.score0(fdata,preds);
    gbm4_Forest_46.score0(fdata,preds);
    gbm4_Forest_47.score0(fdata,preds);
    gbm4_Forest_48.score0(fdata,preds);
    gbm4_Forest_49.score0(fdata,preds);
    preds[0] += 9.933684462532918;
    preds[0] = preds[0];
    return preds;
  }
}
// The class representing training column names
class NamesHolder_gbm4 implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    NamesHolder_gbm4_0.fill(VALUES);
  }
  static final class NamesHolder_gbm4_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "C4";
      sa[1] = "C5";
      sa[2] = "C6";
    }
  }
}

class gbm4_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_0_class_0.score0(fdata);
  }
}
class gbm4_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.122490235f
      ? (data[1 /* C5 */] <0.1508955f
        ? (data[1 /* C5 */] <0.07441207f
          ? (data[1 /* C5 */] <0.023497334f
            ? -0.66003513f
            : (data[1 /* C5 */] <0.042435832f ? -0.56479704f : -0.51211846f))
          : (data[1 /* C5 */] <0.119882934f
            ? (data[0 /* C4 */] <0.0625f ? -0.4725351f : -0.411424f)
            : (data[2 /* C6 */] <0.05578125f ? -0.30336845f : -0.39849666f)))
        : (data[0 /* C4 */] <0.10242187f
          ? (data[1 /* C5 */] <0.4259414f
            ? (data[2 /* C6 */] <0.062109374f ? -0.09336845f : -0.2707311f)
            : (data[0 /* C4 */] <0.096875f ? -0.05700481f : -0.17114621f))
          : (data[1 /* C5 */] <0.6458945f
            ? (data[2 /* C6 */] <0.23117188f ? -0.12896627f : -0.192562f)
            : (data[2 /* C6 */] <0.28879687f ? 0.29663157f : 0.031121355f))))
      : (data[0 /* C4 */] <0.16282998f
        ? (data[0 /* C4 */] <0.13748685f
          ? (data[1 /* C5 */] <0.8065625f
            ? (data[2 /* C6 */] <0.22857031f ? 0.036236823f : -0.07732749f)
            : (data[2 /* C6 */] <0.35135937f ? 0.3274649f : 0.006631556f))
          : (data[2 /* C6 */] <0.32721874f
            ? (data[1 /* C5 */] <0.781125f ? 0.1142265f : 0.3971976f)
            : (data[1 /* C5 */] <0.9083125f ? -0.04209726f : 0.060259875f)))
        : (data[2 /* C6 */] <0.4451875f
          ? (data[1 /* C5 */] <1.0316328f
            ? (data[2 /* C6 */] <0.39890626f ? 0.29152367f : 0.03243801f)
            : (data[2 /* C6 */] <0.39890626f ? 0.67935884f : 0.40663156f))
          : (data[1 /* C5 */] <1.2959921f
            ? (data[2 /* C6 */] <0.49484375f ? 0.15145914f : 0.038237773f)
            : (data[2 /* C6 */] <0.55996877f ? 0.48317477f : 0.18830125f)))));
    return pred;
  }
}


class gbm4_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_1_class_0.score0(fdata);
  }
}
class gbm4_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.122490235f
      ? (data[1 /* C5 */] <0.1508955f
        ? (data[1 /* C5 */] <0.07964668f
          ? (data[1 /* C5 */] <0.023231514f
            ? -0.5940316f
            : (data[1 /* C5 */] <0.042401932f ? -0.5083173f : -0.457855f))
          : (data[1 /* C5 */] <0.11977006f
            ? (data[0 /* C4 */] <0.0625f ? -0.4223054f : -0.36936894f)
            : (data[2 /* C6 */] <0.048460938f ? -0.21303158f : -0.3397943f)))
        : (data[0 /* C4 */] <0.10242187f
          ? (data[1 /* C5 */] <0.43379688f
            ? (data[2 /* C6 */] <0.062109374f ? -0.08403158f : -0.24326631f)
            : (data[1 /* C5 */] <0.51284254f ? -0.15353134f : -0.06767516f))
          : (data[1 /* C5 */] <0.6301836f
            ? (data[2 /* C6 */] <0.23117188f ? -0.11872317f : -0.17411223f)
            : (data[2 /* C6 */] <0.30320314f ? 0.18908162f : 0.0011678087f))))
      : (data[0 /* C4 */] <0.16282998f
        ? (data[0 /* C4 */] <0.13748685f
          ? (data[1 /* C5 */] <0.8065625f
            ? (data[2 /* C6 */] <0.22857031f ? 0.03261315f : -0.06959471f)
            : (data[2 /* C6 */] <0.39858595f ? 0.18313505f : -0.06130435f))
          : (data[2 /* C6 */] <0.32721874f
            ? (data[1 /* C5 */] <0.781125f ? 0.10280387f : 0.35747784f)
            : (data[1 /* C5 */] <0.93375f ? -0.03087964f : 0.058076847f)))
        : (data[2 /* C6 */] <0.4451875f
          ? (data[1 /* C5 */] <1.0316328f
            ? (data[2 /* C6 */] <0.39890626f ? 0.26237127f : 0.02919419f)
            : (data[2 /* C6 */] <0.39890626f ? 0.611423f : 0.36596844f))
          : (data[0 /* C4 */] <0.18007812f
            ? (data[1 /* C5 */] <1.146711f ? 7.255692E-4f : 0.1225298f)
            : (data[0 /* C4 */] <0.21147704f ? 0.20238584f : 0.36389083f)))));
    return pred;
  }
}


class gbm4_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_2_class_0.score0(fdata);
  }
}
class gbm4_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.122490235f
      ? (data[1 /* C5 */] <0.1508955f
        ? (data[1 /* C5 */] <0.07441207f
          ? (data[1 /* C5 */] <0.023497334f
            ? -0.53462845f
            : (data[1 /* C5 */] <0.05663971f ? -0.4479894f : -0.40351394f))
          : (data[1 /* C5 */] <0.119882934f
            ? (data[0 /* C4 */] <0.0625f ? -0.38260671f : -0.33309898f)
            : (data[2 /* C6 */] <0.05578125f ? -0.24327758f : -0.32466757f)))
        : (data[1 /* C5 */] <0.60656005f
          ? (data[0 /* C4 */] <0.0975f
            ? (data[1 /* C5 */] <0.37875f ? -0.2302349f : -0.045820463f)
            : (data[2 /* C6 */] <0.2270078f ? -0.122641705f : -0.17777276f))
          : (data[2 /* C6 */] <0.26641798f
            ? 0.20859319f
            : (data[1 /* C5 */] <0.6765625f ? -0.13972792f : 0.083184175f))))
      : (data[0 /* C4 */] <0.1579105f
        ? (data[0 /* C4 */] <0.13746999f
          ? (data[1 /* C5 */] <0.832f
            ? (data[2 /* C6 */] <0.22857031f ? 0.029351871f : -0.057091933f)
            : (data[2 /* C6 */] <0.39858595f ? 0.2074417f : -0.04831788f))
          : (data[2 /* C6 */] <0.28401563f
            ? (data[1 /* C5 */] <0.73025f ? 0.11080264f : 0.3486284f)
            : (data[1 /* C5 */] <0.7556875f ? -0.0722317f : 0.028811175f)))
        : (data[0 /* C4 */] <0.19208552f
          ? (data[2 /* C6 */] <0.4426875f
            ? (data[1 /* C5 */] <0.94759375f ? 0.15724689f : 0.32609534f)
            : (data[1 /* C5 */] <1.2203437f ? 0.018759254f : 0.13595009f))
          : (data[2 /* C6 */] <0.5890313f
            ? (data[1 /* C5 */] <1.3959453f ? 0.32379714f : 0.59454757f)
            : (data[1 /* C5 */] <1.6748828f ? 0.079558395f : 0.25405416f)))));
    return pred;
  }
}


class gbm4_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_3_class_0.score0(fdata);
  }
}
class gbm4_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.5727661f
      ? (data[1 /* C5 */] <0.19485652f
        ? (data[1 /* C5 */] <0.09541488f
          ? (data[1 /* C5 */] <0.0414094f
            ? (data[2 /* C6 */] <0.0071171876f ? -0.4991143f : -0.41668448f)
            : (data[1 /* C5 */] <0.06653f ? -0.38050652f : -0.33953908f))
          : (data[1 /* C5 */] <0.15192436f
            ? (data[0 /* C4 */] <0.077109374f ? -0.2928198f : -0.25351092f)
            : (data[2 /* C6 */] <0.0628125f ? -0.08145033f : -0.2474971f)))
        : (data[0 /* C4 */] <0.10265625f
          ? (data[2 /* C6 */] <0.07539844f
            ? -0.06400038f
            : (data[0 /* C4 */] <0.0921875f ? -0.21153203f : -0.16452369f))
          : (data[2 /* C6 */] <0.23291406f
            ? (data[1 /* C5 */] <0.47328907f ? -0.10104761f : 0.026144052f)
            : (data[1 /* C5 */] <0.53748435f ? -0.2007895f : -0.15748161f))))
      : (data[0 /* C4 */] <0.1622168f
        ? (data[2 /* C6 */] <0.25151563f
          ? (data[1 /* C5 */] <0.6727266f
            ? (data[2 /* C6 */] <0.23257813f ? 0.261304f : 0.05782026f)
            : (data[2 /* C6 */] <0.2406875f ? 0.34794462f : 0.5246684f))
          : (data[1 /* C5 */] <0.8023711f
            ? (data[0 /* C4 */] <0.15207031f ? -0.0561881f : 0.11634008f)
            : (data[2 /* C6 */] <0.3281875f ? 0.31366047f : 0.029394893f)))
        : (data[2 /* C6 */] <0.4021797f
          ? (data[1 /* C5 */] <1.0124062f
            ? (data[2 /* C6 */] <0.26475f ? 0.38105842f : 0.19224595f)
            : (data[2 /* C6 */] <0.3753125f ? 0.37918362f : 0.5733938f))
          : (data[0 /* C4 */] <0.19515625f
            ? (data[1 /* C5 */] <1.2013125f ? 0.05112775f : 0.12994337f)
            : (data[2 /* C6 */] <0.5721094f ? 0.44029075f : 0.18907546f)))));
    return pred;
  }
}


class gbm4_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_4_class_0.score0(fdata);
  }
}
class gbm4_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.47350243f
      ? (data[1 /* C5 */] <0.15118632f
        ? (data[1 /* C5 */] <0.079506956f
          ? (data[1 /* C5 */] <0.02319331f
            ? -0.43354383f
            : (data[1 /* C5 */] <0.042376857f ? -0.3712249f : -0.33384177f))
          : (data[1 /* C5 */] <0.11972179f
            ? (data[0 /* C4 */] <0.0625f ? -0.30986255f : -0.26943555f)
            : (data[2 /* C6 */] <0.048460938f ? -0.14087032f : -0.24996956f)))
        : (data[0 /* C4 */] <0.10265625f
          ? (data[2 /* C6 */] <0.06448047f
            ? (data[2 /* C6 */] <0.060765993f ? -0.07234622f : -0.014658108f)
            : (data[1 /* C5 */] <0.18145312f ? -0.24877019f : -0.16884333f))
          : (data[2 /* C6 */] <0.16878906f
            ? (data[1 /* C5 */] <0.3784375f ? -0.09956909f : 0.021351825f)
            : (data[1 /* C5 */] <0.434875f ? -0.202206f : -0.09258788f))))
      : (data[0 /* C4 */] <0.15780273f
        ? (data[2 /* C6 */] <0.21675f
          ? (data[1 /* C5 */] <0.60295314f
            ? (data[2 /* C6 */] <0.18745312f ? 0.17249094f : 0.040377777f)
            : (data[2 /* C6 */] <0.20461719f ? 0.39151162f : 0.31202894f))
          : (data[1 /* C5 */] <0.58146095f
            ? (data[2 /* C6 */] <0.22750781f ? -0.046105355f : -0.1326381f)
            : (data[2 /* C6 */] <0.24752344f ? 0.20094693f : 0.007113942f)))
        : (data[2 /* C6 */] <0.44451562f
          ? (data[1 /* C5 */] <0.93810546f
            ? (data[2 /* C6 */] <0.3594453f ? 0.1810441f : -0.049768418f)
            : (data[1 /* C5 */] <1.1657658f ? 0.2645936f : 0.5354641f))
          : (data[1 /* C5 */] <1.4145352f
            ? (data[2 /* C6 */] <0.575375f ? 0.08350027f : -0.011538783f)
            : (data[2 /* C6 */] <0.5590781f ? 0.5524548f : 0.14521235f)))));
    return pred;
  }
}


class gbm4_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_5_class_0.score0(fdata);
  }
}
class gbm4_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.12745605f
      ? (data[0 /* C4 */] <0.09745907f
        ? (data[1 /* C5 */] <0.11248437f
          ? (data[1 /* C5 */] <0.057242185f
            ? (data[1 /* C5 */] <0.018400023f ? -0.40525335f : -0.32969815f)
            : (data[0 /* C4 */] <0.06777344f ? -0.28188094f : -0.24140407f))
          : (data[1 /* C5 */] <0.43058288f
            ? (data[0 /* C4 */] <0.08238281f ? -0.20653506f : -0.16045664f)
            : -0.01518096f))
        : (data[1 /* C5 */] <0.6510957f
          ? (data[2 /* C6 */] <0.19315626f
            ? (data[1 /* C5 */] <0.43385938f ? -0.09879434f : 0.061393768f)
            : (data[1 /* C5 */] <0.48396876f ? -0.15752645f : -0.096098654f))
          : (data[2 /* C6 */] <0.301f
            ? (data[1 /* C5 */] <0.7506875f ? 0.08225709f : 0.3537167f)
            : (data[1 /* C5 */] <0.94079685f ? -0.04104253f : 0.23906413f))))
      : (data[0 /* C4 */] <0.1724922f
        ? (data[2 /* C6 */] <0.30255273f
          ? (data[1 /* C5 */] <0.7684141f
            ? (data[1 /* C5 */] <0.5718668f ? -0.0026237883f : 0.09665467f)
            : (data[0 /* C4 */] <0.1471875f ? 0.24805273f : 0.3542174f))
          : (data[1 /* C5 */] <0.8525547f
            ? (data[1 /* C5 */] <0.6972739f ? -0.1516285f : -0.037062775f)
            : (data[2 /* C6 */] <0.399125f ? 0.16301683f : 0.019300874f)))
        : (data[2 /* C6 */] <0.53745705f
          ? (data[1 /* C5 */] <1.2979296f
            ? (data[2 /* C6 */] <0.40417188f ? 0.2507184f : 0.092288435f)
            : (data[2 /* C6 */] <0.5240156f ? 0.38671955f : 0.6425227f))
          : (data[1 /* C5 */] <1.6705078f
            ? (data[2 /* C6 */] <0.6279687f ? 0.10044915f : 0.018012505f)
            : (data[2 /* C6 */] <0.76142186f ? 0.4115845f : 0.08356847f)))));
    return pred;
  }
}


class gbm4_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_6_class_0.score0(fdata);
  }
}
class gbm4_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.12745605f
      ? (data[0 /* C4 */] <0.09745907f
        ? (data[1 /* C5 */] <0.11248437f
          ? (data[1 /* C5 */] <0.06673694f
            ? (data[1 /* C5 */] <0.023241807f ? -0.35218266f : -0.28944653f)
            : (data[0 /* C4 */] <0.06777344f ? -0.24922273f : -0.21621044f))
          : (data[1 /* C5 */] <0.37348828f
            ? (data[0 /* C4 */] <0.08238281f ? -0.18710303f : -0.14569971f)
            : -0.051354583f))
        : (data[1 /* C5 */] <0.70173436f
          ? (data[0 /* C4 */] <0.1125f
            ? (data[2 /* C6 */] <0.22233593f ? -0.0930338f : -0.14089558f)
            : (data[2 /* C6 */] <0.12061719f ? 0.15527648f : -0.070001975f))
          : (data[2 /* C6 */] <0.40114063f
            ? (data[1 /* C5 */] <0.9038672f ? 0.0732719f : 0.43178684f)
            : (data[1 /* C5 */] <0.8739609f ? -0.18079638f : -0.030345626f))))
      : (data[0 /* C4 */] <0.18228267f
        ? (data[0 /* C4 */] <0.15246521f
          ? (data[2 /* C6 */] <0.30625f
            ? (data[1 /* C5 */] <0.7346875f ? 0.035532195f : 0.252338f)
            : (data[1 /* C5 */] <0.7835625f ? -0.09903101f : 0.004351709f))
          : (data[2 /* C6 */] <0.44171876f
            ? (data[1 /* C5 */] <0.9389375f ? 0.086505786f : 0.23300333f)
            : (data[1 /* C5 */] <1.4781562f ? 0.020625409f : 0.12694936f)))
        : (data[2 /* C6 */] <0.5866231f
          ? (data[1 /* C5 */] <1.3959453f
            ? (data[2 /* C6 */] <0.4912969f ? 0.24844863f : 0.089856066f)
            : (data[2 /* C6 */] <0.55360156f ? 0.5705441f : 0.34539598f))
          : (data[1 /* C5 */] <1.7969179f
            ? (data[2 /* C6 */] <0.699625f ? 0.09682296f : 0.0052138367f)
            : (data[2 /* C6 */] <0.7559375f ? 0.6017495f : 0.09614805f)))));
    return pred;
  }
}


class gbm4_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_7_class_0.score0(fdata);
  }
}
class gbm4_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.47350243f
      ? (data[1 /* C5 */] <0.15118632f
        ? (data[1 /* C5 */] <0.08358627f
          ? (data[1 /* C5 */] <0.02303396f
            ? -0.31696436f
            : (data[1 /* C5 */] <0.0419296f ? -0.27327994f : -0.24177277f))
          : (data[2 /* C6 */] <0.058890626f
            ? (data[1 /* C5 */] <0.11959375f ? -0.19721285f : -0.1538421f)
            : (data[0 /* C4 */] <0.07734375f ? -0.24208511f : -0.20533793f)))
        : (data[1 /* C5 */] <0.34447658f
          ? (data[2 /* C6 */] <0.06448047f
            ? (data[2 /* C6 */] <0.060765993f ? -0.028372165f : 0.021797428f)
            : (data[1 /* C5 */] <0.16954687f ? -0.23648831f : -0.12523669f))
          : (data[2 /* C6 */] <0.14695702f
            ? (data[2 /* C6 */] <0.12598406f ? 0.32200038f : 0.060763318f)
            : (data[0 /* C4 */] <0.12234375f ? -0.1085991f : -0.02623354f))))
      : (data[0 /* C4 */] <0.15228516f
        ? (data[2 /* C6 */] <0.21675f
          ? (data[1 /* C5 */] <0.58670706f
            ? (data[2 /* C6 */] <0.195375f ? 0.12943672f : 0.024680024f)
            : (data[1 /* C5 */] <0.649311f ? 0.23836273f : 0.32802564f))
          : (data[1 /* C5 */] <0.6481836f
            ? (data[2 /* C6 */] <0.27051562f ? -0.035500433f : -0.12822652f)
            : (data[2 /* C6 */] <0.3058594f ? 0.11930392f : -0.012666226f)))
        : (data[2 /* C6 */] <0.40214062f
          ? (data[1 /* C5 */] <0.93810546f
            ? (data[2 /* C6 */] <0.363875f ? 0.12832867f : -0.03456101f)
            : (data[0 /* C4 */] <0.18546875f ? 0.2866771f : 0.4615207f))
          : (data[1 /* C5 */] <1.2129687f
            ? (data[1 /* C5 */] <0.9186631f ? -0.13796715f : 0.019560339f)
            : (data[2 /* C6 */] <0.5381875f ? 0.27543658f : 0.072859034f)))));
    return pred;
  }
}


class gbm4_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_8_class_0.score0(fdata);
  }
}
class gbm4_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.5727661f
      ? (data[1 /* C5 */] <0.22384074f
        ? (data[1 /* C5 */] <0.097322196f
          ? (data[1 /* C5 */] <0.041469347f
            ? (data[2 /* C6 */] <0.0071171876f ? -0.29957083f : -0.24623199f)
            : (data[2 /* C6 */] <0.037703127f ? -0.20567024f : -0.24638346f))
          : (data[0 /* C4 */] <0.07765625f
            ? (data[1 /* C5 */] <0.105375f ? -0.12852967f : -0.16904013f)
            : (data[2 /* C6 */] <0.07721875f ? -0.10907145f : -0.1494551f)))
        : (data[0 /* C4 */] <0.1321875f
          ? (data[0 /* C4 */] <0.10223877f
            ? (data[2 /* C6 */] <0.09473438f ? 0.0020179243f : -0.10973186f)
            : (data[2 /* C6 */] <0.20367187f ? -0.033916898f : -0.102539994f))
          : (data[2 /* C6 */] <0.23431055f
            ? (data[1 /* C5 */] <0.52054685f ? -0.01031884f : 0.11789071f)
            : -0.16107017f)))
      : (data[0 /* C4 */] <0.17325196f
        ? (data[2 /* C6 */] <0.25151563f
          ? (data[1 /* C5 */] <0.66321874f
            ? (data[2 /* C6 */] <0.23257813f ? 0.19894876f : 0.04198083f)
            : (data[2 /* C6 */] <0.2406875f ? 0.22593519f : 0.4029942f))
          : (data[1 /* C5 */] <0.7083281f
            ? (data[2 /* C6 */] <0.278f ? 0.009490114f : -0.08853119f)
            : (data[2 /* C6 */] <0.31625f ? 0.15720613f : 0.016509628f)))
        : (data[2 /* C6 */] <0.5372578f
          ? (data[1 /* C5 */] <1.2913438f
            ? (data[2 /* C6 */] <0.4060625f ? 0.20645818f : 0.05779406f)
            : (data[2 /* C6 */] <0.5241875f ? 0.2830766f : 0.5274452f))
          : (data[1 /* C5 */] <1.6748828f
            ? (data[1 /* C5 */] <1.4602802f ? 0.0041875597f : 0.07687434f)
            : (data[2 /* C6 */] <0.76142186f ? 0.3409026f : 0.059590712f)))));
    return pred;
  }
}


class gbm4_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_9_class_0.score0(fdata);
  }
}
class gbm4_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.47350243f
      ? (data[1 /* C5 */] <0.15118632f
        ? (data[1 /* C5 */] <0.074553505f
          ? (data[1 /* C5 */] <0.01787108f
            ? -0.27383593f
            : (data[2 /* C6 */] <0.02740625f ? -0.2055611f : -0.25224897f))
          : (data[2 /* C6 */] <0.058890626f
            ? (data[1 /* C5 */] <0.1236875f ? -0.16229823f : -0.12230469f)
            : (data[0 /* C4 */] <0.07734375f ? -0.20097259f : -0.17288741f)))
        : (data[0 /* C4 */] <0.1125f
          ? (data[2 /* C6 */] <0.06448047f
            ? (data[2 /* C6 */] <0.060765993f ? -0.01222909f : 0.032323923f)
            : (data[1 /* C5 */] <0.1965f ? -0.1441473f : -0.090901084f))
          : (data[2 /* C6 */] <0.16151172f
            ? (data[1 /* C5 */] <0.34922656f ? -0.06346199f : 0.07659024f)
            : (data[1 /* C5 */] <0.43273437f ? -0.14838338f : -0.030023687f))))
      : (data[0 /* C4 */] <0.15228516f
        ? (data[2 /* C6 */] <0.23264062f
          ? (data[1 /* C5 */] <0.56621486f
            ? (data[2 /* C6 */] <0.1945f ? 0.11303661f : -9.5961214E-4f)
            : (data[1 /* C5 */] <0.5794202f ? 0.08893793f : 0.22146194f))
          : (data[1 /* C5 */] <0.6174453f
            ? (data[1 /* C5 */] <0.55731297f ? -0.12268068f : -0.06688466f)
            : (data[2 /* C6 */] <0.24159375f ? 0.31557965f : -0.0010201029f)))
        : (data[2 /* C6 */] <0.40214062f
          ? (data[1 /* C5 */] <0.93810546f
            ? (data[2 /* C6 */] <0.363875f ? 0.104812205f : -0.034809384f)
            : (data[1 /* C5 */] <0.9994467f ? 0.2058282f : 0.3245958f))
          : (data[0 /* C4 */] <0.18546875f
            ? (data[1 /* C5 */] <1.56175f ? 0.0215679f : 0.1327102f)
            : (data[2 /* C6 */] <0.5890703f ? 0.21028541f : 0.081297465f)))));
    return pred;
  }
}


class gbm4_Forest_10 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_10_class_0.score0(fdata);
  }
}
class gbm4_Tree_10_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.49280372f
      ? (data[1 /* C5 */] <0.15154175f
        ? (data[1 /* C5 */] <0.06684037f
          ? (data[1 /* C5 */] <0.018463375f
            ? -0.24205498f
            : (data[2 /* C6 */] <0.02303125f ? -0.18220459f : -0.24156485f))
          : (data[1 /* C5 */] <0.09726492f
            ? (data[2 /* C6 */] <0.031851564f ? -0.14429304f : -0.17705745f)
            : (data[2 /* C6 */] <0.05390625f ? -0.11736002f : -0.15567668f)))
        : (data[1 /* C5 */] <0.33667144f
          ? (data[2 /* C6 */] <0.06448047f
            ? 0.017716518f
            : (data[0 /* C4 */] <0.08222656f ? -0.13897091f : -0.08946587f))
          : (data[2 /* C6 */] <0.14695702f
            ? (data[2 /* C6 */] <0.12413351f ? 0.27269724f : 0.06899216f)
            : (data[1 /* C5 */] <0.42226562f ? -0.10050842f : -0.03779588f))))
      : (data[0 /* C4 */] <0.15228516f
        ? (data[2 /* C6 */] <0.21514843f
          ? (data[2 /* C6 */] <0.18024808f
            ? 0.30287832f
            : (data[1 /* C5 */] <0.5245625f ? 0.010406127f : 0.15535372f))
          : (data[1 /* C5 */] <1.2404375f
            ? (data[2 /* C6 */] <0.4460469f ? -0.001334034f : -0.070886925f)
            : (data[2 /* C6 */] <0.5524531f ? 0.2556183f : 0.09937038f)))
        : (data[0 /* C4 */] <0.21339233f
          ? (data[2 /* C6 */] <0.4905f
            ? (data[1 /* C5 */] <1.21125f ? 0.07802264f : 0.33709916f)
            : (data[1 /* C5 */] <1.306875f ? -0.020953987f : 0.06617078f))
          : (data[2 /* C6 */] <0.76065624f
            ? (data[1 /* C5 */] <1.70975f ? 0.19080205f : 0.55047333f)
            : (data[0 /* C4 */] <0.22929688f ? 0.030489182f : 0.18959545f)))));
    return pred;
  }
}


class gbm4_Forest_11 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_11_class_0.score0(fdata);
  }
}
class gbm4_Tree_11_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.6168833f
      ? (data[1 /* C5 */] <0.24459067f
        ? (data[1 /* C5 */] <0.119504854f
          ? (data[1 /* C5 */] <0.05019535f
            ? (data[1 /* C5 */] <0.0178141f ? -0.22224683f : -0.18131769f)
            : (data[1 /* C5 */] <0.08376479f ? -0.15515442f : -0.13400897f))
          : (data[2 /* C6 */] <0.10134375f
            ? (data[0 /* C4 */] <0.08203125f ? -0.1144148f : -0.07545218f)
            : (data[2 /* C6 */] <0.10769238f ? -0.18341877f : -0.13063066f)))
        : (data[0 /* C4 */] <0.13242188f
          ? (data[2 /* C6 */] <0.12265625f
            ? (data[1 /* C5 */] <0.3207578f ? -0.028746737f : 0.2760171f)
            : (data[1 /* C5 */] <0.34391406f ? -0.10586805f : -0.051908907f))
          : (data[2 /* C6 */] <0.24791016f
            ? (data[1 /* C5 */] <0.5218359f ? -0.016563367f : 0.12658931f)
            : (data[2 /* C6 */] <0.26534608f ? -0.08655359f : -0.17448802f))))
      : (data[0 /* C4 */] <0.18208008f
        ? (data[2 /* C6 */] <0.2774922f
          ? (data[1 /* C5 */] <0.8117969f
            ? (data[2 /* C6 */] <0.24353126f ? 0.23624508f : 0.06727277f)
            : 0.30832154f)
          : (data[1 /* C5 */] <0.7978828f
            ? (data[2 /* C6 */] <0.30775f ? 0.0070524095f : -0.076908305f)
            : (data[2 /* C6 */] <0.3985f ? 0.10602558f : 0.008934879f)))
        : (data[2 /* C6 */] <0.5892109f
          ? (data[1 /* C5 */] <1.4044063f
            ? (data[2 /* C6 */] <0.48825783f ? 0.17000091f : 0.041245356f)
            : (data[1 /* C5 */] <1.4909614f ? 0.52276164f : 0.27841356f))
          : (data[1 /* C5 */] <1.8056562f
            ? (data[1 /* C5 */] <1.5505977f ? -0.024872964f : 0.05511449f)
            : (data[2 /* C6 */] <0.7579687f ? 0.48973852f : 0.057632953f)))));
    return pred;
  }
}


class gbm4_Forest_12 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_12_class_0.score0(fdata);
  }
}
class gbm4_Tree_12_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.6168833f
      ? (data[1 /* C5 */] <0.24939445f
        ? (data[1 /* C5 */] <0.123764455f
          ? (data[1 /* C5 */] <0.05717452f
            ? (data[1 /* C5 */] <0.017517833f ? -0.20002216f : -0.160697f)
            : (data[2 /* C6 */] <0.0473125f ? -0.12045743f : -0.15197347f))
          : (data[2 /* C6 */] <0.0781875f
            ? (data[1 /* C5 */] <0.19138281f ? -0.0871915f : 0.015248479f)
            : (data[0 /* C4 */] <0.0875f ? -0.12763913f : -0.08719809f)))
        : (data[0 /* C4 */] <0.13242188f
          ? (data[2 /* C6 */] <0.12265625f
            ? (data[1 /* C5 */] <0.31290624f ? -0.02455405f : 0.20657429f)
            : (data[1 /* C5 */] <0.33578125f ? -0.100470796f : -0.046952143f))
          : (data[2 /* C6 */] <0.24791016f
            ? (data[1 /* C5 */] <0.5218359f ? -0.014907025f : 0.11393034f)
            : (data[2 /* C6 */] <0.26534608f ? -0.077898234f : -0.15703923f))))
      : (data[0 /* C4 */] <0.18208008f
        ? (data[2 /* C6 */] <0.2774922f
          ? (data[1 /* C5 */] <0.8117969f
            ? (data[2 /* C6 */] <0.24353126f ? 0.21262057f : 0.060545452f)
            : 0.27748936f)
          : (data[1 /* C5 */] <0.92310935f
            ? (data[2 /* C6 */] <0.383375f ? 3.2260668E-4f : -0.09055496f)
            : (data[2 /* C6 */] <0.443875f ? 0.15119746f : 0.00520808f)))
        : (data[2 /* C6 */] <0.5892109f
          ? (data[1 /* C5 */] <1.4044063f
            ? (data[2 /* C6 */] <0.48825783f ? 0.1530008f : 0.037120808f)
            : (data[1 /* C5 */] <1.4909614f ? 0.4704855f : 0.2505722f))
          : (data[0 /* C4 */] <0.22238281f
            ? (data[1 /* C5 */] <1.5505f ? -0.025704427f : 0.07081401f)
            : (data[1 /* C5 */] <2.1215937f ? 0.18575391f : 0.30435696f)))));
    return pred;
  }
}


class gbm4_Forest_13 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_13_class_0.score0(fdata);
  }
}
class gbm4_Tree_13_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.6499712f
      ? (data[1 /* C5 */] <0.2449892f
        ? (data[2 /* C6 */] <0.035734374f
          ? (data[1 /* C5 */] <0.041785154f
            ? (data[2 /* C6 */] <0.011625f ? -0.14311093f : -0.18117893f)
            : (data[2 /* C6 */] <0.0233125f ? -0.09599644f : -0.14134984f))
          : (data[2 /* C6 */] <0.1003186f
            ? (data[1 /* C5 */] <0.194625f ? -0.092084356f : -0.05434675f)
            : (data[2 /* C6 */] <0.1064855f ? -0.15220311f : -0.118548706f)))
        : (data[2 /* C6 */] <0.26536718f
          ? (data[1 /* C5 */] <0.57964844f
            ? (data[0 /* C4 */] <0.11671875f ? -0.049188815f : -0.0086641805f)
            : (data[2 /* C6 */] <0.2280625f ? 0.18310009f : 0.03863927f))
          : (data[2 /* C6 */] <0.31865352f
            ? (data[2 /* C6 */] <0.2696526f ? -0.14271969f : -0.081482604f)
            : -0.16399643f)))
      : (data[0 /* C4 */] <0.18208008f
        ? (data[2 /* C6 */] <0.29419923f
          ? (data[1 /* C5 */] <0.77290624f
            ? (data[2 /* C6 */] <0.24764062f ? 0.17115712f : 0.049544178f)
            : (data[0 /* C4 */] <0.1575f ? 0.15099259f : 0.32453912f))
          : (data[1 /* C5 */] <0.8958125f
            ? (data[2 /* C6 */] <0.38365626f ? -0.005250067f : -0.091607496f)
            : (data[2 /* C6 */] <0.3985156f ? 0.15677835f : 0.013896083f)))
        : (data[2 /* C6 */] <0.7541484f
          ? (data[1 /* C5 */] <1.8056562f
            ? (data[2 /* C6 */] <0.58441406f ? 0.13345538f : 0.03766101f)
            : (data[0 /* C4 */] <0.20226562f ? 0.31120265f : 0.4923189f))
          : (data[1 /* C5 */] <2.4409688f
            ? (data[0 /* C4 */] <0.22109374f ? -0.023575133f : 0.14416723f)
            : 0.21960893f))));
    return pred;
  }
}


class gbm4_Forest_14 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_14_class_0.score0(fdata);
  }
}
class gbm4_Tree_14_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.7299336f
      ? (data[1 /* C5 */] <0.33611014f
        ? (data[0 /* C4 */] <0.07724609f
          ? (data[1 /* C5 */] <0.056796875f
            ? (data[0 /* C4 */] <0.05214844f ? -0.14325243f : -0.11400198f)
            : (data[1 /* C5 */] <0.14332446f ? -0.10293534f : -0.083715886f))
          : (data[2 /* C6 */] <0.1245f
            ? (data[1 /* C5 */] <0.27384374f ? -0.06405612f : 0.019433802f)
            : (data[1 /* C5 */] <0.3073125f ? -0.11164564f : -0.0750496f)))
        : (data[2 /* C6 */] <0.14765625f
          ? (data[2 /* C6 */] <0.12556408f
            ? 0.20271377f
            : (data[2 /* C6 */] <0.1421874f ? 0.044657573f : 0.11901696f))
          : (data[1 /* C5 */] <0.42314062f
            ? (data[2 /* C6 */] <0.178375f ? -0.062656164f : -0.12272323f)
            : (data[2 /* C6 */] <0.17457813f ? 0.14316367f : -0.023040816f))))
      : (data[2 /* C6 */] <0.32628125f
        ? (data[1 /* C5 */] <0.9391816f
          ? (data[2 /* C6 */] <0.3152969f
            ? (data[1 /* C5 */] <0.8113437f ? 0.096886314f : 0.20551667f)
            : (data[1 /* C5 */] <0.7880234f ? -0.053553026f : 0.048285853f))
          : 0.29764372f)
        : (data[1 /* C5 */] <0.992375f
          ? (data[2 /* C6 */] <0.39001954f
            ? (data[1 /* C5 */] <0.8980234f ? -0.0112294955f : 0.10786105f)
            : (data[1 /* C5 */] <0.9061953f ? -0.09642137f : -0.051083386f))
          : (data[2 /* C6 */] <0.43539062f
            ? (data[1 /* C5 */] <1.136625f ? 0.16639616f : 0.28284606f)
            : (data[1 /* C5 */] <1.193875f ? -0.021672677f : 0.054409973f)))));
    return pred;
  }
}


class gbm4_Forest_15 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_15_class_0.score0(fdata);
  }
}
class gbm4_Tree_15_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.6168833f
      ? (data[1 /* C5 */] <0.22417462f
        ? (data[1 /* C5 */] <0.09746566f
          ? (data[1 /* C5 */] <0.04152875f
            ? (data[2 /* C6 */] <0.011875f ? -0.11465189f : -0.15026575f)
            : (data[2 /* C6 */] <0.037703127f ? -0.09546938f : -0.14253561f))
          : (data[2 /* C6 */] <0.0781875f
            ? (data[1 /* C5 */] <0.16865624f ? -0.07743438f : -0.016304474f)
            : (data[1 /* C5 */] <0.2081875f ? -0.10229793f : -0.07317613f)))
        : (data[2 /* C6 */] <0.2325625f
          ? (data[1 /* C5 */] <0.49671483f
            ? (data[2 /* C6 */] <0.21703126f ? -0.030772947f : -0.13672021f)
            : (data[2 /* C6 */] <0.18609375f ? 0.21482848f : 0.05125308f))
          : (data[1 /* C5 */] <0.54871094f
            ? (data[2 /* C6 */] <0.23695312f ? -0.14033684f : -0.0953736f)
            : (data[2 /* C6 */] <0.25671875f ? -0.019488402f : -0.08389857f))))
      : (data[1 /* C5 */] <1.5658983f
        ? (data[2 /* C6 */] <0.25151563f
          ? (data[0 /* C4 */] <0.1471875f
            ? (data[1 /* C5 */] <0.7532656f ? 0.13088375f : -0.02471787f)
            : (data[2 /* C6 */] <0.23908204f ? 0.07813112f : 0.39335477f))
          : (data[1 /* C5 */] <0.9875078f
            ? (data[2 /* C6 */] <0.38515624f ? 0.017927565f : -0.062633954f)
            : (data[2 /* C6 */] <0.4404297f ? 0.16875644f : 0.008904071f)))
        : (data[2 /* C6 */] <0.64116406f
          ? (data[2 /* C6 */] <0.6206383f
            ? (data[0 /* C4 */] <0.19f ? 0.33917576f : 0.17693575f)
            : 0.5293669f)
          : (data[2 /* C6 */] <0.76686627f
            ? (data[1 /* C5 */] <1.8021562f ? 0.046549354f : 0.3628366f)
            : (data[1 /* C5 */] <2.451586f ? -0.013981189f : 0.19220701f)))));
    return pred;
  }
}


class gbm4_Forest_16 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_16_class_0.score0(fdata);
  }
}
class gbm4_Tree_16_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.7299336f
      ? (data[0 /* C4 */] <0.10262695f
        ? (data[1 /* C5 */] <0.112753905f
          ? (data[0 /* C4 */] <0.0625f
            ? (data[2 /* C6 */] <0.03959375f ? -0.10215039f : -0.14263393f)
            : (data[1 /* C5 */] <0.10386719f ? -0.06973719f : -0.109575674f))
          : (data[0 /* C4 */] <0.0875f
            ? (data[2 /* C6 */] <0.04703125f ? 0.0073001864f : -0.06817262f)
            : (data[2 /* C6 */] <0.09217188f ? -0.01678046f : -0.056337837f)))
        : (data[2 /* C6 */] <0.278875f
          ? (data[1 /* C5 */] <0.6157578f
            ? (data[2 /* C6 */] <0.23483594f ? -0.0043293633f : -0.053733353f)
            : (data[2 /* C6 */] <0.24479687f ? 0.1762491f : 0.030838182f))
          : (data[2 /* C6 */] <0.3191699f
            ? (data[1 /* C5 */] <0.6605156f ? -0.0746287f : -0.020279901f)
            : (data[1 /* C5 */] <0.67840624f ? -0.15654989f : -0.0693856f))))
      : (data[2 /* C6 */] <0.32628125f
        ? (data[1 /* C5 */] <0.9391816f
          ? (data[2 /* C6 */] <0.3152969f
            ? (data[2 /* C6 */] <0.23833472f ? -0.052191354f : 0.13334727f)
            : (data[2 /* C6 */] <0.3218191f ? -0.022155967f : 0.06933341f))
          : 0.2612959f)
        : (data[1 /* C5 */] <1.0005586f
          ? (data[2 /* C6 */] <0.39001954f
            ? (data[1 /* C5 */] <0.89925f ? -0.011557902f : 0.09651882f)
            : (data[2 /* C6 */] <0.4521928f ? -0.04296579f : -0.09437029f))
          : (data[2 /* C6 */] <0.43539062f
            ? (data[0 /* C4 */] <0.1946875f ? 0.14447041f : 0.3456815f)
            : (data[1 /* C5 */] <1.2005547f ? -0.017501095f : 0.045974318f)))));
    return pred;
  }
}


class gbm4_Forest_17 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_17_class_0.score0(fdata);
  }
}
class gbm4_Tree_17_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.8043814f
      ? (data[1 /* C5 */] <0.33737034f
        ? (data[1 /* C5 */] <0.12383375f
          ? (data[0 /* C4 */] <0.0525f
            ? (data[1 /* C5 */] <0.04186719f ? -0.10992709f : -0.08883506f)
            : (data[2 /* C6 */] <0.0473125f ? -0.07249593f : -0.094990335f))
          : (data[2 /* C6 */] <0.1245f
            ? (data[1 /* C5 */] <0.283f ? -0.048073843f : 0.035180695f)
            : (data[2 /* C6 */] <0.1554375f ? -0.067528024f : -0.11397903f)))
        : (data[2 /* C6 */] <0.30203125f
          ? (data[1 /* C5 */] <0.7311094f
            ? (data[2 /* C6 */] <0.1484375f ? 0.092318796f : -0.01244247f)
            : (data[2 /* C6 */] <0.29103124f ? 0.081871726f : 0.2188109f))
          : (data[1 /* C5 */] <0.68008596f
            ? (data[2 /* C6 */] <0.3191875f ? -0.082336314f : -0.13430515f)
            : (data[2 /* C6 */] <0.335875f ? -0.015057909f : -0.07620377f))))
      : (data[2 /* C6 */] <0.34951562f
        ? (data[1 /* C5 */] <0.89923435f
          ? (data[2 /* C6 */] <0.33602345f
            ? (data[1 /* C5 */] <0.87425f ? 0.14921772f : -3.960669E-4f)
            : (data[0 /* C4 */] <0.1475f ? 0.033303037f : -0.09106261f))
          : (data[2 /* C6 */] <0.34276173f
            ? (data[1 /* C5 */] <0.985293f ? 0.15387724f : 0.26146454f)
            : 0.40427208f))
        : (data[1 /* C5 */] <1.0887032f
          ? (data[2 /* C6 */] <0.4482539f
            ? (data[1 /* C5 */] <0.9866172f ? -0.01653341f : 0.08402745f)
            : (data[2 /* C6 */] <0.52162695f ? -0.058890644f : -0.12200273f))
          : (data[2 /* C6 */] <0.5015742f
            ? (data[1 /* C5 */] <1.2246641f ? 0.08337844f : 0.23636776f)
            : (data[1 /* C5 */] <1.4145937f ? -0.014410188f : 0.054211415f)))));
    return pred;
  }
}


class gbm4_Forest_18 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_18_class_0.score0(fdata);
  }
}
class gbm4_Tree_18_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.5727661f
      ? (data[0 /* C4 */] <0.08717773f
        ? (data[2 /* C6 */] <0.035734374f
          ? (data[2 /* C6 */] <0.007241333f
            ? -0.11883684f
            : (data[2 /* C6 */] <0.03218076f ? -0.07577157f : -0.11341195f))
          : (data[1 /* C5 */] <0.25828907f
            ? (data[2 /* C6 */] <0.071859375f ? -0.045740418f : -0.077383496f)
            : (data[0 /* C4 */] <0.08234375f ? 0.018393314f : -0.045286678f)))
        : (data[2 /* C6 */] <0.21519531f
          ? (data[1 /* C5 */] <0.4326367f
            ? (data[2 /* C6 */] <0.16134375f ? -0.020610189f : -0.076822646f)
            : (data[2 /* C6 */] <0.18659376f ? 0.074656084f : 8.0059294E-4f))
          : (data[1 /* C5 */] <0.50044924f
            ? (data[1 /* C5 */] <0.4843931f ? -0.12439647f : -0.07641923f)
            : (data[0 /* C4 */] <0.12234375f ? -0.014617226f : -0.07470807f))))
      : (data[1 /* C5 */] <1.7145326f
        ? (data[2 /* C6 */] <0.25151563f
          ? (data[0 /* C4 */] <0.14566407f
            ? (data[2 /* C6 */] <0.22958593f ? 0.11762799f : 0.023659252f)
            : (data[2 /* C6 */] <0.2398125f ? 0.10031979f : 0.31750864f))
          : (data[1 /* C5 */] <0.80415624f
            ? (data[2 /* C6 */] <0.30777344f ? 0.0015264829f : -0.05823259f)
            : (data[2 /* C6 */] <0.38515624f ? 0.080131404f : 0.0074377195f)))
        : (data[2 /* C6 */] <0.7554609f
          ? (data[0 /* C4 */] <0.20714843f
            ? (data[0 /* C4 */] <0.18772705f ? 0.35355282f : 0.11780515f)
            : 0.38122872f)
          : (data[1 /* C5 */] <2.4449687f
            ? (data[2 /* C6 */] <0.8264375f ? 0.071704246f : -0.023296379f)
            : 0.16296764f))));
    return pred;
  }
}


class gbm4_Forest_19 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_19_class_0.score0(fdata);
  }
}
class gbm4_Tree_19_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.47350243f
      ? (data[1 /* C5 */] <0.15118632f
        ? (data[1 /* C5 */] <0.074553505f
          ? (data[1 /* C5 */] <0.018437903f
            ? -0.10412611f
            : (data[2 /* C6 */] <0.02740625f ? -0.068769954f : -0.12360504f))
          : (data[2 /* C6 */] <0.058890626f
            ? (data[2 /* C6 */] <0.03206714f ? -0.01395381f : -0.052818578f)
            : (data[1 /* C5 */] <0.1450625f ? -0.0805279f : -0.107886024f)))
        : (data[2 /* C6 */] <0.19396874f
          ? (data[1 /* C5 */] <0.43488282f
            ? (data[2 /* C6 */] <0.16117187f ? -0.024150997f : -0.06832686f)
            : (data[2 /* C6 */] <0.17253906f ? 0.089871906f : 0.013123756f))
          : (data[2 /* C6 */] <0.19653173f
            ? -0.14885353f
            : (data[2 /* C6 */] <0.20410055f ? -0.031806834f : -0.080608934f))))
      : (data[1 /* C5 */] <1.148783f
        ? (data[2 /* C6 */] <0.44451562f
          ? (data[1 /* C5 */] <0.937375f
            ? (data[2 /* C6 */] <0.21500781f ? 0.06884023f : -0.0089889215f)
            : (data[2 /* C6 */] <0.3614922f ? 0.1994131f : 0.067374684f))
          : (data[2 /* C6 */] <0.52951586f
            ? (data[1 /* C5 */] <1.084625f ? -0.055649675f : 0.011885387f)
            : (data[2 /* C6 */] <0.5408264f ? -0.07493733f : -0.11077777f)))
        : (data[2 /* C6 */] <0.5345625f
          ? (data[1 /* C5 */] <1.2411562f
            ? (data[2 /* C6 */] <0.4360625f ? 0.28244063f : 0.035806797f)
            : (data[2 /* C6 */] <0.4885625f ? 0.2467011f : 0.14627776f))
          : (data[1 /* C5 */] <1.7125312f
            ? (data[2 /* C6 */] <0.69879687f ? 0.009822886f : -0.0678796f)
            : (data[2 /* C6 */] <0.77325f ? 0.19898485f : 0.0087846825f)))));
    return pred;
  }
}


class gbm4_Forest_20 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_20_class_0.score0(fdata);
  }
}
class gbm4_Tree_20_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.57828075f
      ? (data[1 /* C5 */] <0.24962063f
        ? (data[2 /* C6 */] <0.035734374f
          ? (data[2 /* C6 */] <0.007241333f
            ? -0.09708449f
            : (data[2 /* C6 */] <0.03218076f ? -0.061812673f : -0.09619899f))
          : (data[2 /* C6 */] <0.1003186f
            ? (data[1 /* C5 */] <0.23282813f ? -0.039861985f : 0.04511432f)
            : (data[1 /* C5 */] <0.24091406f ? -0.09217314f : -0.06535167f)))
        : (data[2 /* C6 */] <0.2325625f
          ? (data[1 /* C5 */] <0.4934375f
            ? (data[2 /* C6 */] <0.11683594f ? 0.032089006f : -0.028825438f)
            : (data[2 /* C6 */] <0.18623437f ? 0.1524912f : 0.023727506f))
          : (data[0 /* C4 */] <0.12726563f
            ? (data[1 /* C5 */] <0.5458125f ? -0.07703322f : -0.02439911f)
            : (data[2 /* C6 */] <0.2488125f ? -0.13249038f : -0.073381506f))))
      : (data[2 /* C6 */] <0.24205664f
        ? (data[2 /* C6 */] <0.23942986f
          ? (data[2 /* C6 */] <0.23338623f
            ? (data[1 /* C5 */] <0.68551564f ? 0.15951721f : -0.031865027f)
            : (data[1 /* C5 */] <0.60822654f ? -0.113295764f : 0.09249263f))
          : 0.24217352f)
        : (data[1 /* C5 */] <1.0875859f
          ? (data[2 /* C6 */] <0.40791798f
            ? (data[1 /* C5 */] <0.93639064f ? -5.586555E-4f : 0.11674539f)
            : (data[2 /* C6 */] <0.4751506f ? -0.028986363f : -0.06952039f))
          : (data[2 /* C6 */] <0.53441405f
            ? (data[1 /* C5 */] <1.2237422f ? 0.04682199f : 0.160511f)
            : (data[1 /* C5 */] <1.3866328f ? -0.033727128f : 0.035866454f)))));
    return pred;
  }
}


class gbm4_Forest_21 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_21_class_0.score0(fdata);
  }
}
class gbm4_Tree_21_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.6582432f
      ? (data[1 /* C5 */] <0.3365302f
        ? (data[0 /* C4 */] <0.12359375f
          ? (data[0 /* C4 */] <0.07724609f
            ? (data[0 /* C4 */] <0.052503202f ? -0.0695716f : -0.049122203f)
            : (data[2 /* C6 */] <0.1245f ? -0.022051832f : -0.058909558f))
          : -0.13305074f)
        : (data[2 /* C6 */] <0.14765625f
          ? (data[2 /* C6 */] <0.12556408f
            ? 0.18336375f
            : (data[2 /* C6 */] <0.14270152f ? 0.045029346f : 0.11517992f))
          : (data[2 /* C6 */] <0.26382813f
            ? (data[1 /* C5 */] <0.57825f ? -0.018933099f : 0.048031256f)
            : (data[2 /* C6 */] <0.30013183f ? -0.04857714f : -0.08786165f))))
      : (data[2 /* C6 */] <0.30595118f
        ? (data[1 /* C5 */] <0.7605547f
          ? (data[2 /* C6 */] <0.24842188f
            ? (data[0 /* C4 */] <0.1421875f ? 0.19124186f : 0.04714486f)
            : (data[2 /* C6 */] <0.25956994f ? -0.08468601f : 0.039265282f))
          : (data[2 /* C6 */] <0.30001172f
            ? (data[2 /* C6 */] <0.29385474f ? 0.12143933f : 0.019675834f)
            : 0.22564934f))
        : (data[1 /* C5 */] <0.9890527f
          ? (data[2 /* C6 */] <0.39834374f
            ? (data[1 /* C5 */] <0.83428127f ? -0.031467106f : 0.03922315f)
            : (data[2 /* C6 */] <0.42631054f ? -0.07660909f : -0.03257185f))
          : (data[2 /* C6 */] <0.44451562f
            ? (data[2 /* C6 */] <0.36761573f ? 0.23925076f : 0.09431845f)
            : (data[1 /* C5 */] <1.219f ? -0.021015419f : 0.02980552f)))));
    return pred;
  }
}


class gbm4_Forest_22 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_22_class_0.score0(fdata);
  }
}
class gbm4_Tree_22_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.7189043f
      ? (data[1 /* C5 */] <0.3786548f
        ? (data[2 /* C6 */] <0.155375f
          ? (data[1 /* C5 */] <0.3373203f
            ? (data[1 /* C5 */] <0.14346325f ? -0.049216554f : -0.02749269f)
            : (data[2 /* C6 */] <0.13334376f ? 0.16258168f : 0.01631046f))
          : (data[0 /* C4 */] <0.1025f
            ? (data[1 /* C5 */] <0.3614375f ? -0.06757074f : 0.0013208071f)
            : (data[2 /* C6 */] <0.16080469f ? -0.05428163f : -0.15460011f)))
        : (data[2 /* C6 */] <0.17274219f
          ? (data[1 /* C5 */] <0.4970293f
            ? (data[1 /* C5 */] <0.38822103f ? 0.10904574f : 0.023064706f)
            : 0.30270267f)
          : (data[2 /* C6 */] <0.27846083f
            ? (data[1 /* C5 */] <0.5228047f ? -0.030804915f : 0.019193947f)
            : (data[0 /* C4 */] <0.14125f ? -0.043749496f : -0.089762025f))))
      : (data[2 /* C6 */] <0.33499414f
        ? (data[2 /* C6 */] <0.23775975f
          ? -0.08002287f
          : (data[2 /* C6 */] <0.25287542f
            ? 0.26601884f
            : (data[1 /* C5 */] <0.82773435f ? 0.043893088f : 0.104454234f)))
        : (data[1 /* C5 */] <0.90094143f
          ? (data[2 /* C6 */] <0.38003907f
            ? (data[2 /* C6 */] <0.34977844f ? -0.06168844f : 0.007958526f)
            : (data[2 /* C6 */] <0.43076953f ? -0.07770971f : -0.02107245f))
          : (data[2 /* C6 */] <0.35301563f
            ? (data[0 /* C4 */] <0.1634375f ? 0.3274934f : 0.055403512f)
            : (data[0 /* C4 */] <0.2103125f ? 0.012044933f : 0.094174415f)))));
    return pred;
  }
}


class gbm4_Forest_23 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_23_class_0.score0(fdata);
  }
}
class gbm4_Tree_23_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.64445657f
      ? (data[1 /* C5 */] <0.3784394f
        ? (data[2 /* C6 */] <0.155375f
          ? (data[1 /* C5 */] <0.336875f
            ? (data[0 /* C4 */] <0.1225f ? -0.030032044f : -0.11699639f)
            : (data[2 /* C6 */] <0.13334376f ? 0.14632355f : 0.008968784f))
          : (data[0 /* C4 */] <0.1025f
            ? (data[0 /* C4 */] <0.092539065f ? -0.087269686f : -0.021513242f)
            : (data[2 /* C6 */] <0.16080469f ? -0.048853505f : -0.1391401f)))
        : (data[2 /* C6 */] <0.2325625f
          ? (data[1 /* C5 */] <0.4863594f
            ? (data[2 /* C6 */] <0.19394532f ? 0.017016416f : -0.055095423f)
            : (data[0 /* C4 */] <0.10828125f ? 0.1821844f : 0.038139317f))
          : (data[2 /* C6 */] <0.2636626f
            ? (data[1 /* C5 */] <0.58716404f ? -0.0526077f : 0.025180226f)
            : (data[0 /* C4 */] <0.13398437f ? -0.046457417f : -0.089787364f))))
      : (data[2 /* C6 */] <0.30595118f
        ? (data[1 /* C5 */] <0.76377344f
          ? (data[2 /* C6 */] <0.270375f
            ? (data[2 /* C6 */] <0.2637891f ? 0.04142088f : 0.19071142f)
            : (data[2 /* C6 */] <0.30001172f ? 0.013145804f : -0.05577545f))
          : (data[2 /* C6 */] <0.30001172f
            ? (data[1 /* C5 */] <0.9215f ? 0.06814583f : 0.17229943f)
            : 0.19667646f))
        : (data[1 /* C5 */] <0.9852812f
          ? (data[2 /* C6 */] <0.36140624f
            ? (data[1 /* C5 */] <0.88923436f ? -0.011047783f : 0.10456866f)
            : (data[0 /* C4 */] <0.13191406f ? 0.015289896f : -0.04261029f))
          : (data[2 /* C6 */] <0.44451562f
            ? (data[0 /* C4 */] <0.155625f ? 0.14667527f : 0.068751834f)
            : (data[1 /* C5 */] <1.2155f ? -0.021903781f : 0.025267f)))));
    return pred;
  }
}


class gbm4_Forest_24 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_24_class_0.score0(fdata);
  }
}
class gbm4_Tree_24_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.112558596f
      ? (data[0 /* C4 */] <0.07749396f
        ? (data[0 /* C4 */] <0.05252032f
          ? (data[1 /* C5 */] <0.05611719f
            ? (data[0 /* C4 */] <0.0375f ? -0.047460034f : -0.06485851f)
            : -0.036046725f)
          : (data[2 /* C6 */] <0.08874219f
            ? (data[2 /* C6 */] <0.06942963f ? -0.03744151f : -0.01349204f)
            : -0.06722318f))
        : (data[2 /* C6 */] <0.22680078f
          ? (data[1 /* C5 */] <0.49659374f
            ? (data[2 /* C6 */] <0.072625f ? 3.07074E-4f : -0.026036132f)
            : 0.1610133f)
          : (data[1 /* C5 */] <0.47067186f
            ? -0.0943227f
            : (data[2 /* C6 */] <0.30655468f ? -0.02709808f : -0.080289155f))))
      : (data[1 /* C5 */] <1.5957334f
        ? (data[2 /* C6 */] <0.5838594f
          ? (data[1 /* C5 */] <1.3156953f
            ? (data[1 /* C5 */] <1.1613319f ? 0.0011905219f : 0.04256426f)
            : (data[1 /* C5 */] <1.4012718f ? 0.08958596f : 0.20494552f))
          : (data[2 /* C6 */] <0.69846475f
            ? (data[1 /* C5 */] <1.3860781f ? -0.05554025f : 0.0065293266f)
            : (data[1 /* C5 */] <1.3941329f ? -0.033362042f : -0.09776141f)))
        : (data[2 /* C6 */] <0.7058906f
          ? (data[2 /* C6 */] <0.64575064f
            ? (data[2 /* C6 */] <0.59468406f ? 0.1417097f : 0.3539462f)
            : (data[1 /* C5 */] <1.7663125f ? 0.07072348f : 0.25969684f))
          : (data[0 /* C4 */] <0.22160156f
            ? (data[1 /* C5 */] <1.7885313f ? -0.06257844f : 0.013464562f)
            : 0.17141892f))));
    return pred;
  }
}


class gbm4_Forest_25 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_25_class_0.score0(fdata);
  }
}
class gbm4_Tree_25_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.8043814f
      ? (data[0 /* C4 */] <0.14676757f
        ? (data[2 /* C6 */] <0.33483595f
          ? (data[0 /* C4 */] <0.102519535f
            ? (data[1 /* C5 */] <0.07704688f ? -0.045090176f : -0.023935482f)
            : (data[2 /* C6 */] <0.21985938f ? 0.006578854f : -0.017474974f))
          : (data[2 /* C6 */] <0.3648667f
            ? (data[2 /* C6 */] <0.3410667f ? -0.075255096f : -0.032462116f)
            : (data[2 /* C6 */] <0.40350002f ? -0.09286703f : -0.053931076f)))
        : (data[0 /* C4 */] <0.17365283f
          ? (data[2 /* C6 */] <0.24307813f
            ? (data[2 /* C6 */] <0.22271729f ? 0.03174348f : 0.33524472f)
            : (data[2 /* C6 */] <0.30011377f ? 0.048453998f : -0.018538354f))
          : -0.10531199f))
      : (data[2 /* C6 */] <0.34951562f
        ? (data[1 /* C5 */] <0.89923435f
          ? (data[2 /* C6 */] <0.33602345f
            ? (data[1 /* C5 */] <0.87425f ? 0.106113404f : -0.03112163f)
            : (data[0 /* C4 */] <0.1475f ? 0.031628244f : -0.08501854f))
          : (data[0 /* C4 */] <0.16226563f
            ? (data[2 /* C6 */] <0.33735937f ? 0.12659694f : 0.34525216f)
            : (data[2 /* C6 */] <0.32348436f ? -0.04500377f : 0.13073118f)))
        : (data[1 /* C5 */] <1.0255469f
          ? (data[0 /* C4 */] <0.18296875f
            ? (data[2 /* C6 */] <0.44710937f ? -0.0021418878f : -0.05527113f)
            : -0.15499562f)
          : (data[2 /* C6 */] <0.4926875f
            ? (data[1 /* C5 */] <1.2228203f ? 0.042791493f : 0.18623851f)
            : (data[1 /* C5 */] <1.475875f ? -0.0153644495f : 0.033497117f)))));
    return pred;
  }
}


class gbm4_Forest_26 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_26_class_0.score0(fdata);
  }
}
class gbm4_Tree_26_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.6582432f
      ? (data[2 /* C6 */] <0.2623867f
        ? (data[1 /* C5 */] <0.5785625f
          ? (data[1 /* C5 */] <0.4118999f
            ? (data[2 /* C6 */] <0.15567188f ? -0.017947203f : -0.049907293f)
            : (data[2 /* C6 */] <0.18823437f ? 0.04720009f : -0.01976157f))
          : (data[2 /* C6 */] <0.24364844f
            ? (data[0 /* C4 */] <0.14777344f ? 0.056504678f : 0.18878491f)
            : (data[1 /* C5 */] <0.5929258f ? 0.09636077f : -0.028725998f)))
        : (data[0 /* C4 */] <0.13683593f
          ? (data[2 /* C6 */] <0.3188086f
            ? (data[1 /* C5 */] <0.54577345f ? -0.07521876f : -0.027868396f)
            : (data[2 /* C6 */] <0.3408325f ? -0.08376495f : -0.055991538f))
          : (data[1 /* C5 */] <0.62778515f ? -0.13195731f : -0.04312481f)))
      : (data[2 /* C6 */] <0.30595118f
        ? (data[1 /* C5 */] <0.7605547f
          ? (data[1 /* C5 */] <0.68399197f
            ? (data[2 /* C6 */] <0.26817968f ? 0.1578734f : 0.0040279976f)
            : (data[1 /* C5 */] <0.69714177f ? -0.05012775f : 0.024096902f))
          : (data[1 /* C5 */] <0.78327f
            ? (data[2 /* C6 */] <0.290875f ? 0.07893724f : 0.26965705f)
            : (data[1 /* C5 */] <0.80988955f ? -0.044361103f : 0.09830949f)))
        : (data[1 /* C5 */] <1.0906074f
          ? (data[2 /* C6 */] <0.4075781f
            ? (data[1 /* C5 */] <0.98948437f ? -0.003100578f : 0.11372429f)
            : (data[0 /* C4 */] <0.16839844f ? -0.02597251f : -0.08750261f))
          : (data[2 /* C6 */] <0.4906875f
            ? (data[1 /* C5 */] <1.1727812f ? 0.04566023f : 0.15039738f)
            : (data[1 /* C5 */] <1.30825f ? -0.022532217f : 0.020490626f)))));
    return pred;
  }
}


class gbm4_Forest_27 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_27_class_0.score0(fdata);
  }
}
class gbm4_Tree_27_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.8043814f
      ? (data[1 /* C5 */] <0.80124706f
        ? (data[0 /* C4 */] <0.14566407f
          ? (data[2 /* C6 */] <0.3676406f
            ? (data[0 /* C4 */] <0.09742188f ? -0.024284892f : -0.0067121997f)
            : (data[2 /* C6 */] <0.40346044f ? -0.083944544f : -0.04579777f))
          : (data[2 /* C6 */] <0.24414062f
            ? (data[2 /* C6 */] <0.2228119f ? 0.016418183f : 0.21622388f)
            : (data[0 /* C4 */] <0.1653125f ? 0.021305377f : -0.06123732f)))
        : -0.1489644f)
      : (data[2 /* C6 */] <0.40179297f
        ? (data[1 /* C5 */] <0.9860742f
          ? (data[2 /* C6 */] <0.34539843f
            ? (data[2 /* C6 */] <0.34193286f ? 0.06265835f : 0.18785429f)
            : (data[1 /* C5 */] <0.96384764f ? 0.009166475f : -0.12403373f))
          : (data[2 /* C6 */] <0.37671095f
            ? (data[2 /* C6 */] <0.36778492f ? 0.14814426f : -0.17224647f)
            : (data[1 /* C5 */] <1.0124453f ? -0.005084464f : 0.22550842f)))
        : (data[1 /* C5 */] <1.0887032f
          ? (data[0 /* C4 */] <0.16734375f
            ? (data[2 /* C6 */] <0.44723436f ? -0.005675472f : -0.040465724f)
            : (data[1 /* C5 */] <0.99678123f ? -0.14537878f : -0.04039649f))
          : (data[2 /* C6 */] <0.55471873f
            ? (data[1 /* C5 */] <1.2246641f ? 0.014706639f : 0.105901934f)
            : (data[1 /* C5 */] <1.7130547f ? -0.020860823f : 0.040375642f)))));
    return pred;
  }
}


class gbm4_Forest_28 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_28_class_0.score0(fdata);
  }
}
class gbm4_Tree_28_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.73269093f
      ? (data[0 /* C4 */] <0.17766601f
        ? (data[2 /* C6 */] <0.30010155f
          ? (data[1 /* C5 */] <0.4243203f
            ? (data[2 /* C6 */] <0.17853124f ? -0.015510708f : -0.069684334f)
            : (data[2 /* C6 */] <0.17385937f ? 0.094742805f : -7.9545984E-4f))
          : (data[1 /* C5 */] <0.6811367f
            ? (data[1 /* C5 */] <0.6451594f ? -0.04535378f : -0.090178564f)
            : (data[2 /* C6 */] <0.34608594f ? 0.0021294507f : -0.08266276f)))
        : -0.13300653f)
      : (data[2 /* C6 */] <0.33499414f
        ? (data[2 /* C6 */] <0.24553195f
          ? -0.04291324f
          : (data[2 /* C6 */] <0.26290852f
            ? 0.21326874f
            : (data[0 /* C4 */] <0.176875f ? 0.03921881f : 0.14289932f)))
        : (data[1 /* C5 */] <0.9046504f
          ? (data[0 /* C4 */] <0.17710938f
            ? (data[2 /* C6 */] <0.38078126f ? -0.0020191658f : -0.04476062f)
            : -0.1432643f)
          : (data[2 /* C6 */] <0.44309375f
            ? (data[2 /* C6 */] <0.35063037f ? 0.15151195f : 0.03582417f)
            : (data[1 /* C5 */] <1.1455f ? -0.028421998f : 0.013275196f)))));
    return pred;
  }
}


class gbm4_Forest_29 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_29_class_0.score0(fdata);
  }
}
class gbm4_Tree_29_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.64445657f
      ? (data[2 /* C6 */] <0.265291f
        ? (data[1 /* C5 */] <0.57879686f
          ? (data[2 /* C6 */] <0.232f
            ? (data[1 /* C5 */] <0.4974297f ? -0.0139820855f : 0.03055583f)
            : (data[0 /* C4 */] <0.12796874f ? -0.031244094f : -0.0708919f))
          : (data[2 /* C6 */] <0.2155f
            ? 0.119024605f
            : (data[1 /* C5 */] <0.59220314f ? 0.06307492f : 0.0021923382f)))
        : (data[0 /* C4 */] <0.13683593f
          ? (data[2 /* C6 */] <0.31032422f
            ? (data[2 /* C6 */] <0.29701704f ? -0.03749164f : 9.6470444E-4f)
            : -0.065509625f)
          : (data[2 /* C6 */] <0.28611913f ? -0.07480007f : -0.11299699f)))
      : (data[2 /* C6 */] <0.77063864f
        ? (data[1 /* C5 */] <1.9565078f
          ? (data[1 /* C5 */] <1.5670055f
            ? (data[2 /* C6 */] <0.59984374f ? 0.011512035f : -0.038396847f)
            : (data[2 /* C6 */] <0.6376563f ? 0.20423222f : 0.02085949f))
          : 0.41081238f)
        : (data[1 /* C5 */] <1.7775977f
          ? (data[2 /* C6 */] <0.82839847f
            ? (data[2 /* C6 */] <0.7934619f ? -0.08370069f : -0.15537159f)
            : (data[2 /* C6 */] <0.8736365f ? -0.0969786f : -0.04043197f))
          : (data[2 /* C6 */] <0.98491406f
            ? (data[1 /* C5 */] <2.1491797f ? -8.4411434E-4f : 0.20618051f)
            : (data[1 /* C5 */] <2.3854845f ? -0.07713796f : -0.006012466f)))));
    return pred;
  }
}


class gbm4_Forest_30 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_30_class_0.score0(fdata);
  }
}
class gbm4_Tree_30_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.94224757f
      ? (data[2 /* C6 */] <0.40179297f
        ? (data[1 /* C5 */] <0.736375f
          ? (data[2 /* C6 */] <0.29198828f
            ? (data[1 /* C5 */] <0.5865078f ? -0.011303524f : 0.021642148f)
            : (data[0 /* C4 */] <0.12359375f ? -0.007994683f : -0.04521548f))
          : (data[2 /* C6 */] <0.33579296f
            ? (data[2 /* C6 */] <0.24725506f ? -0.049679063f : 0.051237468f)
            : (data[2 /* C6 */] <0.34092632f ? -0.09159762f : -0.0050548688f)))
        : (data[2 /* C6 */] <0.42440695f
          ? (data[1 /* C5 */] <0.90278906f
            ? (data[1 /* C5 */] <0.8689668f ? -0.09231194f : -0.039590795f)
            : -0.11644294f)
          : (data[2 /* C6 */] <0.43233755f
            ? (data[2 /* C6 */] <0.4294597f ? 0.018040892f : 0.07162266f)
            : (data[1 /* C5 */] <0.9158594f ? -0.005586715f : -0.08061616f))))
      : (data[2 /* C6 */] <0.41631445f
        ? (data[0 /* C4 */] <0.1478125f
          ? (data[2 /* C6 */] <0.39103907f ? 0.21793117f : 0.080011114f)
          : (data[2 /* C6 */] <0.37578514f
            ? (data[2 /* C6 */] <0.3684548f ? 0.053158913f : -0.19897209f)
            : (data[2 /* C6 */] <0.38458213f ? 0.20687261f : 0.04777194f)))
        : (data[1 /* C5 */] <1.4058945f
          ? (data[2 /* C6 */] <0.53414065f
            ? (data[1 /* C5 */] <1.2106484f ? -0.0060935062f : 0.07681873f)
            : (data[0 /* C4 */] <0.18757813f ? -0.03864776f : 0.01823081f))
          : (data[2 /* C6 */] <0.6178125f
            ? (data[2 /* C6 */] <0.55354345f ? 0.21367861f : 0.10208219f)
            : (data[0 /* C4 */] <0.22023438f ? -0.009635588f : 0.13862263f)))));
    return pred;
  }
}


class gbm4_Forest_31 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_31_class_0.score0(fdata);
  }
}
class gbm4_Tree_31_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <1.0883857f
      ? (data[2 /* C6 */] <0.40179297f
        ? (data[1 /* C5 */] <0.8419531f
          ? (data[0 /* C4 */] <0.09710938f
            ? (data[1 /* C5 */] <0.30369532f ? -0.021111513f : 0.008746153f)
            : (data[2 /* C6 */] <0.16329688f ? 0.0171562f : -0.006689822f))
          : (data[0 /* C4 */] <0.13242188f
            ? (data[2 /* C6 */] <0.34928906f ? 0.2729748f : 0.09062127f)
            : (data[1 /* C5 */] <1.0571406f ? 0.017046766f : 0.16250947f)))
        : (data[2 /* C6 */] <0.47575504f
          ? (data[2 /* C6 */] <0.4273533f
            ? (data[1 /* C5 */] <0.9340625f ? -0.072357215f : -0.00831465f)
            : (data[2 /* C6 */] <0.42961016f ? 0.07360283f : -0.0054850676f))
          : (data[2 /* C6 */] <0.5218693f
            ? (data[2 /* C6 */] <0.5000097f ? -0.05524188f : 0.0011599797f)
            : (data[0 /* C4 */] <0.1525f ? -0.108649194f : -0.023426142f))))
      : (data[2 /* C6 */] <0.48892188f
        ? (data[1 /* C5 */] <1.1699219f
          ? (data[1 /* C5 */] <1.1066291f
            ? (data[2 /* C6 */] <0.45839062f ? 0.21454169f : 0.06356461f)
            : (data[0 /* C4 */] <0.158125f ? 0.07311836f : -0.061510436f))
          : (data[2 /* C6 */] <0.47911718f
            ? (data[2 /* C6 */] <0.41147217f ? 0.21828918f : 0.046894386f)
            : 0.25015402f))
        : (data[1 /* C5 */] <1.4074024f
          ? (data[2 /* C6 */] <0.5675078f
            ? (data[1 /* C5 */] <1.3125937f ? -0.010400051f : 0.090477265f)
            : (data[0 /* C4 */] <0.186875f ? -0.043898933f : -4.3184042E-4f))
          : (data[2 /* C6 */] <0.63771486f
            ? (data[2 /* C6 */] <0.5540516f ? 0.20432994f : 0.08648666f)
            : (data[1 /* C5 */] <1.7852578f ? -0.03219758f : 0.03118237f)))));
    return pred;
  }
}


class gbm4_Forest_32 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_32_class_0.score0(fdata);
  }
}
class gbm4_Tree_32_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.112558596f
      ? (data[0 /* C4 */] <0.07749396f
        ? (data[1 /* C5 */] <0.2117041f
          ? (data[1 /* C5 */] <0.17893784f
            ? (data[1 /* C5 */] <0.15682061f ? -0.021186283f : -0.07138153f)
            : 0.02808984f)
          : -0.06197553f)
        : (data[2 /* C6 */] <0.072845705f
          ? (data[1 /* C5 */] <0.16825f
            ? (data[0 /* C4 */] <0.08257812f ? 0.008568074f : -0.042824633f)
            : (data[1 /* C5 */] <0.19299023f ? 0.03998372f : 0.120855674f))
          : (data[1 /* C5 */] <0.21145312f
            ? (data[0 /* C4 */] <0.0875f ? -0.065070055f : -0.009292403f)
            : (data[2 /* C6 */] <0.108429685f ? 0.014305307f : -0.015138439f))))
      : (data[2 /* C6 */] <0.77063864f
        ? (data[1 /* C5 */] <1.9648213f
          ? (data[1 /* C5 */] <1.5963513f
            ? (data[2 /* C6 */] <0.6164375f ? 0.006019451f : -0.035372496f)
            : (data[2 /* C6 */] <0.6493437f ? 0.16726312f : 0.03144096f))
          : 0.345326f)
        : (data[1 /* C5 */] <2.3926144f
          ? (data[1 /* C5 */] <1.7785795f
            ? (data[1 /* C5 */] <1.6385547f ? -0.059319414f : -0.10166282f)
            : (data[2 /* C6 */] <0.8719297f ? 0.042009752f : -0.05264776f))
          : 0.10148168f)));
    return pred;
  }
}


class gbm4_Forest_33 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_33_class_0.score0(fdata);
  }
}
class gbm4_Tree_33_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <1.0883857f
      ? (data[2 /* C6 */] <0.40179297f
        ? (data[1 /* C5 */] <0.8419531f
          ? (data[2 /* C6 */] <0.33579296f
            ? (data[1 /* C5 */] <0.6578594f ? -0.007968944f : 0.018169515f)
            : (data[0 /* C4 */] <0.15890625f ? -0.020999558f : -0.09695669f))
          : (data[0 /* C4 */] <0.13242188f
            ? (data[2 /* C6 */] <0.34928906f ? 0.24507535f : 0.08095721f)
            : (data[2 /* C6 */] <0.36075f ? 0.050506976f : -0.0067892196f)))
        : (data[0 /* C4 */] <0.16773437f
          ? (data[2 /* C6 */] <0.4758828f
            ? (data[1 /* C5 */] <0.96475f ? -0.029150547f : 0.013013814f)
            : (data[2 /* C6 */] <0.52148235f ? -0.033946633f : -0.06929572f))
          : (data[2 /* C6 */] <0.43894142f
            ? (data[2 /* C6 */] <0.41563565f ? -0.06361995f : -0.14496605f)
            : (data[2 /* C6 */] <0.4759142f ? 0.005400906f : -0.05954787f))))
      : (data[2 /* C6 */] <0.5353906f
        ? (data[1 /* C5 */] <1.2377734f
          ? (data[1 /* C5 */] <1.1071591f
            ? (data[2 /* C6 */] <0.45739844f ? 0.18627778f : 0.037149277f)
            : (data[1 /* C5 */] <1.1374733f ? -0.038993403f : 0.030494452f))
          : (data[2 /* C6 */] <0.5257617f
            ? (data[0 /* C4 */] <0.1778125f ? 0.14126274f : 0.004046605f)
            : (data[0 /* C4 */] <0.1778125f ? 0.061240617f : 0.26425958f)))
        : (data[1 /* C5 */] <1.4074024f
          ? (data[1 /* C5 */] <1.1495223f
            ? (data[1 /* C5 */] <1.139905f ? -0.053986937f : -0.12899798f)
            : (data[2 /* C6 */] <0.54684377f ? -0.07957004f : -0.015269978f))
          : (data[2 /* C6 */] <0.70665234f
            ? (data[1 /* C5 */] <1.5639297f ? 0.021533f : 0.10914559f)
            : (data[1 /* C5 */] <1.7852578f ? -0.060411282f : 0.01059285f)))));
    return pred;
  }
}


class gbm4_Forest_34 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_34_class_0.score0(fdata);
  }
}
class gbm4_Tree_34_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <1.2979424f
      ? (data[2 /* C6 */] <0.529582f
        ? (data[1 /* C5 */] <1.0900176f
          ? (data[2 /* C6 */] <0.40898827f
            ? (data[1 /* C5 */] <0.988f ? -0.0033395833f : 0.07913603f)
            : (data[2 /* C6 */] <0.42734948f ? -0.05062489f : -0.011342822f))
          : (data[1 /* C5 */] <1.1060709f
            ? (data[2 /* C6 */] <0.4584219f ? 0.18737496f : 0.04520826f)
            : (data[1 /* C5 */] <1.12087f ? -0.0522987f : 0.028553301f)))
        : (data[1 /* C5 */] <1.1507442f
          ? (data[1 /* C5 */] <1.1361548f
            ? (data[1 /* C5 */] <1.0325929f ? -0.077576555f : -0.04275894f)
            : -0.09012252f)
          : (data[1 /* C5 */] <1.245333f
            ? (data[2 /* C6 */] <0.59875f ? 0.030147612f : -0.046733517f)
            : (data[2 /* C6 */] <0.620625f ? -0.07030467f : 0.021441381f))))
      : (data[2 /* C6 */] <0.5528164f
        ? (data[2 /* C6 */] <0.5448967f
          ? (data[2 /* C6 */] <0.46147528f
            ? 0.16411588f
            : (data[2 /* C6 */] <0.49520406f ? -0.0581425f : 0.10408326f))
          : 0.25955614f)
        : (data[0 /* C4 */] <0.22249024f
          ? (data[2 /* C6 */] <0.7063984f
            ? (data[1 /* C5 */] <1.7879922f ? 0.009145815f : 0.26651073f)
            : (data[1 /* C5 */] <1.7667968f ? -0.053004496f : -0.0038269393f))
          : (data[2 /* C6 */] <0.8086641f ? 0.17720819f : 0.035602048f))));
    return pred;
  }
}


class gbm4_Forest_35 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_35_class_0.score0(fdata);
  }
}
class gbm4_Tree_35_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C6 */] <1.0487251f
      ? (data[1 /* C5 */] <2.119625f
        ? (data[2 /* C6 */] <0.7075293f
          ? (data[1 /* C5 */] <1.5566719f
            ? (data[2 /* C6 */] <0.6633437f ? -2.0341645E-4f : -0.048713528f)
            : (data[1 /* C5 */] <1.71467f ? 0.053205285f : 0.13937874f))
          : (data[1 /* C5 */] <1.7882187f
            ? (data[1 /* C5 */] <1.3948003f ? 0.033525124f : -0.05109565f)
            : (data[1 /* C5 */] <1.8528244f ? 0.05761478f : -0.025694564f)))
        : (data[2 /* C6 */] <0.93010646f ? 0.26556665f : 0.073954366f))
      : (data[1 /* C5 */] <2.2161314f
        ? -0.12040701f
        : (data[2 /* C6 */] <1.1529522f ? 0.028992824f : -0.118578054f)));
    return pred;
  }
}


class gbm4_Forest_36 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_36_class_0.score0(fdata);
  }
}
class gbm4_Tree_36_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.40456933f
      ? (data[1 /* C5 */] <0.3880577f
        ? (data[1 /* C5 */] <0.38202557f
          ? (data[2 /* C6 */] <0.155375f
            ? (data[1 /* C5 */] <0.3345f ? -0.011487734f : 0.036491413f)
            : (data[0 /* C4 */] <0.10625f ? -0.024685113f : -0.08111473f))
          : 0.14734857f)
        : (data[1 /* C5 */] <0.39875162f
          ? (data[2 /* C6 */] <0.16674219f ? -0.09963637f : -0.07215187f)
          : -0.041448064f))
      : (data[2 /* C6 */] <0.16654493f
        ? (data[1 /* C5 */] <0.45700294f
          ? (data[0 /* C4 */] <0.12726563f
            ? (data[2 /* C6 */] <0.16278125f ? 0.24119323f : 0.035177473f)
            : -0.029580945f)
          : 0.20842668f)
        : (data[2 /* C6 */] <0.98213047f
          ? (data[1 /* C5 */] <2.106914f
            ? (data[2 /* C6 */] <0.75242186f ? 0.0029859268f : -0.030251723f)
            : 0.2245477f)
          : (data[0 /* C4 */] <0.19421875f
            ? -0.0036507086f
            : (data[2 /* C6 */] <1.1375625f ? -0.09758412f : -0.021114064f)))));
    return pred;
  }
}


class gbm4_Forest_37 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_37_class_0.score0(fdata);
  }
}
class gbm4_Tree_37_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <1.405478f
      ? (data[2 /* C6 */] <0.5353906f
        ? (data[1 /* C5 */] <1.2072735f
          ? (data[0 /* C4 */] <0.11476562f
            ? (data[2 /* C6 */] <0.22628126f ? -0.008535681f : -0.02944307f)
            : (data[2 /* C6 */] <0.1178125f ? 0.09053615f : 7.9117E-4f))
          : (data[2 /* C6 */] <0.48910937f
            ? (data[2 /* C6 */] <0.47110522f ? 0.016174477f : 0.2617711f)
            : (data[2 /* C6 */] <0.49627978f ? -0.13334884f : 0.050974373f)))
        : (data[2 /* C6 */] <0.5467378f
          ? (data[1 /* C5 */] <1.247916f
            ? (data[1 /* C5 */] <1.1332854f ? -0.068391025f : 0.0013010502f)
            : -0.16174777f)
          : (data[2 /* C6 */] <0.56322664f
            ? (data[1 /* C5 */] <1.2668438f ? -0.014190686f : 0.12641037f)
            : (data[0 /* C4 */] <0.1578125f ? -0.010391684f : -0.03284121f))))
      : (data[2 /* C6 */] <0.62832814f
        ? (data[1 /* C5 */] <1.4226347f
          ? 0.18461254f
          : (data[2 /* C6 */] <0.5210918f
            ? -0.034435477f
            : (data[2 /* C6 */] <0.5536654f ? 0.24970357f : 0.0625848f)))
        : (data[0 /* C4 */] <0.22249024f
          ? (data[1 /* C5 */] <1.5506172f
            ? (data[2 /* C6 */] <0.65632814f ? -0.08303832f : -0.033101078f)
            : (data[2 /* C6 */] <0.79046875f ? 0.036602806f : -0.03525662f))
          : (data[1 /* C5 */] <2.1936016f ? 0.17490657f : 0.02899353f))));
    return pred;
  }
}


class gbm4_Forest_38 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_38_class_0.score0(fdata);
  }
}
class gbm4_Tree_38_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.23229004f
      ? (data[0 /* C4 */] <0.22230883f
        ? (data[2 /* C6 */] <1.0465468f
          ? (data[1 /* C5 */] <2.0762188f
            ? (data[2 /* C6 */] <0.8177969f ? 4.1989068E-4f : -0.046746384f)
            : (data[2 /* C6 */] <0.94848436f ? 0.2247487f : 0.02712792f))
          : (data[0 /* C4 */] <0.20796876f ? -0.0462308f : -0.13186763f))
        : (data[1 /* C5 */] <1.7556581f ? 0.0043152445f : 0.24370183f))
      : -0.09908273f);
    return pred;
  }
}


class gbm4_Forest_39 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_39_class_0.score0(fdata);
  }
}
class gbm4_Tree_39_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.8043814f
      ? (data[2 /* C6 */] <0.30595118f
        ? (data[1 /* C5 */] <0.65675783f
          ? (data[2 /* C6 */] <0.2626797f
            ? (data[1 /* C5 */] <0.53378123f ? -0.007487922f : 0.020987403f)
            : (data[0 /* C4 */] <0.1373047f ? -0.027073426f : -0.05982144f))
          : (data[0 /* C4 */] <0.16773437f
            ? (data[1 /* C5 */] <0.78203905f ? 0.048738945f : -0.07004881f)
            : -0.061689276f))
        : (data[1 /* C5 */] <0.8008672f
          ? (data[1 /* C5 */] <0.7900021f
            ? (data[0 /* C4 */] <0.1528125f ? -0.037589617f : 0.018184548f)
            : (data[1 /* C5 */] <0.79468864f ? -0.03738622f : 0.045203287f))
          : -0.09924148f))
      : (data[2 /* C6 */] <0.3611328f
        ? (data[1 /* C5 */] <0.89923435f
          ? (data[1 /* C5 */] <0.86888975f
            ? (data[2 /* C6 */] <0.31521875f ? 0.10993724f : 0.011210226f)
            : (data[0 /* C4 */] <0.15734375f ? 0.009760139f : -0.10515416f))
          : (data[0 /* C4 */] <0.16226563f
            ? (data[0 /* C4 */] <0.15235962f ? 0.057915747f : 0.19932139f)
            : (data[2 /* C6 */] <0.32271874f ? -0.078450836f : 0.04414306f)))
        : (data[1 /* C5 */] <1.0018632f
          ? (data[0 /* C4 */] <0.18296875f
            ? (data[0 /* C4 */] <0.122686766f ? 0.12089175f : -0.01683114f)
            : -0.19659287f)
          : (data[2 /* C6 */] <0.43190625f
            ? (data[0 /* C4 */] <0.1946875f ? 0.039281957f : 0.1908049f)
            : (data[1 /* C5 */] <1.1449219f ? -0.014980112f : 0.007976902f)))));
    return pred;
  }
}


class gbm4_Forest_40 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_40_class_0.score0(fdata);
  }
}
class gbm4_Tree_40_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.23229004f
      ? (data[0 /* C4 */] <0.22230883f
        ? (data[2 /* C6 */] <1.0465468f
          ? (data[1 /* C5 */] <2.0762188f
            ? (data[2 /* C6 */] <0.76878905f ? 6.291193E-4f : -0.034893524f)
            : (data[2 /* C6 */] <0.94848436f ? 0.20147617f : 0.023617445f))
          : (data[0 /* C4 */] <0.20796876f ? -0.042405326f : -0.11947855f))
        : (data[1 /* C5 */] <1.7556581f ? -0.0025394147f : 0.218534f))
      : -0.090704374f);
    return pred;
  }
}


class gbm4_Forest_41 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_41_class_0.score0(fdata);
  }
}
class gbm4_Tree_41_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <1.405478f
      ? (data[2 /* C6 */] <0.5353906f
        ? (data[1 /* C5 */] <1.2072735f
          ? (data[2 /* C6 */] <0.5183125f
            ? (data[1 /* C5 */] <0.9990625f ? -0.0035795146f : 0.014782193f)
            : (data[2 /* C6 */] <0.52391845f ? -0.071835384f : -0.029353756f))
          : (data[2 /* C6 */] <0.48910937f
            ? (data[2 /* C6 */] <0.47110522f ? 0.012268737f : 0.23469146f)
            : (data[2 /* C6 */] <0.49627978f ? -0.12091655f : 0.04523938f)))
        : (data[2 /* C6 */] <0.5467378f
          ? (data[1 /* C5 */] <1.247916f
            ? (data[1 /* C5 */] <1.1674734f ? -0.050768394f : 0.011914574f)
            : -0.14647554f)
          : (data[2 /* C6 */] <0.56322664f
            ? (data[1 /* C5 */] <1.3046992f ? -0.008402996f : 0.12595077f)
            : (data[1 /* C5 */] <1.3632032f ? -0.030456768f : -0.0069210036f))))
      : (data[2 /* C6 */] <0.6399453f
        ? (data[0 /* C4 */] <0.16759765f
          ? 0.18801141f
          : (data[1 /* C5 */] <1.5701874f
            ? (data[2 /* C6 */] <0.5894531f ? 0.117705f : -0.049855687f)
            : (data[2 /* C6 */] <0.582375f ? -0.012612588f : 0.19846274f)))
        : (data[1 /* C5 */] <1.7941445f
          ? (data[2 /* C6 */] <0.7000899f
            ? (data[2 /* C6 */] <0.66005296f ? -0.04333576f : 0.021286039f)
            : (data[1 /* C5 */] <1.6057891f ? -0.060674217f : -0.0314922f))
          : (data[1 /* C5 */] <1.8183169f
            ? 0.29340765f
            : (data[2 /* C6 */] <0.78823435f ? 0.080884635f : -0.015699318f)))));
    return pred;
  }
}


class gbm4_Forest_42 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_42_class_0.score0(fdata);
  }
}
class gbm4_Tree_42_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <2.4449892f
      ? (data[2 /* C6 */] <0.7938731f
        ? (data[1 /* C5 */] <1.9581094f
          ? (data[1 /* C5 */] <1.8511347f
            ? (data[1 /* C5 */] <1.7933491f ? -1.917045E-4f : 0.22306138f)
            : -0.19426377f)
          : 0.2240343f)
        : (data[2 /* C6 */] <1.0495856f
          ? (data[2 /* C6 */] <0.9539285f
            ? (data[1 /* C5 */] <1.8806406f ? -0.049895767f : -0.0080844555f)
            : (data[2 /* C6 */] <1.0002142f ? 0.07171995f : -0.012148828f))
          : (data[2 /* C6 */] <1.1084555f ? -0.09679675f : -0.03822807f)))
      : 0.10026427f);
    return pred;
  }
}


class gbm4_Forest_43 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_43_class_0.score0(fdata);
  }
}
class gbm4_Tree_43_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.23229004f
      ? (data[0 /* C4 */] <0.22230883f
        ? (data[2 /* C6 */] <1.0465468f
          ? (data[1 /* C5 */] <2.0762188f
            ? (data[1 /* C5 */] <1.8493512f ? 2.602111E-4f : -0.043881964f)
            : (data[2 /* C6 */] <0.94848436f ? 0.17277233f : 0.021366112f))
          : (data[0 /* C4 */] <0.20796876f ? -0.032806415f : -0.10650631f))
        : (data[1 /* C5 */] <1.7556581f ? -0.003991127f : 0.19276932f))
      : -0.085122846f);
    return pred;
  }
}


class gbm4_Forest_44 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_44_class_0.score0(fdata);
  }
}
class gbm4_Tree_44_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <2.3884642f
      ? (data[2 /* C6 */] <0.77063864f
        ? (data[1 /* C5 */] <1.9535234f
          ? (data[1 /* C5 */] <1.4046575f
            ? (data[2 /* C6 */] <0.5657344f ? -1.4294208E-4f : -0.023258409f)
            : (data[2 /* C6 */] <0.6378281f ? 0.06466787f : -0.005983173f))
          : 0.20629892f)
        : (data[1 /* C5 */] <1.9814024f
          ? (data[1 /* C5 */] <1.9229228f
            ? (data[0 /* C4 */] <0.20277344f ? -0.03852971f : 0.02679751f)
            : 0.11836321f)
          : (data[2 /* C6 */] <0.8764492f
            ? -0.16037038f
            : (data[2 /* C6 */] <0.9765498f ? 0.01937754f : -0.047017653f))))
      : 0.08817496f);
    return pred;
  }
}


class gbm4_Forest_45 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_45_class_0.score0(fdata);
  }
}
class gbm4_Tree_45_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.4321426f
      ? (data[2 /* C6 */] <0.16073632f
        ? (data[1 /* C5 */] <0.4013008f
          ? (data[1 /* C5 */] <0.33579051f
            ? (data[0 /* C4 */] <0.1225f ? -0.008040328f : -0.10400023f)
            : (data[2 /* C6 */] <0.14803906f ? 0.06910497f : -0.020044358f))
          : 0.122477576f)
        : (data[0 /* C4 */] <0.112558596f
          ? (data[2 /* C6 */] <0.17973828f
            ? (data[1 /* C5 */] <0.4055703f ? -0.01878331f : 0.04051747f)
            : (data[2 /* C6 */] <0.2043681f ? -0.05584245f : -0.01705556f))
          : (data[1 /* C5 */] <0.37801564f
            ? -0.11569064f
            : (data[1 /* C5 */] <0.40768275f ? -0.00427027f : -0.08386683f))))
      : (data[2 /* C6 */] <0.16654493f
        ? (data[1 /* C5 */] <0.45586914f ? 0.074855074f : 0.18794693f)
        : (data[2 /* C6 */] <0.20267847f
          ? (data[0 /* C4 */] <0.13695313f
            ? (data[1 /* C5 */] <0.48640624f ? 0.011120314f : 0.10672935f)
            : (data[2 /* C6 */] <0.17975782f ? 0.065559596f : -0.047025993f))
          : (data[1 /* C5 */] <0.5446719f
            ? (data[0 /* C4 */] <0.11953125f ? -0.0076751853f : -0.048151612f)
            : (data[2 /* C6 */] <0.24315625f ? 0.04115596f : 0.0010545827f)))));
    return pred;
  }
}


class gbm4_Forest_46 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_46_class_0.score0(fdata);
  }
}
class gbm4_Tree_46_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.23229004f
      ? (data[0 /* C4 */] <0.22230883f
        ? (data[1 /* C5 */] <0.7189043f
          ? (data[2 /* C6 */] <0.2798125f
            ? (data[1 /* C5 */] <0.6289375f ? -0.004614173f : 0.045988776f)
            : (data[0 /* C4 */] <0.15289062f ? -0.022438148f : -0.11232181f))
          : (data[2 /* C6 */] <0.31466407f
            ? (data[2 /* C6 */] <0.23808752f ? -0.09558806f : 0.05384022f)
            : (data[1 /* C5 */] <0.99239063f ? -0.0094212135f : 0.0053713573f)))
        : (data[1 /* C5 */] <1.7556581f ? -0.0059082694f : 0.17343141f))
      : -0.079312354f);
    return pred;
  }
}


class gbm4_Forest_47 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_47_class_0.score0(fdata);
  }
}
class gbm4_Tree_47_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <2.4959998f
      ? (data[2 /* C6 */] <0.77063864f
        ? (data[1 /* C5 */] <1.9574317f
          ? (data[1 /* C5 */] <1.5907882f
            ? (data[2 /* C6 */] <0.69790626f ? -3.2120172E-4f : -0.048241306f)
            : (data[2 /* C6 */] <0.64984375f ? 0.09454221f : 0.0056446455f))
          : 0.21698739f)
        : (data[1 /* C5 */] <1.9866172f
          ? (data[1 /* C5 */] <1.9225433f
            ? (data[0 /* C4 */] <0.20277344f ? -0.035319358f : 0.022354795f)
            : 0.10435646f)
          : (data[1 /* C5 */] <2.075542f
            ? -0.123262435f
            : (data[1 /* C5 */] <2.1472065f ? 0.044658594f : -0.045494907f))))
      : 0.08614693f);
    return pred;
  }
}


class gbm4_Forest_48 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_48_class_0.score0(fdata);
  }
}
class gbm4_Tree_48_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[0 /* C4 */] <0.23229004f
      ? (data[0 /* C4 */] <0.22230883f
        ? (data[2 /* C6 */] <1.1017286f
          ? (data[1 /* C5 */] <2.0762188f
            ? (data[1 /* C5 */] <1.8493512f ? 3.6358243E-4f : -0.048604563f)
            : (data[2 /* C6 */] <0.94115627f ? 0.1464606f : 0.01426971f))
          : -0.06820352f)
        : (data[1 /* C5 */] <1.7556581f ? -0.0063761417f : 0.15545216f))
      : -0.07337841f);
    return pred;
  }
}


class gbm4_Forest_49 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm4_Tree_49_class_0.score0(fdata);
  }
}
class gbm4_Tree_49_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C5 */] <0.8043814f
      ? (data[1 /* C5 */] <0.80124706f
        ? (data[0 /* C4 */] <0.17214844f
          ? (data[0 /* C4 */] <0.14726761f
            ? (data[2 /* C6 */] <0.27115625f ? -0.001770925f : -0.02230722f)
            : (data[1 /* C5 */] <0.7630703f ? 0.019776106f : 0.08512152f))
          : -0.089871675f)
        : -0.12015432f)
      : (data[2 /* C6 */] <0.40179297f
        ? (data[1 /* C5 */] <1.1281757f
          ? (data[1 /* C5 */] <0.82472974f
            ? (data[1 /* C5 */] <0.8157212f ? 0.023666348f : 0.14176133f)
            : (data[1 /* C5 */] <0.83408195f ? -0.084517255f : 0.021726377f))
          : 0.11883661f)
        : (data[1 /* C5 */] <1.0887032f
          ? (data[0 /* C4 */] <0.16734375f
            ? (data[2 /* C6 */] <0.44723436f ? 8.111036E-4f : -0.025912734f)
            : (data[1 /* C5 */] <1.0271875f ? -0.08636587f : -0.014915955f))
          : (data[2 /* C6 */] <0.5038125f
            ? (data[0 /* C4 */] <0.1790625f ? 0.05569757f : 0.003098737f)
            : (data[1 /* C5 */] <1.4688594f ? -0.011664919f : 0.010352914f)))));
    return pred;
  }
}


