package ai.h2o.hive.udf.models;/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2016-03-16T13:29:29.798-07:00
  3.8.1.3
  
  Standalone prediction code with sample test data for GBMModel named gbm6

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/gbm6 > gbm6.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m gbm6.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="gbm6", algorithm="gbm")
public class gbm6 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 3; }
  public int nclasses() { return 1; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_gbm6.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* C6 */ null,
    /* C7 */ null,
    /* C8 */ null,
    /* C9 */ null
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {1.0};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {1.0};

  public gbm6() { super(NAMES,DOMAINS); }
  public String getUUID() { return Long.toString(7876244725979288127L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    double[] fdata = hex.genmodel.GenModel.SharedTree_clean(data);
    gbm6_Forest_0.score0(fdata,preds);
    gbm6_Forest_1.score0(fdata,preds);
    gbm6_Forest_2.score0(fdata,preds);
    gbm6_Forest_3.score0(fdata,preds);
    gbm6_Forest_4.score0(fdata,preds);
    gbm6_Forest_5.score0(fdata,preds);
    gbm6_Forest_6.score0(fdata,preds);
    gbm6_Forest_7.score0(fdata,preds);
    gbm6_Forest_8.score0(fdata,preds);
    gbm6_Forest_9.score0(fdata,preds);
    gbm6_Forest_10.score0(fdata,preds);
    gbm6_Forest_11.score0(fdata,preds);
    gbm6_Forest_12.score0(fdata,preds);
    gbm6_Forest_13.score0(fdata,preds);
    gbm6_Forest_14.score0(fdata,preds);
    gbm6_Forest_15.score0(fdata,preds);
    gbm6_Forest_16.score0(fdata,preds);
    gbm6_Forest_17.score0(fdata,preds);
    gbm6_Forest_18.score0(fdata,preds);
    gbm6_Forest_19.score0(fdata,preds);
    gbm6_Forest_20.score0(fdata,preds);
    gbm6_Forest_21.score0(fdata,preds);
    gbm6_Forest_22.score0(fdata,preds);
    gbm6_Forest_23.score0(fdata,preds);
    gbm6_Forest_24.score0(fdata,preds);
    gbm6_Forest_25.score0(fdata,preds);
    gbm6_Forest_26.score0(fdata,preds);
    gbm6_Forest_27.score0(fdata,preds);
    gbm6_Forest_28.score0(fdata,preds);
    gbm6_Forest_29.score0(fdata,preds);
    gbm6_Forest_30.score0(fdata,preds);
    gbm6_Forest_31.score0(fdata,preds);
    gbm6_Forest_32.score0(fdata,preds);
    gbm6_Forest_33.score0(fdata,preds);
    gbm6_Forest_34.score0(fdata,preds);
    gbm6_Forest_35.score0(fdata,preds);
    gbm6_Forest_36.score0(fdata,preds);
    gbm6_Forest_37.score0(fdata,preds);
    gbm6_Forest_38.score0(fdata,preds);
    gbm6_Forest_39.score0(fdata,preds);
    gbm6_Forest_40.score0(fdata,preds);
    gbm6_Forest_41.score0(fdata,preds);
    gbm6_Forest_42.score0(fdata,preds);
    gbm6_Forest_43.score0(fdata,preds);
    gbm6_Forest_44.score0(fdata,preds);
    gbm6_Forest_45.score0(fdata,preds);
    gbm6_Forest_46.score0(fdata,preds);
    gbm6_Forest_47.score0(fdata,preds);
    gbm6_Forest_48.score0(fdata,preds);
    gbm6_Forest_49.score0(fdata,preds);
    preds[0] += 9.933684462532918;
    preds[0] = preds[0];
    return preds;
  }
}
// The class representing training column names
class NamesHolder_gbm6 implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    NamesHolder_gbm6_0.fill(VALUES);
  }
  static final class NamesHolder_gbm6_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "C6";
      sa[1] = "C7";
      sa[2] = "C8";
    }
  }
}

class gbm6_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_0_class_0.score0(fdata);
  }
}
class gbm6_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.1671167f
      ? (data[2 /* C8 */] <0.058754213f
        ? (data[2 /* C8 */] <0.026548719f
          ? (data[1 /* C7 */] <0.010445313f
            ? (data[0 /* C6 */] <0.0071171876f ? -0.6779838f : -0.5729139f)
            : (data[2 /* C8 */] <0.017578125f ? -0.54042727f : -0.48655027f))
          : (data[2 /* C8 */] <0.039404117f
            ? (data[1 /* C7 */] <0.0283125f ? -0.40670177f : -0.45336846f)
            : (data[0 /* C6 */] <0.0710625f ? -0.29849663f : -0.36908272f)))
        : (data[2 /* C8 */] <0.1116086f
          ? (data[1 /* C7 */] <0.100125f
            ? (data[0 /* C6 */] <0.15689844f ? -0.22919318f : -0.2905113f)
            : -0.10670178f)
          : (data[0 /* C6 */] <0.2306875f
            ? (data[2 /* C8 */] <0.1395f ? -0.117089376f : -0.024494272f)
            : (data[1 /* C7 */] <0.143875f ? -0.21090092f : -0.08796304f))))
      : (data[2 /* C8 */] <0.37495103f
        ? (data[2 /* C8 */] <0.24934591f
          ? (data[0 /* C6 */] <0.2451875f
            ? (data[2 /* C8 */] <0.1942422f ? 0.059461746f : 0.29677242f)
            : (data[0 /* C6 */] <0.30153906f ? 0.027887596f : -0.069298424f))
          : (data[0 /* C6 */] <0.432875f
            ? (data[2 /* C8 */] <0.2885625f ? 0.16612062f : 0.3273689f)
            : (data[2 /* C8 */] <0.29051563f ? -0.0379229f : 0.06892958f)))
        : (data[0 /* C6 */] <0.5380586f
          ? (data[2 /* C8 */] <0.50789064f
            ? (data[0 /* C6 */] <0.39582032f ? 0.6780601f : 0.37806013f)
            : (data[2 /* C8 */] <0.54772705f ? 0.75663155f : 0.8520861f))
          : (data[2 /* C8 */] <0.5669531f
            ? (data[2 /* C8 */] <0.44398317f ? 0.122702986f : 0.23668082f)
            : (data[0 /* C6 */] <0.7610391f ? 0.69725657f : 0.33031577f)))));
    return pred;
  }
}


class gbm6_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_1_class_0.score0(fdata);
  }
}
class gbm6_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.18965624f
      ? (data[2 /* C8 */] <0.06764868f
        ? (data[2 /* C8 */] <0.02643495f
          ? (data[1 /* C7 */] <0.010445313f
            ? (data[0 /* C6 */] <0.0071171876f ? -0.6101855f : -0.5156225f)
            : (data[0 /* C6 */] <0.023429688f ? -0.41394246f : -0.46709216f))
          : (data[2 /* C8 */] <0.047609117f
            ? (data[2 /* C8 */] <0.03955868f ? -0.3748737f : -0.32414275f)
            : (data[0 /* C6 */] <0.0710625f ? -0.18094444f : -0.29777902f)))
        : (data[2 /* C8 */] <0.119054705f
          ? (data[0 /* C6 */] <0.15046094f
            ? (data[2 /* C8 */] <0.098679684f ? -0.19966727f : -0.08832669f)
            : (data[2 /* C8 */] <0.09429687f ? -0.30963656f : -0.20865344f))
          : (data[0 /* C6 */] <0.23453125f
            ? (data[2 /* C8 */] <0.15121876f ? -0.07996249f : 0.04327773f)
            : (data[2 /* C8 */] <0.158875f ? -0.19773276f : -0.09066724f))))
      : (data[2 /* C8 */] <0.40941685f
        ? (data[0 /* C6 */] <0.39836133f
          ? (data[2 /* C8 */] <0.28923437f
            ? (data[0 /* C6 */] <0.3075547f ? 0.18386622f : 0.02898745f)
            : (data[2 /* C8 */] <0.36365503f ? 0.3047672f : 0.56365186f))
          : (data[2 /* C8 */] <0.29265624f
            ? (data[2 /* C8 */] <0.25736815f ? -0.095491275f : -0.011100524f)
            : (data[0 /* C6 */] <0.4426875f ? 0.25258237f : 0.071944095f)))
        : (data[0 /* C6 */] <0.5883496f
          ? (data[2 /* C8 */] <0.5071992f
            ? (data[0 /* C6 */] <0.48972657f ? 0.52457553f : 0.3854521f)
            : (data[2 /* C8 */] <0.5913635f ? 0.7270809f : 0.4891644f))
          : (data[2 /* C8 */] <0.693293f
            ? (data[2 /* C8 */] <0.5691335f ? 0.16417535f : 0.346781f)
            : 0.7298094f))));
    return pred;
  }
}


class gbm6_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_2_class_0.score0(fdata);
  }
}
class gbm6_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.17887646f
      ? (data[2 /* C8 */] <0.067669734f
        ? (data[2 /* C8 */] <0.026442887f
          ? (data[2 /* C8 */] <0.015238075f
            ? (data[0 /* C6 */] <0.0071171876f ? -0.5491669f : -0.46073633f)
            : (data[0 /* C6 */] <0.023429688f ? -0.33699375f : -0.41646412f))
          : (data[2 /* C8 */] <0.04761296f
            ? (data[2 /* C8 */] <0.039561022f ? -0.33738628f : -0.2917285f)
            : (data[0 /* C6 */] <0.0710625f ? -0.16284999f : -0.2680011f)))
        : (data[2 /* C8 */] <0.11182867f
          ? (data[0 /* C6 */] <0.12442187f
            ? (data[2 /* C8 */] <0.082953125f ? -0.18798247f : -0.100709274f)
            : (data[2 /* C8 */] <0.09450781f ? -0.25479454f : -0.18125938f))
          : (data[0 /* C6 */] <0.22630468f
            ? (data[2 /* C8 */] <0.15148437f ? -0.07818448f : 0.043015298f)
            : (data[2 /* C8 */] <0.14421093f ? -0.20491058f : -0.11020087f))))
      : (data[2 /* C8 */] <0.35959098f
        ? (data[0 /* C6 */] <0.32571876f
          ? (data[2 /* C8 */] <0.23963672f
            ? (data[0 /* C6 */] <0.22886719f ? 0.17354175f : 0.035922088f)
            : (data[2 /* C8 */] <0.28289795f ? 0.24805726f : 0.36897454f))
          : (data[2 /* C8 */] <0.2593789f
            ? (data[2 /* C8 */] <0.23441675f ? -0.08841734f : -0.014713285f)
            : (data[0 /* C6 */] <0.44890624f ? 0.14612654f : 0.023288073f)))
        : (data[0 /* C6 */] <0.5380586f
          ? (data[2 /* C8 */] <0.50613284f
            ? (data[0 /* C6 */] <0.4154375f ? 0.4839812f : 0.2717345f)
            : (data[2 /* C8 */] <0.5477902f ? 0.6082603f : 0.7049838f))
          : (data[2 /* C8 */] <0.5666016f
            ? (data[2 /* C8 */] <0.44393188f ? 0.09058562f : 0.19423729f)
            : (data[0 /* C6 */] <0.7610391f ? 0.5798724f : 0.2550229f)))));
    return pred;
  }
}


class gbm6_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_3_class_0.score0(fdata);
  }
}
class gbm6_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.18965624f
      ? (data[2 /* C8 */] <0.06764868f
        ? (data[2 /* C8 */] <0.02643495f
          ? (data[1 /* C7 */] <0.010445313f
            ? (data[0 /* C6 */] <0.0071171876f ? -0.49425027f : -0.4184691f)
            : (data[2 /* C8 */] <0.021789063f ? -0.3824388f : -0.3342333f))
          : (data[2 /* C8 */] <0.047609117f
            ? (data[2 /* C8 */] <0.038753636f ? -0.30412456f : -0.26311204f)
            : (data[0 /* C6 */] <0.0710625f ? -0.14656496f : -0.24120095f)))
        : (data[2 /* C8 */] <0.119054705f
          ? (data[0 /* C6 */] <0.15046094f
            ? (data[2 /* C8 */] <0.11023437f ? -0.15205954f : 0.009384331f)
            : (data[2 /* C8 */] <0.0935f ? -0.25438616f : -0.17257164f))
          : (data[0 /* C6 */] <0.19496875f
            ? (data[2 /* C8 */] <0.1391875f ? -0.05441625f : 0.053856466f)
            : (data[2 /* C8 */] <0.1523125f ? -0.14053783f : -0.061266698f))))
      : (data[2 /* C8 */] <0.40941685f
        ? (data[0 /* C6 */] <0.39836133f
          ? (data[2 /* C8 */] <0.24817188f
            ? (data[0 /* C6 */] <0.2756328f ? 0.16217148f : -0.0100305155f)
            : (data[2 /* C8 */] <0.35373986f ? 0.18973292f : 0.40028316f))
          : (data[2 /* C8 */] <0.29265624f
            ? (data[2 /* C8 */] <0.25736815f ? -0.08108955f : -0.016155621f)
            : (data[0 /* C6 */] <0.4426875f ? 0.20799024f : 0.058160175f)))
        : (data[0 /* C6 */] <0.63864064f
          ? (data[2 /* C8 */] <0.5071992f
            ? (data[0 /* C6 */] <0.5888516f ? 0.3718061f : 0.1998623f)
            : (data[2 /* C8 */] <0.5913635f ? 0.6139061f : 0.4269766f))
          : (data[2 /* C8 */] <0.693293f
            ? (data[2 /* C8 */] <0.5691335f ? 0.1058434f : 0.24671017f)
            : 0.6100479f))));
    return pred;
  }
}


class gbm6_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_4_class_0.score0(fdata);
  }
}
class gbm6_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.19455615f
      ? (data[2 /* C8 */] <0.08275703f
        ? (data[2 /* C8 */] <0.03879571f
          ? (data[2 /* C8 */] <0.021750405f
            ? (data[0 /* C6 */] <0.00871875f ? -0.42959443f : -0.35864174f)
            : (data[1 /* C7 */] <0.028765624f ? -0.274048f : -0.3088931f))
          : (data[2 /* C8 */] <0.058769938f
            ? (data[1 /* C7 */] <0.028320312f ? -0.29836458f : -0.20676613f)
            : (data[0 /* C6 */] <0.08053125f ? -0.09577409f : -0.19903077f)))
        : (data[2 /* C8 */] <0.13971975f
          ? (data[0 /* C6 */] <0.12573437f
            ? (data[2 /* C8 */] <0.11036719f ? -0.09100348f : 0.120906256f)
            : (data[2 /* C8 */] <0.10771875f ? -0.16890833f : -0.11427063f))
          : (data[0 /* C6 */] <0.20485938f
            ? (data[1 /* C7 */] <0.13621876f ? 0.025553811f : 0.21111698f)
            : (data[1 /* C7 */] <0.16585937f ? -0.08315771f : 0.0034898992f))))
      : (data[2 /* C8 */] <0.38925263f
        ? (data[0 /* C6 */] <0.32571876f
          ? (data[2 /* C8 */] <0.23895313f
            ? (data[0 /* C6 */] <0.25394532f ? 0.18067025f : 0.03708789f)
            : (data[2 /* C8 */] <0.28964186f ? 0.20666118f : 0.31632778f))
          : (data[2 /* C8 */] <0.29048437f
            ? (data[2 /* C8 */] <0.23379053f ? -0.06769997f : 0.0047485223f)
            : (data[0 /* C6 */] <0.43866405f ? 0.22139464f : 0.039269637f)))
        : (data[0 /* C6 */] <0.565998f
          ? (data[2 /* C8 */] <0.41402343f
            ? (data[0 /* C6 */] <0.47360155f ? 0.35954818f : 0.16979688f)
            : (data[1 /* C7 */] <0.23410937f ? 0.5506975f : 0.36065012f))
          : (data[2 /* C8 */] <0.6926953f
            ? (data[0 /* C6 */] <0.75328124f ? 0.1767845f : 0.06961347f)
            : 0.55760264f))));
    return pred;
  }
}


class gbm6_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_5_class_0.score0(fdata);
  }
}
class gbm6_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.1671167f
      ? (data[2 /* C8 */] <0.058754213f
        ? (data[2 /* C8 */] <0.023753103f
          ? (data[0 /* C6 */] <0.00871875f
            ? -0.38663495f
            : (data[1 /* C7 */] <0.013796875f ? -0.3321265f : -0.2910791f))
          : (data[1 /* C7 */] <0.031382814f
            ? (data[1 /* C7 */] <0.024693787f ? -0.25758374f : -0.22637932f)
            : (data[0 /* C6 */] <0.063625f ? -0.12919934f : -0.21909669f)))
        : (data[2 /* C8 */] <0.1116086f
          ? (data[1 /* C7 */] <0.100125f
            ? (data[0 /* C6 */] <0.15689844f ? -0.13365671f : -0.18160066f)
            : -0.027684264f)
          : (data[0 /* C6 */] <0.16199219f
            ? (data[0 /* C6 */] <0.122339234f ? 0.14607371f : -0.009335175f)
            : (data[0 /* C6 */] <0.23211865f ? -0.065409034f : -0.12380682f))))
      : (data[2 /* C8 */] <0.32421982f
        ? (data[0 /* C6 */] <0.39836133f
          ? (data[2 /* C8 */] <0.23963672f
            ? (data[0 /* C6 */] <0.23375f ? 0.11062719f : -0.016172528f)
            : (data[0 /* C6 */] <0.252f ? 0.36401317f : 0.12043775f))
          : (data[2 /* C8 */] <0.25919923f
            ? (data[1 /* C7 */] <0.26215625f ? -0.07932694f : 0.03775882f)
            : (data[0 /* C6 */] <0.4486875f ? 0.045923367f : -0.008487669f)))
        : (data[0 /* C6 */] <0.415125f
          ? (data[2 /* C8 */] <0.36703125f
            ? (data[2 /* C8 */] <0.33222413f ? 0.3863899f : 0.2067437f)
            : (data[1 /* C7 */] <0.2056875f ? 0.5364563f : 0.35237807f))
          : (data[2 /* C8 */] <0.44146094f
            ? (data[0 /* C6 */] <0.58307815f ? 0.124951646f : 0.034646276f)
            : (data[0 /* C6 */] <0.76741403f ? 0.28273386f : 0.09275798f)))));
    return pred;
  }
}


class gbm6_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_6_class_0.score0(fdata);
  }
}
class gbm6_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.19455615f
      ? (data[2 /* C8 */] <0.08275703f
        ? (data[2 /* C8 */] <0.03879571f
          ? (data[2 /* C8 */] <0.021750405f
            ? (data[0 /* C6 */] <0.00871875f ? -0.34797147f : -0.29057777f)
            : (data[1 /* C7 */] <0.028765624f ? -0.22134376f : -0.25793192f))
          : (data[0 /* C6 */] <0.0781875f
            ? (data[2 /* C8 */] <0.06414844f ? -0.15977712f : -0.010634125f)
            : (data[2 /* C8 */] <0.07230469f ? -0.18979128f : -0.14779928f)))
        : (data[2 /* C8 */] <0.13971975f
          ? (data[0 /* C6 */] <0.16035156f
            ? (data[2 /* C8 */] <0.11036719f ? -0.09470882f : 0.0021122221f)
            : (data[1 /* C7 */] <0.13071875f ? -0.12911907f : -0.003109473f))
          : (data[0 /* C6 */] <0.22958593f
            ? (data[1 /* C7 */] <0.12351563f ? -0.004017386f : 0.08458178f)
            : (data[1 /* C7 */] <0.16585937f ? -0.08332105f : -2.828439E-5f))))
      : (data[2 /* C8 */] <0.4098303f
        ? (data[0 /* C6 */] <0.31454298f
          ? (data[2 /* C8 */] <0.23354296f
            ? (data[0 /* C6 */] <0.24221875f ? 0.16956173f : 0.04456639f)
            : (data[1 /* C7 */] <0.12153125f ? 0.024987621f : 0.21137926f))
          : (data[2 /* C8 */] <0.31398046f
            ? (data[2 /* C8 */] <0.25449023f ? -0.034856033f : 0.022739524f)
            : (data[0 /* C6 */] <0.42616406f ? 0.24156278f : 0.052777182f)))
        : (data[0 /* C6 */] <0.63864064f
          ? (data[2 /* C8 */] <0.5076172f
            ? (data[0 /* C6 */] <0.5888516f ? 0.2783144f : 0.14553683f)
            : (data[2 /* C8 */] <0.5916672f ? 0.4886174f : 0.32095063f))
          : (data[2 /* C8 */] <0.6935547f
            ? (data[2 /* C8 */] <0.5783606f ? 0.07169425f : 0.20443977f)
            : 0.47377747f))));
    return pred;
  }
}


class gbm6_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_7_class_0.score0(fdata);
  }
}
class gbm6_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.19455615f
      ? (data[2 /* C8 */] <0.07219927f
        ? (data[2 /* C8 */] <0.026493296f
          ? (data[2 /* C8 */] <0.015265839f
            ? (data[0 /* C6 */] <0.0071171876f ? -0.32840517f : -0.27381414f)
            : (data[0 /* C6 */] <0.023429688f ? -0.17066392f : -0.25299826f))
          : (data[2 /* C8 */] <0.047469042f
            ? (data[0 /* C6 */] <0.0561875f ? -0.17732076f : -0.21152611f)
            : (data[0 /* C6 */] <0.0710625f ? -0.072787866f : -0.15908489f)))
        : (data[2 /* C8 */] <0.13956022f
          ? (data[0 /* C6 */] <0.12573437f
            ? (data[2 /* C8 */] <0.11594531f ? -0.07324619f : 0.1652415f)
            : (data[2 /* C8 */] <0.094484374f ? -0.16481508f : -0.09149773f))
          : (data[0 /* C6 */] <0.20980468f
            ? (data[2 /* C8 */] <0.15107031f ? -0.016635986f : 0.06270336f)
            : (data[1 /* C7 */] <0.16585937f ? -0.06614034f : 0.00781619f))))
      : (data[2 /* C8 */] <0.38925263f
        ? (data[0 /* C6 */] <0.40394923f
          ? (data[2 /* C8 */] <0.28896874f
            ? (data[0 /* C6 */] <0.3061875f ? 0.12370128f : 0.00971002f)
            : (data[0 /* C6 */] <0.3926875f ? 0.18286146f : 0.3711556f))
          : (data[2 /* C8 */] <0.29048437f
            ? (data[2 /* C8 */] <0.25915357f ? -0.059841134f : -0.015874675f)
            : (data[0 /* C6 */] <0.5032578f ? 0.069752425f : 0.015411801f)))
        : (data[0 /* C6 */] <0.565998f
          ? (data[2 /* C8 */] <0.5053125f
            ? (data[0 /* C6 */] <0.49082032f ? 0.29128033f : 0.17609958f)
            : (data[2 /* C8 */] <0.5827344f ? 0.4418704f : 0.24624911f))
          : (data[2 /* C8 */] <0.5773828f
            ? (data[0 /* C6 */] <0.738875f ? 0.118408754f : 0.03037244f)
            : (data[0 /* C6 */] <0.7676875f ? 0.44742683f : 0.13119043f)))));
    return pred;
  }
}


class gbm6_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_8_class_0.score0(fdata);
  }
}
class gbm6_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.15927686f
      ? (data[2 /* C8 */] <0.048185926f
        ? (data[2 /* C8 */] <0.021742726f
          ? (data[0 /* C6 */] <0.00871875f
            ? -0.28205773f
            : (data[0 /* C6 */] <0.027291993f ? -0.22836974f : -0.27745157f))
          : (data[1 /* C7 */] <0.024578124f
            ? (data[0 /* C6 */] <0.0413125f ? -0.16893072f : -0.21915752f)
            : (data[0 /* C6 */] <0.0561875f ? -0.13121465f : -0.18632807f)))
        : (data[2 /* C8 */] <0.09471918f
          ? (data[0 /* C6 */] <0.07275f
            ? (data[1 /* C7 */] <0.03334375f ? -0.1410058f : -0.03418345f)
            : (data[2 /* C8 */] <0.07221875f ? -0.1476324f : -0.10770597f))
          : (data[0 /* C6 */] <0.23371875f
            ? (data[1 /* C7 */] <0.13075f ? -0.05274741f : 0.09362591f)
            : (data[2 /* C8 */] <0.131f ? -0.15465902f : -0.10846775f))))
      : (data[2 /* C8 */] <0.3541896f
        ? (data[2 /* C8 */] <0.23479012f
          ? (data[0 /* C6 */] <0.28128126f
            ? (data[2 /* C8 */] <0.19465625f ? 0.007241153f : 0.10860722f)
            : (data[1 /* C7 */] <0.129875f ? -0.110353984f : -0.04154984f))
          : (data[0 /* C6 */] <0.3606875f
            ? (data[2 /* C8 */] <0.25917187f ? 0.076130345f : 0.16655083f)
            : (data[2 /* C8 */] <0.31309375f ? -0.0033454797f : 0.049282797f)))
        : (data[0 /* C6 */] <0.43747658f
          ? (data[1 /* C7 */] <0.21472657f
            ? (data[0 /* C6 */] <0.32107812f ? 0.24326721f : 0.4375463f)
            : (data[2 /* C8 */] <0.39191407f ? 0.13254583f : 0.30388507f))
          : (data[2 /* C8 */] <0.5476172f
            ? (data[0 /* C6 */] <0.7165391f ? 0.100084715f : 0.02942316f)
            : (data[0 /* C6 */] <0.7657812f ? 0.35948512f : 0.10497999f)))));
    return pred;
  }
}


class gbm6_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_9_class_0.score0(fdata);
  }
}
class gbm6_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.15143701f
      ? (data[2 /* C8 */] <0.048208892f
        ? (data[2 /* C8 */] <0.023759706f
          ? (data[1 /* C7 */] <0.010445313f
            ? (data[0 /* C6 */] <0.00709375f ? -0.26735884f : -0.22514957f)
            : (data[0 /* C6 */] <0.022632813f ? -0.15789364f : -0.22310424f))
          : (data[0 /* C6 */] <0.058890626f
            ? (data[1 /* C7 */] <0.03009375f ? -0.15862216f : -0.07559995f)
            : (data[0 /* C6 */] <0.07933325f ? -0.1882496f : -0.13945499f)))
        : (data[2 /* C8 */] <0.094786115f
          ? (data[0 /* C6 */] <0.07240625f
            ? (data[1 /* C7 */] <0.03334375f ? -0.12690525f : -0.029707097f)
            : (data[2 /* C8 */] <0.0585625f ? -0.16069518f : -0.10382395f))
          : (data[0 /* C6 */] <0.15957813f
            ? (data[2 /* C8 */] <0.12475f ? -0.040402766f : 0.07021832f)
            : (data[0 /* C6 */] <0.2311836f ? -0.066815846f : -0.11210636f))))
      : (data[2 /* C8 */] <0.3898345f
        ? (data[2 /* C8 */] <0.24925438f
          ? (data[0 /* C6 */] <0.28128126f
            ? (data[2 /* C8 */] <0.21091406f ? 0.017119644f : 0.15472274f)
            : (data[1 /* C7 */] <0.14513281f ? -0.074402906f : -0.024389181f))
          : (data[0 /* C6 */] <0.41121876f
            ? (data[2 /* C8 */] <0.29309374f ? 0.086625315f : 0.1721251f)
            : (data[2 /* C8 */] <0.31489062f ? -0.016232679f : 0.03342029f)))
        : (data[0 /* C6 */] <0.55482227f
          ? (data[2 /* C8 */] <0.41402343f
            ? (data[0 /* C6 */] <0.50421876f ? 0.21183333f : 0.059727896f)
            : (data[1 /* C7 */] <0.23410937f ? 0.37703767f : 0.22903772f))
          : (data[2 /* C8 */] <0.6926953f
            ? (data[2 /* C8 */] <0.44675538f ? 0.03655305f : 0.111770324f)
            : 0.37032774f))));
    return pred;
  }
}


class gbm6_Forest_10 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_10_class_0.score0(fdata);
  }
}
class gbm6_Tree_10_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.19455615f
      ? (data[2 /* C8 */] <0.08275703f
        ? (data[2 /* C8 */] <0.034669373f
          ? (data[2 /* C8 */] <0.017436847f
            ? (data[0 /* C6 */] <0.00871875f ? -0.22844899f : -0.19984202f)
            : (data[1 /* C7 */] <0.020753907f ? -0.14948002f : -0.17279053f))
          : (data[2 /* C8 */] <0.05372689f
            ? (data[1 /* C7 */] <0.025421875f ? -0.16586672f : -0.11836621f)
            : (data[0 /* C6 */] <0.084f ? -0.059902363f : -0.11612733f)))
        : (data[2 /* C8 */] <0.13971975f
          ? (data[0 /* C6 */] <0.12573437f
            ? (data[2 /* C8 */] <0.11610547f ? -0.028915819f : 0.15360756f)
            : (data[1 /* C7 */] <0.13071875f ? -0.07972835f : 0.020172609f))
          : (data[0 /* C6 */] <0.20485938f
            ? (data[1 /* C7 */] <0.13621876f ? 0.02257985f : 0.1654591f)
            : (data[1 /* C7 */] <0.16585937f ? -0.05095693f : 0.013235924f))))
      : (data[2 /* C8 */] <0.4098303f
        ? (data[0 /* C6 */] <0.39836133f
          ? (data[2 /* C8 */] <0.248625f
            ? (data[0 /* C6 */] <0.24371094f ? 0.15938097f : 0.0018443472f)
            : (data[2 /* C8 */] <0.36452147f ? 0.10201499f : 0.25525275f))
          : (data[2 /* C8 */] <0.31398046f
            ? (data[2 /* C8 */] <0.27865812f ? -0.03971653f : 6.453104E-4f)
            : (data[0 /* C6 */] <0.49792188f ? 0.11167781f : 0.012290265f)))
        : (data[0 /* C6 */] <0.63864064f
          ? (data[2 /* C8 */] <0.5076172f
            ? (data[1 /* C7 */] <0.3679219f ? 0.1829413f : 0.02435699f)
            : (data[2 /* C8 */] <0.5916672f ? 0.35928756f : 0.19742776f))
          : (data[2 /* C8 */] <0.6935547f
            ? (data[2 /* C8 */] <0.46759704f ? 0.014695755f : 0.08133553f)
            : 0.33697537f))));
    return pred;
  }
}


class gbm6_Forest_11 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_11_class_0.score0(fdata);
  }
}
class gbm6_Tree_11_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.17691651f
      ? (data[2 /* C8 */] <0.067795105f
        ? (data[2 /* C8 */] <0.026490146f
          ? (data[2 /* C8 */] <0.015264104f
            ? (data[0 /* C6 */] <0.0071171876f ? -0.21777807f : -0.18119559f)
            : (data[0 /* C6 */] <0.023429688f ? -0.09798582f : -0.17068411f))
          : (data[2 /* C8 */] <0.039626114f
            ? (data[1 /* C7 */] <0.0283125f ? -0.121714786f : -0.16729915f)
            : (data[0 /* C6 */] <0.04875f ? -0.023028027f : -0.10727882f)))
        : (data[2 /* C8 */] <0.11917515f
          ? (data[0 /* C6 */] <0.15410157f
            ? (data[2 /* C8 */] <0.098679684f ? -0.06780677f : -0.011844738f)
            : (data[1 /* C7 */] <0.09973437f ? -0.11230228f : -0.040933147f))
          : (data[0 /* C6 */] <0.2329336f
            ? (data[0 /* C6 */] <0.12211884f ? 0.21555048f : -0.007829716f)
            : (data[1 /* C7 */] <0.1478125f ? -0.08887165f : -0.016828211f))))
      : (data[2 /* C8 */] <0.40981498f
        ? (data[0 /* C6 */] <0.31454298f
          ? (data[2 /* C8 */] <0.2333086f
            ? (data[1 /* C7 */] <0.12510937f ? -0.023821058f : 0.05633017f)
            : (data[1 /* C7 */] <0.12153125f ? -0.027758008f : 0.14384912f))
          : (data[2 /* C8 */] <0.28961718f
            ? (data[2 /* C8 */] <0.23154895f ? -0.045720376f : -9.556923E-4f)
            : (data[0 /* C6 */] <0.43851563f ? 0.12043806f : 0.017299186f)))
        : (data[0 /* C6 */] <0.63864064f
          ? (data[2 /* C8 */] <0.5215625f
            ? (data[1 /* C7 */] <0.3679219f ? 0.1673846f : 0.021921303f)
            : (data[2 /* C8 */] <0.5903369f ? 0.36596188f : 0.177685f))
          : (data[2 /* C8 */] <0.6935547f
            ? (data[2 /* C8 */] <0.5783606f ? 0.037595075f : 0.12304473f)
            : 0.30327785f))));
    return pred;
  }
}


class gbm6_Forest_12 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_12_class_0.score0(fdata);
  }
}
class gbm6_Tree_12_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.15143701f
      ? (data[2 /* C8 */] <0.048208892f
        ? (data[2 /* C8 */] <0.021752683f
          ? (data[1 /* C7 */] <0.013585937f
            ? (data[0 /* C6 */] <0.00709375f ? -0.19600026f : -0.16274887f)
            : -0.13570826f)
          : (data[0 /* C6 */] <0.058890626f
            ? (data[1 /* C7 */] <0.031875f ? -0.11502366f : -0.036573894f)
            : (data[0 /* C6 */] <0.07933325f ? -0.14517695f : -0.10141429f)))
        : (data[2 /* C8 */] <0.11165028f
          ? (data[0 /* C6 */] <0.07240625f
            ? (data[1 /* C7 */] <0.03265625f ? -0.107714966f : -0.009117358f)
            : (data[2 /* C8 */] <0.082953125f ? -0.091002196f : -0.060060546f))
          : (data[0 /* C6 */] <0.15957813f
            ? (data[0 /* C6 */] <0.15671632f ? 0.0025904449f : 0.14494796f)
            : (data[1 /* C7 */] <0.132f ? -0.064658396f : -0.0036850255f))))
      : (data[2 /* C8 */] <0.324817f
        ? (data[0 /* C6 */] <0.3592461f
          ? (data[2 /* C8 */] <0.23935156f
            ? (data[0 /* C6 */] <0.2325f ? 0.049544398f : -0.010544998f)
            : (data[0 /* C6 */] <0.25226563f ? 0.24756211f : 0.07550477f))
          : (data[2 /* C8 */] <0.22989063f
            ? (data[0 /* C6 */] <0.43521094f ? -0.07645236f : -0.019559499f)
            : (data[0 /* C6 */] <0.44897658f ? 0.019113515f : -0.018783903f)))
        : (data[0 /* C6 */] <0.50453126f
          ? (data[2 /* C8 */] <0.3940625f
            ? (data[0 /* C6 */] <0.4137031f ? 0.15661356f : 0.0735537f)
            : (data[0 /* C6 */] <0.3857656f ? 0.36220556f : 0.16527599f))
          : (data[2 /* C8 */] <0.4525f
            ? (data[2 /* C8 */] <0.33695313f ? -0.03403501f : 0.02343247f)
            : (data[0 /* C6 */] <0.7664766f ? 0.16197497f : 0.039426815f)))));
    return pred;
  }
}


class gbm6_Forest_13 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_13_class_0.score0(fdata);
  }
}
class gbm6_Tree_13_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.19455615f
      ? (data[2 /* C8 */] <0.06786305f
        ? (data[2 /* C8 */] <0.031700373f
          ? (data[2 /* C8 */] <0.017425979f
            ? (data[1 /* C7 */] <0.0076484373f ? -0.14299655f : -0.16300775f)
            : (data[1 /* C7 */] <0.020753907f ? -0.107612066f : -0.1389839f))
          : (data[0 /* C6 */] <0.10134375f
            ? (data[2 /* C8 */] <0.058625f ? -0.09021735f : -0.05666414f)
            : (data[1 /* C7 */] <0.042125f ? -0.16261554f : -0.09789348f)))
        : (data[2 /* C8 */] <0.12475074f
          ? (data[0 /* C6 */] <0.15046094f
            ? (data[1 /* C7 */] <0.08271875f ? -0.04668856f : 0.059648674f)
            : (data[1 /* C7 */] <0.09973437f ? -0.09049689f : -0.042548973f))
          : (data[0 /* C6 */] <0.23453125f
            ? (data[1 /* C7 */] <0.1350625f ? -0.0063004354f : 0.11014308f)
            : (data[1 /* C7 */] <0.15732813f ? -0.057704847f : -0.0042505013f))))
      : (data[2 /* C8 */] <0.44465405f
        ? (data[0 /* C6 */] <0.25307617f
          ? (data[1 /* C7 */] <0.10623437f
            ? -0.106313586f
            : (data[2 /* C8 */] <0.23751953f ? 0.112872854f : 0.22677468f))
          : (data[2 /* C8 */] <0.2591953f
            ? (data[0 /* C6 */] <0.3934297f ? 0.007945728f : -0.04414539f)
            : (data[0 /* C6 */] <0.40892187f ? 0.09250156f : 0.01854526f)))
        : (data[0 /* C6 */] <0.7671621f
          ? (data[2 /* C8 */] <0.52375f
            ? (data[0 /* C6 */] <0.70675f ? 0.13137537f : -0.0039986754f)
            : (data[2 /* C8 */] <0.6891797f ? 0.20152654f : 0.3910628f))
          : (data[0 /* C6 */] <1.0487394f
            ? (data[1 /* C7 */] <0.4284297f ? 0.003572643f : 0.10718288f)
            : (data[0 /* C6 */] <1.1413959f ? -0.07204223f : 0.02521707f)))));
    return pred;
  }
}


class gbm6_Forest_14 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_14_class_0.score0(fdata);
  }
}
class gbm6_Tree_14_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.16515674f
      ? (data[2 /* C8 */] <0.06782573f
        ? (data[1 /* C7 */] <0.017310547f
          ? (data[1 /* C7 */] <0.010284264f
            ? (data[1 /* C7 */] <0.0077617583f ? -0.12963921f : -0.16926207f)
            : (data[1 /* C7 */] <0.015216133f ? -0.11035345f : -0.14885859f))
          : (data[2 /* C8 */] <0.0345f
            ? (data[0 /* C6 */] <0.04083594f ? -0.085786775f : -0.13106638f)
            : (data[0 /* C6 */] <0.0780625f ? -0.06603866f : -0.090295464f)))
        : (data[0 /* C6 */] <0.080414064f
          ? (data[2 /* C8 */] <0.07254688f ? 0.029006824f : 0.050382115f)
          : (data[2 /* C8 */] <0.12483594f
            ? (data[0 /* C6 */] <0.12320313f ? -0.03221143f : -0.06591497f)
            : (data[0 /* C6 */] <0.16590625f ? 0.053453572f : -0.038203698f))))
      : (data[2 /* C8 */] <0.38988042f
        ? (data[0 /* C6 */] <0.3033672f
          ? (data[1 /* C7 */] <0.17619531f
            ? (data[2 /* C8 */] <0.1923125f ? -9.2631613E-4f : 0.06261341f)
            : (data[0 /* C6 */] <0.2953281f ? 0.10182969f : 0.28381017f))
          : (data[2 /* C8 */] <0.29296485f
            ? (data[2 /* C8 */] <0.20404425f ? -0.054823168f : -0.007985994f)
            : (data[0 /* C6 */] <0.42003125f ? 0.10714442f : 0.012343329f)))
        : (data[0 /* C6 */] <0.70569533f
          ? (data[2 /* C8 */] <0.52453125f
            ? (data[0 /* C6 */] <0.4904844f ? 0.1661067f : 0.07498783f)
            : (data[1 /* C7 */] <0.35740626f ? 0.2560063f : 0.08296179f))
          : (data[2 /* C8 */] <0.56777346f
            ? (data[2 /* C8 */] <0.48214883f ? -0.018718285f : 0.028198535f)
            : (data[0 /* C6 */] <0.7670938f ? 0.3310664f : 0.04684731f)))));
    return pred;
  }
}


class gbm6_Forest_15 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_15_class_0.score0(fdata);
  }
}
class gbm6_Tree_15_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.16515674f
      ? (data[2 /* C8 */] <0.077734634f
        ? (data[2 /* C8 */] <0.031725843f
          ? (data[2 /* C8 */] <0.015314154f
            ? (data[1 /* C7 */] <0.010507813f ? -0.12969717f : -0.09986567f)
            : (data[1 /* C7 */] <0.012890625f ? -0.048857868f : -0.10365872f))
          : (data[1 /* C7 */] <0.0623125f
            ? (data[1 /* C7 */] <0.058342773f ? -0.06689597f : 0.00580502f)
            : -0.1480993f))
        : (data[0 /* C6 */] <0.122210935f
          ? (data[2 /* C8 */] <0.11742187f
            ? (data[0 /* C6 */] <0.10767187f ? 0.024278287f : -0.044256102f)
            : 0.19275819f)
          : (data[1 /* C7 */] <0.13435157f
            ? (data[0 /* C6 */] <0.225875f ? -0.035929162f : -0.0747362f)
            : (data[0 /* C6 */] <0.23233594f ? 0.123503044f : -0.028563203f))))
      : (data[2 /* C8 */] <0.32426766f
        ? (data[0 /* C6 */] <0.3592461f
          ? (data[2 /* C8 */] <0.25465626f
            ? (data[0 /* C6 */] <0.24435937f ? 0.06543551f : -0.006187744f)
            : (data[1 /* C7 */] <0.1565f ? 0.17580873f : 0.0675802f))
          : (data[2 /* C8 */] <0.22989063f
            ? (data[0 /* C6 */] <0.40767968f ? -0.07242745f : -0.02719746f)
            : (data[0 /* C6 */] <0.44897658f ? 0.013603668f : -0.018561091f)))
        : (data[0 /* C6 */] <0.50453126f
          ? (data[2 /* C8 */] <0.4042461f
            ? (data[0 /* C6 */] <0.4137031f ? 0.12564334f : 0.061614778f)
            : (data[2 /* C8 */] <0.46211436f ? 0.22986582f : 0.06935792f))
          : (data[2 /* C8 */] <0.46804297f
            ? (data[0 /* C6 */] <0.5822578f ? 0.038631003f : 0.0013683534f)
            : (data[0 /* C6 */] <0.7818281f ? 0.13627966f : 0.022687806f)))));
    return pred;
  }
}


class gbm6_Forest_16 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_16_class_0.score0(fdata);
  }
}
class gbm6_Tree_16_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.19455615f
      ? (data[2 /* C8 */] <0.09463451f
        ? (data[1 /* C7 */] <0.023738282f
          ? (data[2 /* C8 */] <0.03564844f
            ? (data[2 /* C8 */] <0.023909913f ? -0.10655199f : -0.06928661f)
            : -0.15425004f)
          : (data[0 /* C6 */] <0.13607812f
            ? (data[2 /* C8 */] <0.07153125f ? -0.060209356f : -0.028935064f)
            : (data[1 /* C7 */] <0.0584375f ? -0.04727848f : -0.107685685f)))
        : (data[0 /* C6 */] <0.21615624f
          ? (data[1 /* C7 */] <0.13410547f
            ? (data[1 /* C7 */] <0.09986609f ? -0.024318675f : 0.018920053f)
            : (data[1 /* C7 */] <0.14711386f ? 0.18641421f : 0.08149446f))
          : (data[1 /* C7 */] <0.120207034f
            ? (data[2 /* C8 */] <0.13386719f ? -0.1036184f : -0.057399023f)
            : (data[0 /* C6 */] <0.3125781f ? -0.006636106f : -0.051360067f))))
      : (data[2 /* C8 */] <0.38925263f
        ? (data[0 /* C6 */] <0.3592461f
          ? (data[2 /* C8 */] <0.25410938f
            ? (data[0 /* C6 */] <0.1776289f ? 0.2831868f : 0.019138258f)
            : (data[0 /* C6 */] <0.23651563f ? -0.15115994f : 0.09968677f))
          : (data[2 /* C8 */] <0.29048437f
            ? (data[0 /* C6 */] <0.48584375f ? -0.0077258977f : -0.043472107f)
            : (data[0 /* C6 */] <0.44696876f ? 0.066290125f : 0.00567534f)))
        : (data[0 /* C6 */] <0.70569533f
          ? (data[2 /* C8 */] <0.54855466f
            ? (data[0 /* C6 */] <0.38623437f ? 0.22019511f : 0.074404664f)
            : (data[2 /* C8 */] <0.5913464f ? 0.2763207f : 0.10756851f))
          : (data[2 /* C8 */] <0.56777346f
            ? (data[1 /* C7 */] <0.38984376f ? -0.02147523f : 0.018420648f)
            : (data[0 /* C6 */] <0.96870315f ? 0.18438005f : -0.0438739f)))));
    return pred;
  }
}


class gbm6_Forest_17 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_17_class_0.score0(fdata);
  }
}
class gbm6_Tree_17_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.19455615f
      ? (data[2 /* C8 */] <0.08275703f
        ? (data[2 /* C8 */] <0.031812683f
          ? (data[2 /* C8 */] <0.017485203f
            ? (data[1 /* C7 */] <0.008125f ? -0.09301038f : -0.11412217f)
            : (data[1 /* C7 */] <0.020753907f ? -0.067808695f : -0.09712648f))
          : (data[0 /* C6 */] <0.10134375f
            ? (data[2 /* C8 */] <0.058828127f ? -0.060412735f : -0.025207471f)
            : (data[1 /* C7 */] <0.043140624f ? -0.12275472f : -0.06642872f)))
        : (data[1 /* C7 */] <0.16058594f
          ? (data[0 /* C6 */] <0.22958593f
            ? (data[1 /* C7 */] <0.10026562f ? -0.027129974f : 0.015766775f)
            : (data[2 /* C8 */] <0.13875f ? -0.08325088f : -0.039883f))
          : (data[0 /* C6 */] <0.3383828f
            ? (data[2 /* C8 */] <0.1648125f ? -0.032753844f : 0.13275632f)
            : (data[0 /* C6 */] <0.4316483f ? -0.06972008f : 0.03627764f))))
      : (data[2 /* C8 */] <0.44465405f
        ? (data[0 /* C6 */] <0.25307617f
          ? (data[1 /* C7 */] <0.10623437f
            ? -0.118105255f
            : (data[2 /* C8 */] <0.23751953f ? 0.08612652f : 0.18695766f))
          : (data[2 /* C8 */] <0.31366405f
            ? (data[0 /* C6 */] <0.3934297f ? 0.017225929f : -0.015861033f)
            : (data[0 /* C6 */] <0.501875f ? 0.081319295f : 0.004023214f)))
        : (data[0 /* C6 */] <0.81745315f
          ? (data[2 /* C8 */] <0.685625f
            ? (data[1 /* C7 */] <0.2395f ? 0.21731329f : 0.07582897f)
            : 0.29959467f)
          : (data[1 /* C7 */] <0.5174219f
            ? (data[2 /* C8 */] <0.4944375f ? -0.033922814f : 0.01032297f)
            : 0.08311285f))));
    return pred;
  }
}


class gbm6_Forest_18 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_18_class_0.score0(fdata);
  }
}
class gbm6_Tree_18_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.15143701f
      ? (data[2 /* C8 */] <0.04747678f
        ? (data[1 /* C7 */] <0.017310547f
          ? (data[0 /* C6 */] <0.00871875f
            ? -0.10624197f
            : (data[1 /* C7 */] <0.005785156f ? -0.043969464f : -0.08821408f))
          : (data[0 /* C6 */] <0.058890626f
            ? (data[1 /* C7 */] <0.0315625f ? -0.059257858f : 0.0070187775f)
            : (data[2 /* C8 */] <0.045f ? -0.0826282f : -0.13246766f)))
        : (data[2 /* C8 */] <0.09479012f
          ? (data[0 /* C6 */] <0.112878904f
            ? (data[2 /* C8 */] <0.082875f ? -0.03702325f : 0.03577068f)
            : (data[1 /* C7 */] <0.059265625f ? -0.048118692f : -0.07846939f))
          : (data[0 /* C6 */] <0.16891797f
            ? (data[2 /* C8 */] <0.12825f ? -0.012917345f : 0.06500117f)
            : (data[1 /* C7 */] <0.11270312f ? -0.051953103f : -0.012495769f))))
      : (data[2 /* C8 */] <0.35982642f
        ? (data[0 /* C6 */] <0.3033672f
          ? (data[1 /* C7 */] <0.18785547f
            ? (data[2 /* C8 */] <0.21191406f ? 0.0041166334f : 0.056682006f)
            : (data[0 /* C6 */] <0.28765625f ? 0.18917926f : 0.01746223f))
          : (data[2 /* C8 */] <0.249f
            ? (data[2 /* C8 */] <0.18501562f ? -0.053430773f : -0.018076029f)
            : (data[0 /* C6 */] <0.345875f ? 0.080116674f : 0.0030034757f)))
        : (data[0 /* C6 */] <0.415125f
          ? (data[0 /* C6 */] <0.32274073f
            ? -0.0370168f
            : (data[1 /* C7 */] <0.20988281f ? 0.3183773f : 0.09017259f))
          : (data[2 /* C8 */] <0.68753904f
            ? (data[0 /* C6 */] <0.6165938f ? 0.058845013f : 0.018219015f)
            : 0.18143933f))));
    return pred;
  }
}


class gbm6_Forest_19 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_19_class_0.score0(fdata);
  }
}
class gbm6_Tree_19_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C7 */] <0.120655276f
      ? (data[1 /* C7 */] <0.032298908f
        ? (data[0 /* C6 */] <0.056960937f
          ? (data[2 /* C8 */] <0.026039062f
            ? (data[0 /* C6 */] <0.02875f ? -0.07126214f : -0.09741856f)
            : (data[2 /* C8 */] <0.040030517f ? -0.040736344f : -0.094222754f))
          : (data[0 /* C6 */] <0.060383115f
            ? -0.17146462f
            : (data[2 /* C8 */] <0.05003125f ? -0.07721963f : -0.037063207f)))
        : (data[0 /* C6 */] <0.21519531f
          ? (data[1 /* C7 */] <0.099875f
            ? (data[1 /* C7 */] <0.093558595f ? -0.023953203f : -0.09729697f)
            : (data[0 /* C6 */] <0.16275f ? 0.16563632f : 0.017954942f))
          : (data[0 /* C6 */] <0.22122589f
            ? (data[2 /* C8 */] <0.15935938f ? -0.068944015f : -0.18450339f)
            : (data[1 /* C7 */] <0.10571875f ? -0.030115435f : -0.06584751f))))
      : (data[2 /* C8 */] <0.32489356f
        ? (data[0 /* C6 */] <0.27869532f
          ? (data[1 /* C7 */] <0.18783788f
            ? (data[1 /* C7 */] <0.16903973f ? 0.03798075f : -0.053512435f)
            : 0.20892142f)
          : (data[2 /* C8 */] <0.23485157f
            ? (data[1 /* C7 */] <0.23632812f ? -0.026447188f : 0.070675574f)
            : (data[0 /* C6 */] <0.40925f ? 0.02678831f : -0.00921904f)))
        : (data[0 /* C6 */] <0.49058202f
          ? (data[1 /* C7 */] <0.30323437f
            ? (data[1 /* C7 */] <0.19152538f ? 0.1580231f : 0.058984563f)
            : (data[0 /* C6 */] <0.4588125f ? 0.086427525f : 0.28548962f))
          : (data[2 /* C8 */] <0.4684375f
            ? (data[0 /* C6 */] <0.5849219f ? 0.029756866f : -0.0055124583f)
            : (data[0 /* C6 */] <0.8029063f ? 0.0898344f : 0.008548371f)))));
    return pred;
  }
}


class gbm6_Forest_20 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_20_class_0.score0(fdata);
  }
}
class gbm6_Tree_20_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.15143701f
      ? (data[2 /* C8 */] <0.048208892f
        ? (data[1 /* C7 */] <0.017310547f
          ? (data[0 /* C6 */] <0.00871875f
            ? -0.088491514f
            : (data[1 /* C7 */] <0.005785156f ? -0.032208476f : -0.07224626f))
          : (data[0 /* C6 */] <0.058890626f
            ? (data[1 /* C7 */] <0.0315625f ? -0.04744625f : 0.0035599074f)
            : (data[2 /* C8 */] <0.04490625f ? -0.059560653f : -0.08333318f)))
        : (data[0 /* C6 */] <0.06467969f
          ? (data[0 /* C6 */] <0.059780795f ? -0.025082693f : 0.11617202f)
          : (data[2 /* C8 */] <0.0829336f
            ? (data[2 /* C8 */] <0.08134296f ? -0.040920194f : -0.11009267f)
            : (data[0 /* C6 */] <0.14873438f ? 0.0048311832f : -0.03169269f))))
      : (data[2 /* C8 */] <0.3898345f
        ? (data[0 /* C6 */] <0.44865236f
          ? (data[2 /* C8 */] <0.2591172f
            ? (data[0 /* C6 */] <0.21634375f ? 0.0535014f : -0.0075645493f)
            : (data[2 /* C8 */] <0.26111534f ? 0.12768951f : 0.03742995f))
          : (data[1 /* C7 */] <0.35109764f
            ? (data[2 /* C8 */] <0.29028124f ? -0.027700117f : -0.0033080266f)
            : (data[0 /* C6 */] <0.582125f ? 0.14920856f : 0.03718632f)))
        : (data[0 /* C6 */] <0.70569533f
          ? (data[1 /* C7 */] <0.19985546f
            ? -0.051470436f
            : (data[2 /* C8 */] <0.52453125f ? 0.061275937f : 0.13198394f))
          : (data[2 /* C8 */] <0.5605664f
            ? (data[0 /* C6 */] <0.71821874f ? -0.06441025f : -0.0044792877f)
            : (data[0 /* C6 */] <0.7670938f ? 0.23460613f : 0.02416517f)))));
    return pred;
  }
}


class gbm6_Forest_21 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_21_class_0.score0(fdata);
  }
}
class gbm6_Tree_21_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.17691651f
      ? (data[2 /* C8 */] <0.09469002f
        ? (data[2 /* C8 */] <0.03881241f
          ? (data[1 /* C7 */] <0.028484374f
            ? (data[2 /* C8 */] <0.026648438f ? -0.06245176f : -0.03751479f)
            : -0.08507891f)
          : (data[0 /* C6 */] <0.11292188f
            ? (data[2 /* C8 */] <0.085828125f ? -0.02776659f : 0.061649296f)
            : (data[1 /* C7 */] <0.058828127f ? -0.03793245f : -0.065670244f)))
        : (data[0 /* C6 */] <0.1224375f
          ? (data[0 /* C6 */] <0.114356935f
            ? (data[1 /* C7 */] <0.057796873f ? 0.046723034f : -0.03536086f)
            : 0.1692691f)
          : (data[0 /* C6 */] <0.23255566f
            ? (data[2 /* C8 */] <0.16758594f ? -0.0140162865f : 0.05421605f)
            : (data[1 /* C7 */] <0.14879687f ? -0.048729796f : -0.0030295055f))))
      : (data[2 /* C8 */] <0.4195191f
        ? (data[0 /* C6 */] <0.3033672f
          ? (data[1 /* C7 */] <0.12178125f
            ? (data[0 /* C6 */] <0.17257813f ? 0.08363702f : -0.05011761f)
            : (data[1 /* C7 */] <0.2079602f ? 0.04381774f : 0.17555654f))
          : (data[2 /* C8 */] <0.29256642f
            ? (data[1 /* C7 */] <0.1631875f ? -0.03890822f : -0.0032581028f)
            : (data[0 /* C6 */] <0.49146876f ? 0.045579802f : -3.2589055E-4f)))
        : (data[1 /* C7 */] <0.35138866f
          ? (data[2 /* C8 */] <0.52054685f
            ? (data[2 /* C8 */] <0.4765576f ? 0.0860379f : -0.022171834f)
            : (data[2 /* C8 */] <0.62866634f ? 0.235798f : 0.04290899f))
          : (data[1 /* C7 */] <0.3865037f
            ? (data[1 /* C7 */] <0.35846946f ? 0.064808026f : -0.043153603f)
            : (data[0 /* C6 */] <0.8841562f ? 0.06554143f : -0.0030449796f)))));
    return pred;
  }
}


class gbm6_Forest_22 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_22_class_0.score0(fdata);
  }
}
class gbm6_Tree_22_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.20435596f
      ? (data[2 /* C8 */] <0.108078614f
        ? (data[1 /* C7 */] <0.028220704f
          ? (data[2 /* C8 */] <0.040421873f
            ? (data[1 /* C7 */] <0.024777343f ? -0.05188747f : -0.011608761f)
            : -0.07793212f)
          : (data[0 /* C6 */] <0.1245f
            ? (data[2 /* C8 */] <0.09902344f ? -0.0244443f : 0.10092867f)
            : (data[1 /* C7 */] <0.059265625f ? -0.0075741243f : -0.055435948f)))
        : (data[0 /* C6 */] <0.21615624f
          ? (data[1 /* C7 */] <0.13528906f
            ? (data[0 /* C6 */] <0.146625f ? 0.04526126f : -0.0044638473f)
            : (data[2 /* C8 */] <0.17998438f ? 0.05291683f : 0.16799317f))
          : (data[1 /* C7 */] <0.15916015f
            ? (data[2 /* C8 */] <0.19509375f ? -0.029181067f : -0.1110102f)
            : (data[0 /* C6 */] <0.3125781f ? 0.053223178f : -0.018554848f))))
      : (data[2 /* C8 */] <0.20591971f
        ? (data[1 /* C7 */] <0.15708399f ? 0.219922f : 0.050741628f)
        : (data[1 /* C7 */] <0.09993555f
          ? -0.18777806f
          : (data[2 /* C8 */] <0.44320312f
            ? (data[0 /* C6 */] <0.2826875f ? 0.059641864f : 0.0064943936f)
            : (data[1 /* C7 */] <0.23565625f ? 0.1939053f : 0.03778829f)))));
    return pred;
  }
}


class gbm6_Forest_23 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_23_class_0.score0(fdata);
  }
}
class gbm6_Tree_23_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.14457715f
      ? (data[1 /* C7 */] <0.042035155f
        ? (data[0 /* C6 */] <0.099414065f
          ? (data[1 /* C7 */] <0.025789063f
            ? (data[0 /* C6 */] <0.0070625f ? -0.07817713f : -0.04424741f)
            : (data[2 /* C8 */] <0.074210934f ? -0.022208467f : -0.07302516f))
          : (data[0 /* C6 */] <0.10868561f ? -0.10926963f : -0.07843698f))
        : (data[0 /* C6 */] <0.217125f
          ? (data[1 /* C7 */] <0.10015625f
            ? (data[1 /* C7 */] <0.0938501f ? -0.016970325f : -0.07986279f)
            : (data[0 /* C6 */] <0.17078906f ? 0.079010636f : 0.009305059f))
          : (data[1 /* C7 */] <0.14051563f
            ? (data[0 /* C6 */] <0.24249218f ? -0.07458452f : -0.04323965f)
            : -0.005470257f)))
      : (data[2 /* C8 */] <0.3899321f
        ? (data[0 /* C6 */] <0.5324707f
          ? (data[2 /* C8 */] <0.31465626f
            ? (data[0 /* C6 */] <0.2799219f ? 0.021224037f : -0.0055684247f)
            : (data[1 /* C7 */] <0.15715624f ? 0.20407404f : 0.029728925f))
          : (data[1 /* C7 */] <0.35109764f
            ? (data[2 /* C8 */] <0.3713047f ? -0.017332882f : -0.05216781f)
            : (data[2 /* C8 */] <0.3606875f ? 0.09350195f : 0.011470281f)))
        : (data[0 /* C6 */] <0.70569533f
          ? (data[1 /* C7 */] <0.19985546f
            ? -0.05656102f
            : (data[0 /* C6 */] <0.5360938f ? 0.08873996f : 0.04081165f))
          : (data[2 /* C8 */] <0.5773828f
            ? (data[1 /* C7 */] <0.43007812f ? -0.02140435f : 0.02021317f)
            : (data[0 /* C6 */] <0.96870315f ? 0.13813764f : -0.05224748f)))));
    return pred;
  }
}


class gbm6_Forest_24 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_24_class_0.score0(fdata);
  }
}
class gbm6_Tree_24_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.20435596f
      ? (data[2 /* C8 */] <0.12471914f
        ? (data[2 /* C8 */] <0.048188504f
          ? (data[1 /* C7 */] <0.040929686f
            ? (data[1 /* C7 */] <0.03145398f ? -0.040572193f : -0.016210211f)
            : -0.087092526f)
          : (data[0 /* C6 */] <0.0781875f
            ? (data[2 /* C8 */] <0.0639375f ? -0.009436712f : 0.05740076f)
            : (data[2 /* C8 */] <0.07225f ? -0.0472257f : -0.0208677f)))
        : (data[1 /* C7 */] <0.07344922f
          ? (data[2 /* C8 */] <0.13302344f ? 0.026099911f : 0.16321217f)
          : (data[0 /* C6 */] <0.23308593f
            ? (data[1 /* C7 */] <0.1349375f ? -0.0037870118f : 0.07418794f)
            : (data[1 /* C7 */] <0.1630625f ? -0.03278963f : 0.014369234f))))
      : (data[2 /* C8 */] <0.20591971f
        ? (data[1 /* C7 */] <0.15708399f ? 0.19723633f : 0.045399975f)
        : (data[1 /* C7 */] <0.09993555f
          ? -0.17268318f
          : (data[2 /* C8 */] <0.54932034f
            ? (data[0 /* C6 */] <0.2826875f ? 0.051373534f : 0.007709471f)
            : (data[0 /* C6 */] <0.9684687f ? 0.09105565f : -0.04154429f)))));
    return pred;
  }
}


class gbm6_Forest_25 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_25_class_0.score0(fdata);
  }
}
class gbm6_Tree_25_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.23375537f
      ? (data[2 /* C8 */] <0.12488566f
        ? (data[2 /* C8 */] <0.0482516f
          ? (data[1 /* C7 */] <0.040929686f
            ? (data[2 /* C8 */] <0.02184375f ? -0.044455294f : -0.02762501f)
            : -0.07838328f)
          : (data[0 /* C6 */] <0.14765625f
            ? (data[1 /* C7 */] <0.08219531f ? -0.015856294f : 0.07233306f)
            : (data[1 /* C7 */] <0.120078124f ? -0.03860853f : 0.019754805f)))
        : (data[0 /* C6 */] <0.17043555f
          ? (data[1 /* C7 */] <0.0998125f
            ? (data[1 /* C7 */] <0.07963281f ? 0.077384785f : -0.025536865f)
            : (data[1 /* C7 */] <0.107734375f ? 0.20741571f : 0.0794805f))
          : (data[0 /* C6 */] <0.30020165f
            ? (data[1 /* C7 */] <0.13103124f ? -0.014871474f : 0.021004315f)
            : (data[1 /* C7 */] <0.1601875f ? -0.043212425f : -0.010881299f))))
      : (data[0 /* C6 */] <0.4453574f
        ? (data[2 /* C8 */] <0.35748047f
          ? (data[0 /* C6 */] <0.35115233f
            ? (data[1 /* C7 */] <0.21075f ? 0.027556958f : 0.11860499f)
            : (data[0 /* C6 */] <0.37314788f ? -0.051893666f : 0.027155083f))
          : (data[1 /* C7 */] <0.2056875f
            ? (data[2 /* C8 */] <0.37707812f ? 0.36432523f : 0.07680899f)
            : (data[1 /* C7 */] <0.22643945f ? -0.046633504f : 0.07917805f)))
        : (data[2 /* C8 */] <0.33941016f
          ? (data[0 /* C6 */] <0.583957f
            ? (data[2 /* C8 */] <0.26845312f ? -0.03669214f : -8.5096783E-4f)
            : (data[1 /* C7 */] <0.23042187f ? -0.06524925f : -0.02855462f))
          : (data[1 /* C7 */] <0.203125f
            ? -0.112056166f
            : (data[0 /* C6 */] <0.59296095f ? 0.039463487f : 0.008100812f)))));
    return pred;
  }
}


class gbm6_Forest_26 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_26_class_0.score0(fdata);
  }
}
class gbm6_Tree_26_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.23375537f
      ? (data[2 /* C8 */] <0.07770879f
        ? (data[2 /* C8 */] <0.075178415f
          ? (data[2 /* C8 */] <0.07230035f
            ? (data[1 /* C7 */] <0.0465f ? -0.024251673f : -0.047663324f)
            : (data[1 /* C7 */] <0.0565625f ? -0.025144417f : 0.045306597f))
          : -0.105165176f)
        : (data[0 /* C6 */] <0.28070313f
          ? (data[1 /* C7 */] <0.18776563f
            ? (data[2 /* C8 */] <0.21382031f ? -0.00664559f : 0.066438675f)
            : 0.15972166f)
          : (data[0 /* C6 */] <0.28389686f
            ? -0.111182734f
            : (data[2 /* C8 */] <0.22303125f ? -0.012304665f : -0.042105924f))))
      : (data[0 /* C6 */] <0.4453574f
        ? (data[2 /* C8 */] <0.35748047f
          ? (data[0 /* C6 */] <0.25427735f
            ? (data[2 /* C8 */] <0.2676328f ? 0.1508149f : -0.084026806f)
            : (data[0 /* C6 */] <0.43903992f ? 0.0133900065f : 0.10372598f))
          : (data[1 /* C7 */] <0.2056875f
            ? (data[2 /* C8 */] <0.37707812f ? 0.3278927f : 0.06912809f)
            : (data[2 /* C8 */] <0.46726564f ? 0.06551548f : -0.0868687f)))
        : (data[2 /* C8 */] <0.4448203f
          ? (data[0 /* C6 */] <0.5921016f
            ? (data[2 /* C8 */] <0.41775f ? 2.185055E-4f : 0.12284774f)
            : (data[1 /* C7 */] <0.3836875f ? -0.024703853f : 0.030633992f))
          : (data[1 /* C7 */] <0.355f
            ? (data[1 /* C7 */] <0.25804687f ? -0.038436428f : 0.08116117f)
            : (data[0 /* C6 */] <0.6126094f ? -0.07758826f : 0.018253105f)))));
    return pred;
  }
}


class gbm6_Forest_27 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_27_class_0.score0(fdata);
  }
}
class gbm6_Tree_27_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.25923488f
      ? (data[2 /* C8 */] <0.124830164f
        ? (data[0 /* C6 */] <0.14992188f
          ? (data[1 /* C7 */] <0.08459375f
            ? (data[2 /* C8 */] <0.11489063f ? -0.017496653f : -0.076743744f)
            : 0.0919306f)
          : (data[1 /* C7 */] <0.10076562f
            ? (data[1 /* C7 */] <0.079324216f ? -0.021954786f : -0.051585883f)
            : (data[2 /* C8 */] <0.11578125f ? 0.040457625f : -0.040999126f)))
        : (data[0 /* C6 */] <0.16646875f
          ? (data[1 /* C7 */] <0.1049375f
            ? (data[2 /* C8 */] <0.1625f ? 0.050698843f : -0.087550595f)
            : 0.26679727f)
          : (data[0 /* C6 */] <0.38183668f
            ? (data[1 /* C7 */] <0.1601875f ? -0.008160817f : 0.017498905f)
            : (data[1 /* C7 */] <0.2622344f ? -0.030727303f : 0.049780212f))))
      : (data[1 /* C7 */] <0.13845606f
        ? -0.1373765f
        : (data[0 /* C6 */] <0.32571876f
          ? (data[1 /* C7 */] <0.14821094f
            ? 0.21092832f
            : (data[1 /* C7 */] <0.18882245f ? 0.013198669f : 0.121933594f))
          : (data[2 /* C8 */] <0.6934043f
            ? (data[0 /* C6 */] <0.48940626f ? 0.02314914f : 0.0021638572f)
            : 0.11647107f))));
    return pred;
  }
}


class gbm6_Forest_28 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_28_class_0.score0(fdata);
  }
}
class gbm6_Tree_28_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C7 */] <0.11917187f
      ? (data[0 /* C6 */] <0.21591797f
        ? (data[1 /* C7 */] <0.09955859f
          ? (data[1 /* C7 */] <0.09414133f
            ? (data[2 /* C8 */] <0.1105625f ? -0.01866924f : 0.01300305f)
            : (data[0 /* C6 */] <0.15982813f ? -0.031249456f : -0.08444002f))
          : (data[0 /* C6 */] <0.161875f
            ? 0.1172876f
            : (data[1 /* C7 */] <0.10173438f ? 0.08745889f : 0.00480578f)))
        : (data[0 /* C6 */] <0.22136879f
          ? (data[0 /* C6 */] <0.21775523f ? -0.06484353f : -0.15832257f)
          : (data[1 /* C7 */] <0.104375f
            ? (data[2 /* C8 */] <0.121078126f ? -0.05432878f : 0.010055508f)
            : (data[0 /* C6 */] <0.26423436f ? -0.08022833f : -0.0067179943f))))
      : (data[0 /* C6 */] <0.25367382f
        ? (data[2 /* C8 */] <0.22683594f
          ? (data[0 /* C6 */] <0.18297656f
            ? 0.1234051f
            : (data[0 /* C6 */] <0.1995055f ? -0.056163788f : 0.02259372f))
          : (data[1 /* C7 */] <0.15835547f
            ? (data[0 /* C6 */] <0.23196875f ? 0.09068804f : 0.3790703f)
            : -0.005940613f))
        : (data[2 /* C8 */] <0.27989256f
          ? (data[1 /* C7 */] <0.15452734f
            ? (data[2 /* C8 */] <0.2373125f ? -0.016403945f : -0.08402756f)
            : (data[0 /* C6 */] <0.3955625f ? 0.014040662f : -0.020418903f))
          : (data[1 /* C7 */] <0.15953125f
            ? (data[2 /* C8 */] <0.31398436f ? 0.017768325f : 0.19184862f)
            : (data[0 /* C6 */] <0.2925625f ? 0.123969495f : 0.01060173f)))));
    return pred;
  }
}


class gbm6_Forest_29 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_29_class_0.score0(fdata);
  }
}
class gbm6_Tree_29_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C7 */] <0.11917187f
      ? (data[0 /* C6 */] <0.21591797f
        ? (data[2 /* C8 */] <0.15146093f
          ? (data[2 /* C8 */] <0.1491178f
            ? (data[2 /* C8 */] <0.13989168f ? -0.013979531f : 0.031464893f)
            : (data[0 /* C6 */] <0.18198438f ? -0.08600252f : -0.07142989f))
          : (data[1 /* C7 */] <0.111125f
            ? (data[1 /* C7 */] <0.09950586f ? 0.0063681323f : 0.12372117f)
            : (data[0 /* C6 */] <0.19575f ? -0.013269346f : -0.058398582f)))
        : (data[0 /* C6 */] <0.22136879f
          ? (data[0 /* C6 */] <0.21775523f ? -0.0583592f : -0.14249033f)
          : (data[1 /* C7 */] <0.101125f
            ? (data[2 /* C8 */] <0.14596094f ? -0.03732422f : 0.044354226f)
            : (data[0 /* C6 */] <0.26423436f ? -0.06324019f : -0.01243751f))))
      : (data[2 /* C8 */] <0.5091299f
        ? (data[0 /* C6 */] <0.25285548f
          ? (data[2 /* C8 */] <0.20494531f
            ? (data[0 /* C6 */] <0.22515625f ? 0.037077166f : -0.016653549f)
            : (data[1 /* C7 */] <0.15835547f ? 0.16296838f : -0.021883333f))
          : (data[2 /* C8 */] <0.31358594f
            ? (data[1 /* C7 */] <0.15985937f ? -0.017082369f : -7.3883287E-4f)
            : (data[1 /* C7 */] <0.15985937f ? 0.17266373f : 0.009255027f)))
        : (data[1 /* C7 */] <0.3546836f
          ? (data[1 /* C7 */] <0.3108353f
            ? (data[1 /* C7 */] <0.28762528f ? 0.10388194f : -0.051242083f)
            : 0.1983904f)
          : (data[1 /* C7 */] <0.38634896f
            ? -0.0882006f
            : (data[0 /* C6 */] <0.9715547f ? 0.060241383f : -0.031609032f)))));
    return pred;
  }
}


class gbm6_Forest_30 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_30_class_0.score0(fdata);
  }
}
class gbm6_Tree_30_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C7 */] <0.11917187f
      ? (data[0 /* C6 */] <0.21591797f
        ? (data[2 /* C8 */] <0.15146093f
          ? (data[1 /* C7 */] <0.10467187f
            ? (data[2 /* C8 */] <0.14866406f ? -0.012984213f : -0.07361928f)
            : (data[1 /* C7 */] <0.10675439f ? 0.11902286f : -0.0034354853f))
          : (data[1 /* C7 */] <0.111125f
            ? (data[1 /* C7 */] <0.09950586f ? 0.0057313642f : 0.11134905f)
            : (data[0 /* C6 */] <0.19575f ? -0.011942404f : -0.052558757f)))
        : (data[0 /* C6 */] <0.22136879f
          ? (data[0 /* C6 */] <0.21775523f ? -0.052523285f : -0.1282413f)
          : (data[1 /* C7 */] <0.101125f
            ? (data[2 /* C8 */] <0.14596094f ? -0.033591777f : 0.03991878f)
            : (data[0 /* C6 */] <0.26423436f ? -0.056916185f : -0.011193747f))))
      : (data[2 /* C8 */] <0.5091299f
        ? (data[0 /* C6 */] <0.25285548f
          ? (data[2 /* C8 */] <0.23210546f
            ? (data[0 /* C6 */] <0.22515625f ? 0.03889407f : -0.008100752f)
            : (data[1 /* C7 */] <0.15835547f ? 0.22067076f : -0.0031582683f))
          : (data[2 /* C8 */] <0.31358594f
            ? (data[0 /* C6 */] <0.39025f ? 0.001770017f : -0.011625285f)
            : (data[1 /* C7 */] <0.15985937f ? 0.15539736f : 0.008329487f)))
        : (data[2 /* C8 */] <0.51687783f
          ? 0.1656761f
          : (data[2 /* C8 */] <0.5245047f
            ? -0.12754312f
            : (data[1 /* C7 */] <0.35175f ? 0.11816022f : 0.0017057775f)))));
    return pred;
  }
}


class gbm6_Forest_31 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_31_class_0.score0(fdata);
  }
}
class gbm6_Tree_31_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.25923488f
      ? (data[1 /* C7 */] <0.042035155f
        ? (data[2 /* C8 */] <0.08146582f
          ? (data[0 /* C6 */] <0.09748437f
            ? (data[2 /* C8 */] <0.06282812f ? -0.020442443f : 0.03839686f)
            : (data[2 /* C8 */] <0.06405469f ? -0.05073452f : -0.08417394f))
          : -0.09544652f)
        : (data[0 /* C6 */] <0.3926094f
          ? (data[1 /* C7 */] <0.20825f
            ? (data[0 /* C6 */] <0.300625f ? -3.7012217E-4f : -0.013668157f)
            : (data[1 /* C7 */] <0.21324219f ? 0.1091894f : 0.026474128f))
          : (data[0 /* C6 */] <0.4245397f
            ? (data[2 /* C8 */] <0.19794141f ? -0.1269148f : -0.034302756f)
            : (data[2 /* C8 */] <0.19669531f ? 0.059407607f : -0.017326001f))))
      : (data[1 /* C7 */] <0.13845606f
        ? -0.14509852f
        : (data[0 /* C6 */] <0.44306445f
          ? (data[2 /* C8 */] <0.39345703f
            ? (data[2 /* C8 */] <0.37775895f ? 0.029787727f : -0.11209799f)
            : (data[2 /* C8 */] <0.464868f ? 0.15110698f : 0.011199159f))
          : (data[2 /* C8 */] <0.38763282f
            ? (data[1 /* C7 */] <0.348875f ? -0.010222878f : 0.042551246f)
            : (data[0 /* C6 */] <0.7699062f ? 0.026438639f : -0.011880303f)))));
    return pred;
  }
}


class gbm6_Forest_32 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_32_class_0.score0(fdata);
  }
}
class gbm6_Tree_32_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C7 */] <0.13103907f
      ? (data[2 /* C8 */] <0.2572749f
        ? (data[2 /* C8 */] <0.23779204f
          ? (data[0 /* C6 */] <0.2325625f
            ? (data[2 /* C8 */] <0.12634376f ? -0.012522376f : 0.010257693f)
            : (data[0 /* C6 */] <0.23666309f ? -0.07816404f : -0.022713693f))
          : 0.20525691f)
        : -0.12659845f)
      : (data[0 /* C6 */] <0.25367382f
        ? (data[2 /* C8 */] <0.18792774f
          ? (data[0 /* C6 */] <0.24796875f
            ? (data[2 /* C8 */] <0.16080469f ? 0.07303317f : -0.0103945f)
            : -0.07938828f)
          : (data[1 /* C7 */] <0.14478515f
            ? (data[1 /* C7 */] <0.13918048f ? 0.04243531f : 0.2410714f)
            : (data[0 /* C6 */] <0.24520312f ? -0.023948923f : 0.1675144f)))
        : (data[0 /* C6 */] <0.25849542f
          ? (data[2 /* C8 */] <0.21622461f ? -0.042187575f : -0.12461768f)
          : (data[2 /* C8 */] <0.6866602f
            ? (data[2 /* C8 */] <0.33803383f ? -8.664782E-4f : 0.011720676f)
            : 0.09319835f))));
    return pred;
  }
}


class gbm6_Forest_33 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_33_class_0.score0(fdata);
  }
}
class gbm6_Tree_33_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.17691651f
      ? (data[2 /* C8 */] <0.17417562f
        ? (data[1 /* C7 */] <0.1500254f
          ? (data[0 /* C6 */] <0.2643203f
            ? (data[2 /* C8 */] <0.16860938f ? -0.008196438f : 0.045931507f)
            : (data[2 /* C8 */] <0.16860938f ? -0.025590038f : -0.07285935f))
          : (data[2 /* C8 */] <0.15917578f
            ? (data[2 /* C8 */] <0.14705414f ? 0.016237158f : -0.10095006f)
            : 0.12111416f))
        : (data[0 /* C6 */] <0.28365624f
          ? (data[0 /* C6 */] <0.21125415f ? -0.020318266f : -0.11015862f)
          : -0.010626205f))
      : (data[1 /* C7 */] <0.08950391f
        ? -0.103932135f
        : (data[0 /* C6 */] <0.17484571f
          ? 0.22538789f
          : (data[0 /* C6 */] <0.19536375f
            ? -0.11671071f
            : (data[0 /* C6 */] <0.21556118f ? 0.07810238f : 0.004600923f)))));
    return pred;
  }
}


class gbm6_Forest_34 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_34_class_0.score0(fdata);
  }
}
class gbm6_Tree_34_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.28961426f
      ? (data[2 /* C8 */] <0.28539383f
        ? (data[1 /* C7 */] <0.28371876f
          ? (data[2 /* C8 */] <0.072375f
            ? (data[0 /* C6 */] <0.10028125f ? -0.012551935f : -0.03981089f)
            : (data[0 /* C6 */] <0.12234375f ? 0.020902483f : -0.0037468346f))
          : 0.085251525f)
        : (data[1 /* C7 */] <0.21335937f ? -0.11020024f : -0.033738416f))
      : (data[0 /* C6 */] <0.41341016f
        ? (data[0 /* C6 */] <0.37726304f
          ? (data[0 /* C6 */] <0.36227414f
            ? (data[1 /* C7 */] <0.160125f ? 0.08972752f : 0.011092869f)
            : (data[0 /* C6 */] <0.3714778f ? -0.18797363f : -0.03455249f))
          : (data[1 /* C7 */] <0.2056875f
            ? (data[0 /* C6 */] <0.3908125f ? 0.2672981f : 0.1606321f)
            : (data[1 /* C7 */] <0.22477734f ? -0.0425761f : 0.13413818f)))
        : (data[0 /* C6 */] <0.41760778f
          ? -0.119481824f
          : (data[2 /* C8 */] <0.41847655f
            ? (data[2 /* C8 */] <0.41044676f ? -3.629362E-4f : -0.06060431f)
            : (data[0 /* C6 */] <0.63614064f ? 0.049474552f : 8.731528E-4f)))));
    return pred;
  }
}


class gbm6_Forest_35 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_35_class_0.score0(fdata);
  }
}
class gbm6_Tree_35_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.14457715f
      ? (data[2 /* C8 */] <0.1402457f
        ? (data[2 /* C8 */] <0.13916175f
          ? (data[2 /* C8 */] <0.1359353f
            ? (data[1 /* C7 */] <0.036078125f ? -0.017225603f : -0.004846587f)
            : -0.07984009f)
          : (data[1 /* C7 */] <0.10490234f ? -0.013486707f : 0.09838623f))
        : (data[1 /* C7 */] <0.11153808f ? -0.11579873f : -0.030977074f))
      : (data[2 /* C8 */] <0.5487406f
        ? (data[2 /* C8 */] <0.5345466f
          ? (data[2 /* C8 */] <0.52237326f
            ? (data[2 /* C8 */] <0.5164768f ? 0.0029776418f : -0.1309589f)
            : 0.10042353f)
          : -0.09488439f)
        : (data[1 /* C7 */] <0.35424608f
          ? (data[1 /* C7 */] <0.31114948f ? 0.0062238695f : 0.25469258f)
          : (data[2 /* C8 */] <0.5997656f
            ? (data[1 /* C7 */] <0.4069375f ? -0.20005026f : 0.05865068f)
            : (data[0 /* C6 */] <0.95452344f ? 0.07885787f : -0.020730114f)))));
    return pred;
  }
}


class gbm6_Forest_36 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_36_class_0.score0(fdata);
  }
}
class gbm6_Tree_36_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.38957226f
      ? (data[1 /* C7 */] <0.35354882f
        ? (data[2 /* C8 */] <0.38597265f
          ? (data[0 /* C6 */] <0.5968828f
            ? (data[2 /* C8 */] <0.25916407f ? -0.004676399f : 0.0074888403f)
            : (data[1 /* C7 */] <0.2975f ? -0.015603279f : -0.053869363f))
          : -0.11210702f)
        : (data[1 /* C7 */] <0.37207386f
          ? 0.16809635f
          : (data[0 /* C6 */] <0.6713633f ? -0.04529695f : 0.07232054f)))
      : (data[0 /* C6 */] <0.48892188f
        ? (data[1 /* C7 */] <0.26801464f
          ? (data[1 /* C7 */] <0.23655802f
            ? (data[2 /* C8 */] <0.41375f ? -0.035451025f : 0.1974722f)
            : -0.12447921f)
          : (data[1 /* C7 */] <0.3066731f ? 0.26245305f : 0.038993653f))
        : (data[1 /* C7 */] <0.23207617f
          ? -0.108109325f
          : (data[0 /* C6 */] <0.77176565f
            ? (data[2 /* C8 */] <0.70230466f ? 0.015568043f : 0.15120018f)
            : (data[1 /* C7 */] <0.52097654f ? -0.018836489f : 0.054955214f)))));
    return pred;
  }
}


class gbm6_Forest_37 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_37_class_0.score0(fdata);
  }
}
class gbm6_Tree_37_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.44445118f
      ? (data[2 /* C8 */] <0.4357998f
        ? (data[2 /* C8 */] <0.4341033f
          ? (data[0 /* C6 */] <0.58435935f
            ? (data[2 /* C8 */] <0.31235936f ? -0.0025924093f : 0.016178139f)
            : (data[1 /* C7 */] <0.38641405f ? -0.01993455f : 0.021079235f))
          : 0.124868006f)
        : (data[1 /* C7 */] <0.2981465f ? -0.17984097f : -0.03143356f))
      : (data[1 /* C7 */] <0.23858544f
        ? 0.15502931f
        : (data[1 /* C7 */] <0.26302674f
          ? -0.16052674f
          : (data[1 /* C7 */] <0.27467456f
            ? 0.2099182f
            : (data[1 /* C7 */] <0.35808986f ? 0.04365364f : -5.501377E-4f)))));
    return pred;
  }
}


class gbm6_Forest_38 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_38_class_0.score0(fdata);
  }
}
class gbm6_Tree_38_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C7 */] <0.042035155f
      ? (data[2 /* C8 */] <0.0818584f
        ? (data[0 /* C6 */] <0.09748437f
          ? (data[2 /* C8 */] <0.06436133f
            ? (data[1 /* C7 */] <0.025789063f ? -0.01988926f : -0.0036835861f)
            : (data[0 /* C6 */] <0.0835f ? 0.08245421f : -0.013032976f))
          : (data[2 /* C8 */] <0.06436133f ? -0.03787536f : -0.071676515f))
        : -0.12390428f)
      : (data[2 /* C8 */] <0.5483291f
        ? (data[2 /* C8 */] <0.53429276f
          ? (data[2 /* C8 */] <0.5225906f
            ? (data[0 /* C6 */] <0.55698436f ? 0.0026405517f : -0.0070878044f)
            : 0.08682727f)
          : -0.08989417f)
        : (data[2 /* C8 */] <0.5857904f
          ? (data[0 /* C6 */] <0.7539375f ? 0.16458598f : -0.038710676f)
          : (data[2 /* C8 */] <0.60216576f
            ? -0.0934549f
            : (data[0 /* C6 */] <0.6586328f ? -0.056418985f : 0.058916677f)))));
    return pred;
  }
}


class gbm6_Forest_39 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_39_class_0.score0(fdata);
  }
}
class gbm6_Tree_39_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.14457715f
      ? (data[2 /* C8 */] <0.1402457f
        ? (data[2 /* C8 */] <0.13916175f
          ? (data[2 /* C8 */] <0.1359353f
            ? (data[1 /* C7 */] <0.13957812f ? -0.0069183335f : 0.047822874f)
            : -0.071393274f)
          : (data[0 /* C6 */] <0.21905468f ? 0.09313064f : -0.008091613f))
        : (data[1 /* C7 */] <0.11153808f ? -0.10375601f : -0.027416531f))
      : (data[1 /* C7 */] <0.08653711f
        ? (data[2 /* C8 */] <0.171875f
          ? (data[2 /* C8 */] <0.15066895f ? 0.054576546f : 0.18899468f)
          : -0.12601343f)
        : (data[2 /* C8 */] <0.68753904f
          ? (data[2 /* C8 */] <0.6536304f
            ? (data[2 /* C8 */] <0.5979989f ? 0.0016907324f : 0.06654439f)
            : -0.10681013f)
          : 0.06337351f)));
    return pred;
  }
}


class gbm6_Forest_40 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_40_class_0.score0(fdata);
  }
}
class gbm6_Tree_40_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.38957226f
      ? (data[1 /* C7 */] <0.35354882f
        ? (data[2 /* C8 */] <0.37537694f
          ? (data[0 /* C6 */] <0.5901875f
            ? (data[2 /* C8 */] <0.36916405f ? -0.001111907f : 0.059780255f)
            : (data[1 /* C7 */] <0.2975f ? -0.01235927f : -0.04884885f))
          : (data[0 /* C6 */] <0.5433203f
            ? (data[2 /* C8 */] <0.3802461f ? -0.14038911f : -0.055360977f)
            : (data[1 /* C7 */] <0.31440625f ? 0.026012065f : -0.083051145f)))
        : (data[1 /* C7 */] <0.37207386f
          ? 0.15220639f
          : (data[0 /* C6 */] <0.6713633f ? -0.04119576f : 0.06488735f)))
      : (data[2 /* C8 */] <0.3955823f
        ? (data[1 /* C7 */] <0.26801464f
          ? (data[0 /* C6 */] <0.492875f ? -0.080505356f : 0.017699f)
          : (data[1 /* C7 */] <0.30864522f ? 0.27687833f : 0.060066286f))
        : (data[0 /* C6 */] <0.41032422f
          ? 0.11227217f
          : (data[1 /* C7 */] <0.21968359f
            ? -0.10735928f
            : (data[1 /* C7 */] <0.23656848f ? 0.13731155f : 0.0027772842f)))));
    return pred;
  }
}


class gbm6_Forest_41 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_41_class_0.score0(fdata);
  }
}
class gbm6_Tree_41_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.25923488f
      ? (data[0 /* C6 */] <0.3930801f
        ? (data[1 /* C7 */] <0.2062168f
          ? (data[2 /* C8 */] <0.21474218f
            ? (data[2 /* C8 */] <0.20807837f ? -0.003200297f : -0.06613706f)
            : (data[2 /* C8 */] <0.21543372f ? 0.09872624f : 5.142936E-4f))
          : (data[0 /* C6 */] <0.337875f
            ? (data[2 /* C8 */] <0.24189453f ? 0.12825555f : 0.010891485f)
            : (data[2 /* C8 */] <0.24740234f ? -0.032413594f : 0.106550135f)))
        : (data[0 /* C6 */] <0.42373633f
          ? (data[2 /* C8 */] <0.20301367f
            ? -0.12158433f
            : (data[1 /* C7 */] <0.19667187f ? -0.007709894f : -0.064684674f))
          : (data[2 /* C8 */] <0.23944922f
            ? (data[0 /* C6 */] <0.46379688f ? 0.027886571f : -0.011330345f)
            : (data[0 /* C6 */] <0.4416875f ? -0.0753584f : -0.0204676f))))
      : (data[2 /* C8 */] <0.26069143f
        ? (data[0 /* C6 */] <0.37321582f ? 0.14218168f : 0.02971708f)
        : (data[0 /* C6 */] <0.24748828f
          ? -0.16944188f
          : (data[0 /* C6 */] <0.26687127f
            ? 0.16802089f
            : (data[0 /* C6 */] <0.55307335f ? 0.009201812f : -0.0049932064f)))));
    return pred;
  }
}


class gbm6_Forest_42 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_42_class_0.score0(fdata);
  }
}
class gbm6_Tree_42_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.44445118f
      ? (data[2 /* C8 */] <0.4357998f
        ? (data[2 /* C8 */] <0.4341033f
          ? (data[0 /* C6 */] <0.59408206f
            ? (data[1 /* C7 */] <0.3043047f ? -0.0010229406f : 0.031982396f)
            : (data[1 /* C7 */] <0.3699922f ? -0.020144362f : 0.017117742f))
          : 0.11263443f)
        : (data[0 /* C6 */] <0.61838865f ? -0.15784346f : -0.023261031f))
      : (data[2 /* C8 */] <0.445546f
        ? 0.17213073f
        : (data[0 /* C6 */] <0.5134063f
          ? (data[0 /* C6 */] <0.48968568f
            ? (data[1 /* C7 */] <0.274f ? -0.042792704f : 0.13995272f)
            : -0.24153285f)
          : (data[0 /* C6 */] <0.5362483f
            ? 0.18389224f
            : (data[0 /* C6 */] <1.0418664f ? 0.013249453f : -0.03387071f)))));
    return pred;
  }
}


class gbm6_Forest_43 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_43_class_0.score0(fdata);
  }
}
class gbm6_Tree_43_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C7 */] <0.4325398f
      ? (data[0 /* C6 */] <0.70674413f
        ? (data[0 /* C6 */] <0.7012305f
          ? (data[2 /* C8 */] <0.4170117f
            ? (data[2 /* C8 */] <0.41051933f ? -6.048136E-4f : -0.06745179f)
            : (data[1 /* C7 */] <0.3549375f ? 0.033092674f : -0.035032924f))
          : 0.15811811f)
        : (data[2 /* C8 */] <0.64044726f
          ? (data[0 /* C6 */] <0.9233438f
            ? (data[2 /* C8 */] <0.4563594f ? -0.022229893f : -0.056354806f)
            : (data[1 /* C7 */] <0.414875f ? 0.05112148f : -0.023458261f))
          : 0.0793474f))
      : (data[0 /* C6 */] <0.98555666f
        ? (data[2 /* C8 */] <0.56773436f
          ? (data[1 /* C7 */] <0.44118163f
            ? 0.11018813f
            : (data[2 /* C8 */] <0.47296876f ? 0.07873036f : -0.026077574f))
          : 0.13244627f)
        : (data[2 /* C8 */] <0.5314062f ? -0.0027484747f : -0.07780089f)));
    return pred;
  }
}


class gbm6_Forest_44 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_44_class_0.score0(fdata);
  }
}
class gbm6_Tree_44_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C7 */] <0.03610156f
      ? (data[1 /* C7 */] <0.03474564f
        ? (data[1 /* C7 */] <0.03227086f
          ? (data[1 /* C7 */] <0.030657496f
            ? (data[1 /* C7 */] <0.029243864f ? -0.0156617f : 0.026518162f)
            : -0.058290076f)
          : (data[1 /* C7 */] <0.033246107f
            ? 0.08498909f
            : (data[2 /* C8 */] <0.05421875f ? -0.030148596f : 0.0379313f)))
        : -0.0683207f)
      : (data[1 /* C7 */] <0.43481123f
        ? (data[1 /* C7 */] <0.40836087f
          ? (data[1 /* C7 */] <0.38802472f
            ? (data[1 /* C7 */] <0.37703958f ? 0.0011023083f : -0.06258812f)
            : (data[1 /* C7 */] <0.39301854f ? 0.22240572f : 7.7250483E-4f))
          : (data[0 /* C6 */] <0.95125f
            ? (data[0 /* C6 */] <0.8107129f ? -0.02193857f : -0.1667293f)
            : 0.026336059f))
        : (data[0 /* C6 */] <0.9842461f
          ? (data[2 /* C8 */] <0.49507812f
            ? (data[1 /* C7 */] <0.45316407f ? -0.02681922f : 0.048679758f)
            : (data[1 /* C7 */] <0.45558593f ? 0.18334696f : 0.061455574f))
          : (data[2 /* C8 */] <0.5314062f ? -0.0024736258f : -0.07002082f))));
    return pred;
  }
}


class gbm6_Forest_45 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_45_class_0.score0(fdata);
  }
}
class gbm6_Tree_45_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.28961426f
      ? (data[2 /* C8 */] <0.28539383f
        ? (data[1 /* C7 */] <0.28015625f
          ? (data[1 /* C7 */] <0.2583081f
            ? (data[0 /* C6 */] <0.5194687f ? -0.001300006f : -0.032271482f)
            : (data[0 /* C6 */] <0.47534376f ? -0.08438438f : -0.021035733f))
          : (data[1 /* C7 */] <0.29117775f ? 0.04242455f : 0.09098356f))
        : (data[1 /* C7 */] <0.21335937f ? -0.10182609f : -0.029864235f))
      : (data[1 /* C7 */] <0.15922363f
        ? (data[2 /* C8 */] <0.34166992f ? 0.19108464f : -0.12903902f)
        : (data[1 /* C7 */] <0.16626398f
          ? -0.13549092f
          : (data[2 /* C8 */] <0.29558593f
            ? (data[0 /* C6 */] <0.351375f ? 0.17493547f : 0.021188512f)
            : (data[0 /* C6 */] <0.3716719f ? -0.036626928f : 0.0042728516f)))));
    return pred;
  }
}


class gbm6_Forest_46 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_46_class_0.score0(fdata);
  }
}
class gbm6_Tree_46_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.5091299f
      ? (data[2 /* C8 */] <0.4754201f
        ? (data[2 /* C8 */] <0.4717176f
          ? (data[1 /* C7 */] <0.4443125f
            ? (data[0 /* C6 */] <0.70103127f ? 2.2924361E-4f : -0.023344142f)
            : 0.079890974f)
          : 0.22440438f)
        : (data[0 /* C6 */] <0.68654686f
          ? (data[0 /* C6 */] <0.6025838f
            ? (data[1 /* C7 */] <0.25879687f ? -0.008294011f : -0.09102164f)
            : -0.16384995f)
          : (data[2 /* C8 */] <0.50115234f
            ? (data[2 /* C8 */] <0.49674335f ? -0.0183685f : 0.09618477f)
            : -0.056126963f)))
      : (data[2 /* C8 */] <0.5159094f
        ? 0.15828642f
        : (data[2 /* C8 */] <0.5216409f
          ? -0.11165469f
          : (data[1 /* C7 */] <0.3561875f
            ? (data[2 /* C8 */] <0.6288281f ? 0.123410486f : -0.04330062f)
            : (data[1 /* C7 */] <0.38773534f ? -0.11024474f : 0.0098367045f)))));
    return pred;
  }
}


class gbm6_Forest_47 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_47_class_0.score0(fdata);
  }
}
class gbm6_Tree_47_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C7 */] <0.11917187f
      ? (data[1 /* C7 */] <0.11627461f
        ? (data[2 /* C8 */] <0.22780469f
          ? (data[2 /* C8 */] <0.21100864f
            ? (data[2 /* C8 */] <0.19791435f ? -0.003134802f : -0.08863364f)
            : 0.10396661f)
          : -0.07371808f)
        : (data[1 /* C7 */] <0.11725405f
          ? -0.078373305f
          : (data[2 /* C8 */] <0.16273437f ? -0.06136409f : -0.025563637f)))
      : (data[0 /* C6 */] <0.25367382f
        ? (data[2 /* C8 */] <0.2321416f
          ? (data[0 /* C6 */] <0.19023633f
            ? 0.08249012f
            : (data[0 /* C6 */] <0.20012128f ? -0.069035366f : 0.01774151f))
          : (data[0 /* C6 */] <0.23656055f ? -0.014535051f : 0.19641882f))
        : (data[0 /* C6 */] <0.25849542f
          ? (data[2 /* C8 */] <0.20561329f ? 0.008002593f : -0.12949413f)
          : (data[2 /* C8 */] <0.16316797f
            ? (data[0 /* C6 */] <0.33534375f ? -0.05242825f : 0.0020106428f)
            : (data[0 /* C6 */] <0.33534375f ? 0.015409691f : -6.524746E-4f)))));
    return pred;
  }
}


class gbm6_Forest_48 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_48_class_0.score0(fdata);
  }
}
class gbm6_Tree_48_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[2 /* C8 */] <0.3572329f
      ? (data[1 /* C7 */] <0.32239747f
        ? (data[1 /* C7 */] <0.30102146f
          ? (data[1 /* C7 */] <0.2751954f
            ? (data[1 /* C7 */] <0.25802693f ? -0.0012326608f : -0.036790524f)
            : (data[0 /* C6 */] <0.49096093f ? 0.08415439f : 0.0026729964f))
          : (data[0 /* C6 */] <0.5240664f
            ? (data[1 /* C7 */] <0.31078905f ? -0.082803905f : -0.16298622f)
            : (data[0 /* C6 */] <0.5819435f ? 0.048827272f : -0.081148f)))
        : (data[0 /* C6 */] <0.55253124f
          ? (data[2 /* C8 */] <0.32265624f ? 0.03468879f : 0.30079716f)
          : (data[1 /* C7 */] <0.36463085f
            ? (data[1 /* C7 */] <0.34224883f ? -0.028095888f : -0.08681162f)
            : 0.06504992f)))
      : (data[0 /* C6 */] <0.43664452f
        ? (data[1 /* C7 */] <0.2370332f
          ? (data[2 /* C8 */] <0.37707812f
            ? (data[0 /* C6 */] <0.3794375f ? 0.13149792f : 0.31086788f)
            : (data[2 /* C8 */] <0.40244335f ? -0.09429785f : 0.1266431f))
          : (data[1 /* C7 */] <0.2659671f ? -0.1811296f : 0.065003365f))
        : (data[1 /* C7 */] <0.20233399f
          ? -0.13807318f
          : (data[1 /* C7 */] <0.26768547f
            ? (data[0 /* C6 */] <0.47032812f ? -0.09852456f : 0.056527134f)
            : (data[0 /* C6 */] <0.50315624f ? 0.058534127f : -0.0034536894f)))));
    return pred;
  }
}


class gbm6_Forest_49 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm6_Tree_49_class_0.score0(fdata);
  }
}
class gbm6_Tree_49_class_0 {
  static final double score0(double[] data) {
    double pred =  (data[1 /* C7 */] <0.032393068f
      ? (data[2 /* C8 */] <0.040699217f
        ? (data[2 /* C8 */] <0.03472746f
          ? (data[1 /* C7 */] <0.026708985f
            ? (data[1 /* C7 */] <0.010328369f ? -0.023538295f : -0.004709867f)
            : -0.048087716f)
          : (data[1 /* C7 */] <0.028185546f
            ? (data[2 /* C8 */] <0.036246095f ? 0.02131634f : -0.03724569f)
            : 0.05226786f))
        : (data[0 /* C6 */] <0.074328125f
          ? (data[2 /* C8 */] <0.04704492f ? -0.027509859f : -0.13288735f)
          : 0.016453397f))
      : (data[0 /* C6 */] <0.05908594f
        ? (data[2 /* C8 */] <0.046367187f ? 0.030875454f : 0.08294608f)
        : (data[2 /* C8 */] <0.68671876f
          ? (data[2 /* C8 */] <0.65107787f
            ? (data[2 /* C8 */] <0.60294676f ? 3.3484635E-4f : 0.052634776f)
            : -0.09421197f)
          : 0.050181266f)));
    return pred;
  }
}


